CREATE OR REPLACE PROCEDURE ERP.WORKS_GROUP_MEMBER_V2_UPD
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	30/05/2017
	DESCRIPTION	:	C?P NH?T THÔNG TIN THANH VIEN THEO CONG VIEC 
*/
(
  V_OUT OUT SYS_REFCURSOR,
	V_WORKSSUPPORTGROUPID IN EO_WORKSSUPPORTGROUP_MEMBER.WORKSSUPPORTGROUPID%TYPE,
	V_MEMBERUSERNAME IN EO_WORKSSUPPORTGROUP_MEMBER.MEMBERUSERNAME%TYPE,
	V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORTGROUP_MEMBER.WORKSSUPPORTMEMBERROLEID%TYPE,
  V_ISAUTOADDWORKSSUPPORT IN EO_WORKSSUPPORTGROUP_MEMBER.ISAUTOADDMEMBERTOWORKSSUPPORT%TYPE,
	V_DESCRIPTION IN EO_WORKSSUPPORTGROUP_MEMBER.DESCRIPTION%TYPE,
	V_ORDERINDEX IN EO_WORKSSUPPORTGROUP_MEMBER.ORDERINDEX%TYPE,
	V_ISACTIVE IN EO_WORKSSUPPORTGROUP_MEMBER.ISACTIVE%TYPE,
  V_ISSYSTEM IN EO_WORKSSUPPORTGROUP_MEMBER.ISSYSTEM%TYPE,
  V_UPDATEDUSER IN EO_WORKSSUPPORTGROUP_MEMBER.UPDATEDUSER%TYPE

) 
AS
BEGIN
    UPDATE EO_WORKSSUPPORTGROUP_MEMBER
  	SET
  		
      MEMBERUSERNAME =  V_MEMBERUSERNAME,
  		WORKSSUPPORTMEMBERROLEID	= V_WORKSSUPPORTMEMBERROLEID,
      ISAUTOADDMEMBERTOWORKSSUPPORT = V_ISAUTOADDWORKSSUPPORT,
  		DESCRIPTION	= V_DESCRIPTION,
  		ORDERINDEX	= V_ORDERINDEX,
  		ISACTIVE	= V_ISACTIVE,
  		ISSYSTEM	= V_ISSYSTEM,
      UPDATEDUSER= V_UPDATEDUSER

  	WHERE
  		WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID;

	 OPEN V_OUT FOR 
    SELECT * 
      FROM EO_WORKSSUPPORTGROUP_MEMBER WHERE  WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID;
    RETURN;
END;
/