create or replace PROCEDURE     EO_WORKSSUPPORT_QUALITY
/*
	CREATED BY	:	NGUY?N QU?C OAI
	DATE		:	03/08/2017
	DESCRIPTION	:	L?Y DANH SÁCH CH?T LÝ?NG THEO LO?I CÔNG VI?C
*/
(
    V_OUT OUT SYS_REFCURSOR,
	V_WORKSSUPPORTID IN EO_WORKSSUPPORT.WORKSSUPPORTTYPEID%TYPE
)
AS
BEGIN
   OPEN V_OUT FOR
   SELECT EO_WORKSSUPPORTQUALITY.WORKSSUPPORTQUALITYID,
   EO_WORKSSUPPORTQUALITY.WORKSSUPPORTQUALITYNAME
   FROM EO_WORKSSUPPORT
   INNER JOIN EO_WORKSSUPPORTTYPE_QUALITY ON EO_WORKSSUPPORT.WORKSSUPPORTTYPEID = EO_WORKSSUPPORTTYPE_QUALITY.WORKSSUPPORTTYPEID
   INNER JOIN EO_WORKSSUPPORTQUALITY ON EO_WORKSSUPPORTTYPE_QUALITY.WORKSSUPPORTQUALITYID = EO_WORKSSUPPORTQUALITY.WORKSSUPPORTQUALITYID
   WHERE EO_WORKSSUPPORT.WORKSSUPPORTID = V_WORKSSUPPORTID
   AND EO_WORKSSUPPORTQUALITY.ISACTIVE = 1
   AND EO_WORKSSUPPORTQUALITY.ISDELETED = 0;
END;