CREATE OR REPLACE PROCEDURE ERP."SYS_USER_ADD" 
/*
	Created by	:	Nguy?n Linh Tu?n
	Date		:	18/07/2012
	Description	:	Thêm thông tin Ngu?i dùng 

  Modify by	:	Nguy?n Linh Tu?n
	Date		:	11/12/2013
	Description	:	Thêm c?t DEFAULTPICTUREFILEID, SIGNATUREPICTUREFILEID

  Modified by	:	Nguy?n Minh Tri?u
	Date		:	09/06/2014
	Description	:	Thêm c?t v? trí công vi?c (WorkingPositionID)
*/
(
	v_USERNAME IN SYS_USER.USERNAME%TYPE,
	v_PASSWORD IN SYS_USER.PASSWORD%TYPE,
	v_FULLNAME IN SYS_USER.FULLNAME%TYPE,
	v_FIRSTNAME IN SYS_USER.FIRSTNAME%TYPE,
	v_LASTNAME IN SYS_USER.LASTNAME%TYPE,
	v_GENDER IN SYS_USER.GENDER%TYPE,
	v_BIRTHDAY IN SYS_USER.BIRTHDAY%TYPE,
	v_EMAIL IN SYS_USER.EMAIL%TYPE DEFAULT NULL,
	v_PHONENUMBER IN SYS_USER.PHONENUMBER%TYPE DEFAULT NULL,
	v_MOBI IN SYS_USER.MOBI%TYPE, 
	v_ADDRESS IN SYS_USER.ADDRESS%TYPE DEFAULT NULL,
	v_DEPARTMENTID IN SYS_USER.DEPARTMENTID%TYPE,
	v_POSITIONID IN SYS_USER.POSITIONID%TYPE,
	v_AREAID IN SYS_USER.AREAID%TYPE,
	v_DESCRIPTION IN SYS_USER.DESCRIPTION%TYPE DEFAULT NULL,
	v_BANKACCOUNTID IN SYS_USER.BANKACCOUNTID%TYPE DEFAULT NULL,
	v_IDCARD IN SYS_USER.IDCARD%TYPE DEFAULT NULL,
	v_BEGINWORKDATE IN SYS_USER.BEGINWORKDATE%TYPE,
	v_WORKSTOREID IN SYS_USER.WORKSTOREID%TYPE,
	v_SIGNATUREPICTURE IN SYS_USER.SIGNATUREPICTURE%TYPE DEFAULT NULL,
	v_DEFAULTPICTUREURL IN SYS_USER.DEFAULTPICTUREURL%TYPE DEFAULT NULL,
	v_ISGROUPUSER IN SYS_USER.ISGROUPUSER%TYPE,
	v_ISACTIVE IN SYS_USER.ISACTIVE%TYPE,
	v_ISSYSTEM IN SYS_USER.ISSYSTEM%TYPE,
	v_CREATEDUSER IN SYS_USER.CREATEDUSER%TYPE,
  v_ISAUTOADDCUMUTIMEOFFDAYS IN SYS_USER.ISAUTOADDCUMULATIONTIMEOFFDAYS%TYPE DEFAULT 0,
  v_DEFAULTPICTUREFILEID IN SYS_USER.DEFAULTPICTUREFILEID%TYPE DEFAULT NULL,
  v_SIGNATUREPICTUREFILEID IN SYS_USER.SIGNATUREPICTUREFILEID%TYPE DEFAULT NULL,
  V_WORKINGPOSITIONID IN SYS_USER.WORKINGPOSITIONID%TYPE DEFAULT 0,
  v_ISREALSTAFF IN SYS_USER.ISREALSTAFF%TYPE,
	v_CERTIFICATESTRING IN SYS_USER_LOG.CERTIFICATESTRING%TYPE,
	v_USERHOSTADDRESS IN SYS_USER_LOG.USERHOSTADDRESS%TYPE,
	v_LOGINLOGID IN SYS_USER_LOG.LOGINLOGID%TYPE,
  V_ISAUTOGENID IN NUMBER DEFAULT 0,
  v_IsCreatedEmployee IN NUMBER DEFAULT 0
)
AS
t_WorkingStatusIDConfig NUMBER;
BEGIN

	INSERT
	INTO SYS_USER
	(
		USERNAME,
		PASSWORD,
		FULLNAME,
		FIRSTNAME,
		LASTNAME,
		GENDER,
		BIRTHDAY,
		EMAIL,
		PHONENUMBER,
		MOBI,
		ADDRESS,
		DEPARTMENTID,
		POSITIONID,
		AREAID,
		DESCRIPTION,
		BANKACCOUNTID,
		IDCARD,
		BEGINWORKDATE,
		WORKSTOREID,
		SIGNATUREPICTURE,
		DEFAULTPICTUREURL,
		ISGROUPUSER,
		ISACTIVE,
		ISSYSTEM,
		CREATEDUSER,
		CREATEDDATE,
    ISAUTOADDCUMULATIONTIMEOFFDAYS,
    DEFAULTPICTUREFILEID,
    SIGNATUREPICTUREFILEID,
    WORKINGPOSITIONID,
    ISREALSTAFF
	)
	VALUES
	(
		v_USERNAME,
		v_PASSWORD,
		v_FULLNAME,
		v_FIRSTNAME,
		v_LASTNAME,
		v_GENDER,
		v_BIRTHDAY,
		v_EMAIL,
		v_PHONENUMBER,
		v_MOBI,
		v_ADDRESS,
		v_DEPARTMENTID,
		v_POSITIONID,
		v_AREAID,
		v_DESCRIPTION,
		v_BANKACCOUNTID,
		v_IDCARD,
		v_BEGINWORKDATE,
		v_WORKSTOREID,
		v_SIGNATUREPICTURE,
		v_DEFAULTPICTUREURL,
		v_ISGROUPUSER,
		v_ISACTIVE,
		v_ISSYSTEM,
		v_CREATEDUSER,
		SYSDATE,
    v_ISAUTOADDCUMUTIMEOFFDAYS,
    v_DEFAULTPICTUREFILEID,
    v_SIGNATUREPICTUREFILEID,
    V_WORKINGPOSITIONID,
    V_ISREALSTAFF
	);
	INSERT
	INTO SYS_USER_LOG
	(
		USERNAME,
		PASSWORD,
		FULLNAME,
		FIRSTNAME,
		LASTNAME,
		GENDER,
		BIRTHDAY,
		EMAIL,
		PHONENUMBER,
		MOBI,
		ADDRESS,
		DEPARTMENTID,
		POSITIONID,
		AREAID,
		DESCRIPTION,
		BANKACCOUNTID,
		IDCARD,
		BEGINWORKDATE,
		WORKSTOREID,
		SIGNATUREPICTURE,
		DEFAULTPICTUREURL,
		ISGROUPUSER,
		ISACTIVE,
		ISSYSTEM,
		UPDATEDUSER,
		UPDATEDDATE,
		LOGTYPE,
    ISAUTOADDCUMULATIONTIMEOFFDAYS,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID,
    DEFAULTPICTUREFILEID,
    SIGNATUREPICTUREFILEID,
    WORKINGPOSITIONID,
    ISREALSTAFF
	)
	VALUES
	(
		v_USERNAME,
		v_PASSWORD,
		v_FULLNAME,
		v_FIRSTNAME,
		v_LASTNAME,
		v_GENDER,
		v_BIRTHDAY,
		v_EMAIL,
		v_PHONENUMBER,
		v_MOBI,
		v_ADDRESS,
		v_DEPARTMENTID,
		v_POSITIONID,
		v_AREAID,
		v_DESCRIPTION,
		v_BANKACCOUNTID,
		v_IDCARD,
		v_BEGINWORKDATE,
		v_WORKSTOREID,
		v_SIGNATUREPICTURE,
		v_DEFAULTPICTUREURL,
		v_ISGROUPUSER,
		v_ISACTIVE,
		v_ISSYSTEM,
		v_CREATEDUSER,
		SYSDATE,
		1,
    v_ISAUTOADDCUMUTIMEOFFDAYS,
		v_USERHOSTADDRESS,
		v_CERTIFICATESTRING,
		v_LOGINLOGID,
    v_DEFAULTPICTUREFILEID,
    v_SIGNATUREPICTUREFILEID,
    V_WORKINGPOSITIONID,
    v_ISREALSTAFF
	);
   IF v_IsCreatedEmployee =1 THEN
    BEGIN      
      BEGIN
         SELECT to_number( SYS_APPCONFIG.CONFIGVALUE) INTO t_WorkingStatusIDConfig
         FROM 
          SYS_APPCONFIG
         WHERE
          SYS_APPCONFIG.APPCONFIGID='EMPLOYEE_WORKHISTORY_WORKINGSTATUSID';
         EXCEPTION
          WHEN OTHERS THEN t_WorkingStatusIDConfig:=0;
      END;
       HR_EMPLOYEE_IMP(v_USERNAME,t_WorkingStatusIDConfig, v_CREATEDUSER);
       HR_EMPLOYEE_WORKHISTORY_ADD('',v_USERNAME,v_BEGINWORKDATE,NULL,V_WORKINGPOSITIONID,v_DEPARTMENTID,t_WorkingStatusIDConfig,'','','',NULL,'','',0,1,0,v_CREATEDUSER,v_WORKSTOREID,v_CERTIFICATESTRING,v_USERHOSTADDRESS,v_LOGINLOGID);
       INSERT INTO ERP.sys_user_sound(username,soundfullname) VALUES(v_USERNAME,'Sound\FullName\' || TRIM(v_USERNAME) || '.mp3');
    END;
  END IF;
END;
/