CREATE OR REPLACE PROCEDURE ERP.WORKSUPORTGROUP_V2_DEL
/*
	Created by	:	Nguy?n Van Huan
	Date		:	09/06/2017
	Description	:	Xóa thông tin nhom cong viec
*/
(
	v_WORKSSUPPORTGROUPID IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTGROUPID%TYPE,
	v_DELETEDUSER IN EO_WORKSSUPPORTGROUP.DELETEDUSER%TYPE,
  v_CERTIFICATESTRING IN EO_WORKSSUPPORTGROUP_LOG.CERTIFICATESTRING%TYPE,
	v_USERHOSTADDRESS IN EO_WORKSSUPPORTGROUP_LOG.USERHOSTADDRESS%TYPE,
	v_LOGINLOGID IN EO_WORKSSUPPORTGROUP_LOG.LOGINLOGID%TYPE
)
AS
  T_GROUPID NUMBER:= 0;
BEGIN
  -- Xóa nhom công vi?c c?n h? tr?
	UPDATE EO_WORKSSUPPORTGROUP
	SET
		ISDELETED = 1,
		DELETEDDATE = SYSDATE,
		DELETEDUSER = v_DELETEDUSER
	WHERE
		WORKSSUPPORTGROUPID = WORKSSUPPORTGROUPID;
  insert
  INTO EO_WORKSSUPPORTGROUP_LOG
	(
		WORKSSUPPORTGROUPID,
		WORKSSUPPORTGROUPNAME,
		WORKSSUPPORTPROJECTID,
    WORKSSUPPORTTYPEID,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		UPDATEDUSER,
		UPDATEDDATE,
		LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID

	)
  SELECT
		WORKSSUPPORTGROUPID,
		WORKSSUPPORTGROUPNAME,
		WORKSSUPPORTPROJECTID,
    1,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM, 
		v_DELETEDUSER,
		UPDATEDDATE,
    3,
		v_USERHOSTADDRESS,
		v_CERTIFICATESTRING,
		v_LOGINLOGID

    FROM 
      EO_WORKSSUPPORTGROUP 
    WHERE 
      WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID;
  -- Xóa công vi?c c?n ho tro tuong ung v?i d? án

  UPDATE EO_WORKSSUPPORT  
    SET ISDELETED = 1,
        DELETEDUSER =V_DELETEDUSER,
        DELETEDDATE = SYSDATE 
    WHERE WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID;
    INSERT
	INTO EO_WORKSSUPPORT_LOG
	(
	  WORKSSUPPORTID,
		WORKSSUPPORTNAME,
		UPDATEDUSER,
		UPDATEDDATE,
		LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID

	)
  SELECT
		WORKSSUPPORTID,
		WORKSSUPPORTNAME,
		v_DELETEDUSER,
		UPDATEDDATE,
    3,
		v_USERHOSTADDRESS,
		v_CERTIFICATESTRING,
		v_LOGINLOGID

    FROM 
      EO_WORKSSUPPORT
    WHERE 
     WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID;
END;
/