CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORT_CM_V2_SRH_BETA
/*
	Created by	:	YourName 
	Date		:	09/03/2013
	Description	:	N?p danh sách  
*/
(
    v_Out OUT SYS_REFCURSOR,
    	v_COMMENTID IN EO_WORKSSUPPORT_COMMENT.COMMENTID%TYPE DEFAULT -1,
  v_WORKSSUPPORTID IN EO_WORKSSUPPORT_COMMENT.WORKSSUPPORTID%TYPE DEFAULT -1
) 
AS
BEGIN
    OPEN v_Out FOR
	SELECT
		EO_WORKSSUPPORT_COMMENT.COMMENTID,
		EO_WORKSSUPPORT_COMMENT.WORKSSUPPORTID,
		EO_WORKSSUPPORT_COMMENT.COMMENTDATE,
    REPLACE(REPLACE(REPLACE(EO_WORKSSUPPORT_COMMENT.COMMENTCONTENT,'&lt;','<'),'&gt;','>'),'&amp;nbsp;',' ') COMMENTCONTENT,
		EO_WORKSSUPPORT_COMMENT.COMMENTUSER,
    SYS_USER.FULLNAME FULLNAME,
		EO_WORKSSUPPORT_COMMENT.ORDERINDEX,
		EO_WORKSSUPPORT_COMMENT.ISACTIVE,
		EO_WORKSSUPPORT_COMMENT.ISSYSTEM,
		EO_WORKSSUPPORT_COMMENT.CREATEDUSER,
		EO_WORKSSUPPORT_COMMENT.CREATEDDATE,
		EO_WORKSSUPPORT_COMMENT.UPDATEDUSER,
		EO_WORKSSUPPORT_COMMENT.UPDATEDDATE,
		EO_WORKSSUPPORT_COMMENT.ISDELETED,
		EO_WORKSSUPPORT_COMMENT.DELETEDUSER,
		EO_WORKSSUPPORT_COMMENT.DELETEDDATE,
    
    SYS_DEPARTMENT.DEPARTMENTNAME,
    SYS_USER.DEFAULTPICTUREURL
	FROM EO_WORKSSUPPORT_COMMENT
  LEFT JOIN SYS_USER ON SYS_USER.USERNAME = EO_WORKSSUPPORT_COMMENT.COMMENTUSER
  LEFT JOIN SYS_DEPARTMENT ON SYS_DEPARTMENT.DEPARTMENTID = SYS_USER.DEPARTMENTID
	WHERE EO_WORKSSUPPORT_COMMENT.ISDELETED = 0
  
  AND 
  	
		(v_COMMENTID = -1 OR COMMENTID = v_COMMENTID)
    AND (v_WORKSSUPPORTID = -1 OR WORKSSUPPORTID = v_WORKSSUPPORTID)
  ORDER BY  EO_WORKSSUPPORT_COMMENT.COMMENTDATE  
  --xap sep theo ngay truoc
;
END;
/