CREATE OR REPLACE PROCEDURE ERP.SYS_USER_SRH
/*
	Created by	:	Truong Trung L?i 
	Date		:	18/07/2012
	Description	:	N?p danh sách Ngu?i dùng 
*/
(
    v_Out OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN v_Out FOR
	SELECT
		USERNAME,
		PASSWORD,
		FULLNAME,
		FIRSTNAME,
		LASTNAME,
		GENDER,
		BIRTHDAY,
		EMAIL,
		PHONENUMBER,
		MOBI,
		ADDRESS,
		DEPARTMENTID,
		POSITIONID,
		AREAID,
		DESCRIPTION,
		BANKACCOUNTID,
		IDCARD,
		BEGINWORKDATE,
		WORKSTOREID,
		SIGNATUREPICTURE,
		DEFAULTPICTUREURL,
		ISGROUPUSER,
		ISACTIVE,
		ISSYSTEM,SYS_USER.ISAUTOADDCUMULATIONTIMEOFFDAYS,
		CREATEDUSER,
		CREATEDDATE,
		UPDATEDUSER,
		UPDATEDDATE,
		ISDELETED,
		DELETEDUSER,
		DELETEDDATE,
    DEFAULTPICTUREFILEID,
    SIGNATUREPICTUREFILEID,
    WORKINGPOSITIONID,
    ISREALSTAFF
	FROM SYS_USER
	WHERE ISDELETED = 0
;
END;
/