create or replace PROCEDURE WORKSSUPPORT_WFNX_V2_MEMBER
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	02/06/2017
	DESCRIPTION	:	N?P DANH SACH NGUOI THUC HIEN TRONG CONG VIEC CAN HO TRO
*/ (
    V_OUT                  OUT SYS_REFCURSOR,
    V_WORKSSUPPORTID       IN EO_WORKSSUPPORT.WORKSSUPPORTID%TYPE,
    V_WORKSSUPPORTSTEPID   IN EO_WORKSSUPPORT.WORKSSUPPORTID%TYPE
)
    AS
BEGIN
    OPEN V_OUT FOR
        SELECT
            US.USERNAME,
            US.FULLNAME
        FROM
            SYS_USER US
            INNER JOIN EO_WORKSSUPPORTGROUP_MEMBER ME ON US.USERNAME = ME.MEMBERUSERNAME
            INNER JOIN EO_WORKSSUPPORTTYPE_WF_PERMIS WF ON ME.WORKSSUPPORTMEMBERROLEID = WF.WORKSSUPPORTMEMBERROLEID
        WHERE
            ME.WORKSSUPPORTGROUPID = (
                SELECT
                    WORKSSUPPORTGROUPID
                FROM
                    EO_WORKSSUPPORT
                WHERE
                    WORKSSUPPORTID = V_WORKSSUPPORTID
            )
        AND
            WF.WORKSSUPPORTSTEPID = V_WORKSSUPPORTSTEPID;

END;