create or replace PROCEDURE     EO_WORKSSUPPORTTYPE_WF_P_SEL
/*
	CREATED BY	:	LÝÕNG TRUNG NHÂN 
	DATE		:	02/06/2017
	DESCRIPTION	:	N?P THÔNG TIN B?NG CH?A CÁC BÝ?C X? L? K? TI?P
*/
(	
	V_WORKSSUPPORTSTEPID IN EO_WORKSSUPPORTTYPE_WF_PERMIS.WORKSSUPPORTSTEPID%TYPE,	
	V_OUT OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN V_OUT FOR
	SELECT
		WORKSSUPPORTSTEPID,
		WORKSSUPPORTMEMBERROLEID
	FROM 
    EO_WORKSSUPPORTTYPE_WF_PERMIS
	WHERE
		V_WORKSSUPPORTSTEPID = WORKSSUPPORTSTEPID
;
END;
