CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTPRIORITY_V2_SEL 
/*
	CREATED BY	:	TRUONG HOANG NHI
	DATE		    :	29/05/2017
	DESCRIPTION	:	DANH SACH DO UU TIÊN
  UPDATE : NGUYEN THI KIM NGAN
*/
(	
    V_OUT OUT SYS_REFCURSOR,
    V_KEYWORDS NVARCHAR2 DEFAULT NULL,
    V_PAGEINDEX NUMBER DEFAULT -1,
    V_PAGESIZE NUMBER DEFAULT -1,
    V_ISDELETED EO_WORKSSUPPORTPRIORITY.ISDELETED%TYPE DEFAULT -1
) 
AS
BEGIN
  OPEN V_OUT FOR
       SELECT * 
    FROM
    (
  			SELECT
  			  EDB.WORKSSUPPORTPRIORITYID,
          EDB.WORKSSUPPORTPRIORITYNAME,
          EDB.ORDERINDEX,
          EDB.DESCRIPTION,
          EDB.ICONURL,
          EDB.COLORCODE,
          EDB.ISACTIVE,
          EDB.ISSYSTEM,
          EDB.ISDELETED,
  			  ROW_NUMBER() OVER (ORDER BY EDB.ORDERINDEX ASC ,EDB.CREATEDDATE DESC) STT,
          SUM(1) OVER()AS TOTALROWS
  			FROM
  				EO_WORKSSUPPORTPRIORITY EDB
    		WHERE (V_ISDELETED < 0 
              OR EDB.ISDELETED = V_ISDELETED)
              AND (
                    V_KEYWORDS IS NULL
                    OR (CAST(TRIM(V_KEYWORDS) AS NVARCHAR2(2000)) = CAST(TRIM(EDB.WORKSSUPPORTPRIORITYNAME) AS NVARCHAR2(2000)))
                    OR (UPPER(EDB.WORKSSUPPORTPRIORITYNAME) LIKE '%'|| UPPER(TRIM(V_KEYWORDS)) || '%')                 
                  )
    
      --ORDER BY TO_CHAR(EDB.CREATEDDATE,'DD/MM/YYYY HH12:MI:SS') DESC ,ORDERINDEX ASC,TO_CHAR(EDB.CREATEDDATE,'DD/MM/YYYY HH12:MI:SS') DESC
		 )EDOB
     WHERE
          V_PAGESIZE < 0 
          OR
          (STT > V_PAGEINDEX * V_PAGESIZE AND STT <= (V_PAGEINDEX + 1) * V_PAGESIZE)
      ;
END;
/