CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORT_GROUP_V2_SHR
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	17/06/2017
	DESCRIPTION	:	N?P THÔNG TIN CÔNG VI?C C?N H? TR? T? NHÓM CONG VIEC
*/
(	
	V_WORKSSUPPORTGROUPID IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTGROUPID%TYPE,	
	V_OUT OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN V_OUT FOR
	SELECT
		WORKSSUPPORTID,
    WORKSSUPPORTTYPEID,
    WORKSSUPPORTNAME,
    CONTENT,
    WORKSSUPPORTSTATUSID,
    EXPECTEDCOMPLETEDDATE,
    COMPLETEDDATE,
    CURRENTPROGRESS,
    CREATEDUSER,
    CREATEDDATE,
    UPDATEDUSER,
    UPDATEDDATE,
    ISDELETED,
    DELETEDUSER,
  DELETEDDATE,
LASTCOMMENTTIME,
  LASTACTIONTIME,
  LASTCOMMENTID,
  ATTACHMENTFILECOUNT,
  WORKSSUPPORTGROUPID,
  WORKSSUPPORTQUALITYID,
  WORKSSUPPORTPRIORITYID,
  SOLUTIONCONTENT
	FROM 
    EO_WORKSSUPPORT
	WHERE
		WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID
    AND ISDELETED = 0
;
END;
/