CREATE OR REPLACE PROCEDURE ERP.WORKSSUPORTGROUP_V2_GETMEMBER
/*
	CREATED BY	:	NGUYEN VAN HUAN
	DATE		:	29.06.2017
	DESCRIPTION	:	LAY TAT CA THANH VIEN TRONG MOT NHOM CONG VIEC
*/
(	 
  V_WORKSSUPPORTGROUPID IN EO_WORKSSUPPORTGROUP_MEMBER.WORKSSUPPORTGROUPID%TYPE,
  V_OUT OUT SYS_REFCURSOR
)
AS
BEGIN
 OPEN V_OUT FOR
    SELECT 
      SU.USERNAME,
      SU.FULLNAME,
      SU.DEFAULTPICTUREURL,
      SD.DEPARTMENTNAME,
      EWMR.WORKSSUPPORTMEMBERROLEID,
      EWMR.WORKSSUPPORTMEMBERROLENAME,
      EWSG.ISAUTOADDMEMBERTOWORKSSUPPORT    
    FROM 
      ERP.EO_WORKSSUPPORTGROUP_MEMBER EWSG
    LEFT JOIN 
        ERP.EO_WORKSSUPPORTMEMBERROLE EWMR 
      ON 
        (EWSG.WORKSSUPPORTMEMBERROLEID = EWMR.WORKSSUPPORTMEMBERROLEID AND EWMR.ISDELETED =0)
    LEFT JOIN 
        ERP.SYS_USER SU 
      ON 
        (EWSG.MEMBERUSERNAME = SU.USERNAME AND SU.ISDELETED =0 )
    LEFT JOIN 
        ERP.SYS_DEPARTMENT SD 
      ON 
        (SD.DEPARTMENTID = SU.DEPARTMENTID AND SD.ISDELETED =0)
    WHERE  
       EWSG.WORKSSUPPORTGROUPID =  V_WORKSSUPPORTGROUPID AND EWSG.ISDELETED = 0;                                                                                                                                                                                                                                                                                                                                                         
END;
/