CREATE OR REPLACE PROCEDURE ERP.WORKSSUPORTPROJECT_V2_ISMEMBER
/*
	CREATED BY	:	NGUY?N VAN HUÂN
	DATE		:	03/08/2017
	DESCRIPTION	:	KI?M TRA THÀNH VIÊN C?A D? ÁN.
*/
(
    V_OUT OUT SYS_REFCURSOR,
    V_MEMBERUSERNAME EO_WORKSSUPPORTPROJECT_MEMBER.MEMBERUSERNAME%TYPE     
) 
AS
BEGIN
   OPEN V_OUT FOR
   SELECT EW.WORKSSUPPORTPROJECTID 
   FROM EO_WORKSSUPPORTPROJECT_MEMBER EW
   WHERE EW.MEMBERUSERNAME = V_MEMBERUSERNAME AND EW.ISDELETED = 0;
END;
/