CREATE OR REPLACE PROCEDURE ERP."EO_WORKSSUPPORTTYPE_M_SRH" 
/*
	CREATED BY	:	LUONG TRUNG NHÂN
	DATE		:	08/06/2017
	DESCRIPTION	:	TÌM KI?M THÔNG TIN VÀI TRÒ C?A M?T CÔNG VI?C C?N H? TR? 
*/
(
    V_OUT OUT SYS_REFCURSOR,
    V_KEYWORDS NVARCHAR2 DEFAULT NULL,	
    V_PAGESIZE NUMBER DEFAULT 10,
    V_PAGEINDEX NUMBER DEFAULT -1,
    V_ISDELETED IN EO_WORKSSUPPORTMEMBERROLE.ISDELETED%TYPE DEFAULT -1    
) 
AS
BEGIN
    OPEN V_OUT FOR
    	SELECT *
  FROM(
	SELECT	
		EO_WORKSSUPPORTTYPE_MEMBERROLE.WORKSSUPPORTTYPEID,
		EO_WORKSSUPPORTTYPE_MEMBERROLE.WORKSSUPPORTMEMBERROLEID,
    WR.WORKSSUPPORTMEMBERROLENAME,
		EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANADDWORKSSUPPORTGROUP,
		EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANADDWORKSSUPPORT,
		EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANEDITCONTENT,
		EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANEDITSOLUTIONCONTENT,
		EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANADDATTACHMENT,
		EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANCOMMENT,
		EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANEDITEXPECTEDCOMPLETEDDATE,
		EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANCHANGEPROGRESS,
		EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANEDITQUALITY,
		EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANEDITWORKSSUPPORTGROUP,
		EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANEDITWORKSSUPPORT,
		EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANDELETEWORKSSUPPORTGROUP,
		EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANDELETEWORKSSUPPORT,		
        EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANDELETEWORKSSUPPORT,
    ROW_NUMBER() OVER (ORDER BY  EO_WORKSSUPPORTTYPE_MEMBERROLE.WORKSSUPPORTTYPEID ASC) STT,
    SUM(1) OVER()AS TOTALROWS
	FROM EO_WORKSSUPPORTTYPE_MEMBERROLE
  JOIN EO_WORKSSUPPORTMEMBERROLE WR ON EO_WORKSSUPPORTTYPE_MEMBERROLE.WORKSSUPPORTMEMBERROLEID = WR.WORKSSUPPORTMEMBERROLEID	
	WHERE
  (V_KEYWORDS IS NULL OR WR.workssupportmemberroleid LIKE '%' || V_KEYWORDS || '%'   OR  UPPER(WR.WORKSSUPPORTMEMBERROLENAME) LIKE '%'||UPPER(V_KEYWORDS)||'%')
	 AND (V_ISDELETED = -1 OR WR.ISDELETED=V_ISDELETED)	
 )
  WHERE
      (STT > V_PAGEINDEX * V_PAGESIZE AND STT <= (V_PAGEINDEX + 1) * V_PAGESIZE)
        OR V_PAGEINDEX = -1
;

END;
/