CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTTYPE_V2_SEL
/*
	Created by	:	Hoàng Nhu Phong 
	Date		:	02/03/2013
	Description	:	N?p thông tin Lo?i công vi?c c?n h? tr? 
*/
(	
	v_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE.WORKSSUPPORTTYPEID%type,	
	v_Out OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN v_Out FOR
	SELECT
		WORKSSUPPORTTYPEID,
		WORKSSUPPORTTYPENAME,
		ICONURL,
		ADDFUNCTIONID,
		VIEWALLFUNCTIONID,
		EDITFUNCTIONID,
		EDITALLFUNCTIONID,
		DELETEFUNCTIONID,
		DELETEALLFUNCTIONID,
		PROCESSFUNCTIONID,
		COMMENTFUNCTIONID,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		CREATEDUSER,
		CREATEDDATE,
		UPDATEDUSER,
		UPDATEDDATE,
		ISDELETED,
		DELETEDUSER,
		DELETEDDATE,
    CHOOSEPROCESSUSERTYPE,
    CHOOSEREFERENCEUSERTYPE,
    ISHASSOLUTIONCONTENT,
    ADDPROJECTFUNCTIONID
	FROM EO_WORKSSUPPORTTYPE
	WHERE
		WORKSSUPPORTTYPEID = v_WORKSSUPPORTTYPEID
  AND isdeleted = 0
;
END;
/