CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTSTATUS_V2_SRH
/*
	CREATED BY	:	HOÀNG NHU PHONG 
	DATE		:	02/03/2013
	DESCRIPTION	:	N?P DANH SÁCH TR?NG THÁI CÔNG VI?C C?N H? TR? 
  UPDATE BY :NGUY?N TH? KIM NGÂN
  DATE : 06.06.2017
  DESCRIPTION: THÊM PHÂN TRANG
*/
(
    V_OUT OUT SYS_REFCURSOR,
    V_KEYWORDS NVARCHAR2 DEFAULT NULL,
    V_ISDELETED EO_WORKSSUPPORTSTATUS.ISDELETED%TYPE DEFAULT 0,
    V_PAGEINDEX NUMBER DEFAULT -1,
    V_PAGESIZE NUMBER DEFAULT -1
) 
AS
BEGIN
   OPEN V_OUT FOR
   SELECT * 
   FROM(
	SELECT
		EO_WORKSSUPPORTSTATUS.WORKSSUPPORTSTATUSID,
		EO_WORKSSUPPORTSTATUS.WORKSSUPPORTSTATUSNAME,
		EO_WORKSSUPPORTSTATUS.ICONURL,
    EO_WORKSSUPPORTSTATUS.COLORCODE,
		EO_WORKSSUPPORTSTATUS.ISINITSTATUS,
		EO_WORKSSUPPORTSTATUS.ISCOMPLETESTATUS,
		EO_WORKSSUPPORTSTATUS.DESCRIPTION,
		EO_WORKSSUPPORTSTATUS.ORDERINDEX,
		EO_WORKSSUPPORTSTATUS.ISACTIVE,
		EO_WORKSSUPPORTSTATUS.ISSYSTEM,
		NVL2(EO_WORKSSUPPORTSTATUS.CREATEDUSER,	EO_WORKSSUPPORTSTATUS.CREATEDUSER ||'-'||CREATEDUSER.FULLNAME,'') CREATEDUSER,
		EO_WORKSSUPPORTSTATUS.CREATEDDATE,
		NVL2( EO_WORKSSUPPORTSTATUS.UPDATEDUSER,EO_WORKSSUPPORTSTATUS.UPDATEDUSER ||'-'||UPDATEDUSER.FULLNAME,'') UPDATEDUSER,
		EO_WORKSSUPPORTSTATUS.UPDATEDDATE,
		EO_WORKSSUPPORTSTATUS.ISDELETED,
		EO_WORKSSUPPORTSTATUS.DELETEDUSER,
		EO_WORKSSUPPORTSTATUS.DELETEDDATE,
    NVL(EO_WORKSSUPPORTSTATUS.ISCLOSESTATUS,0) ISCLOSESTATUS,
    ROW_NUMBER() OVER (ORDER BY EO_WORKSSUPPORTSTATUS.ORDERINDEX ASC ,EO_WORKSSUPPORTSTATUS.CREATEDDATE DESC) STT,
    SUM(1) OVER()AS TOTALROWS
	FROM 
    EO_WORKSSUPPORTSTATUS
    LEFT  JOIN SYS_USER CREATEDUSER 
      ON CREATEDUSER.USERNAME = EO_WORKSSUPPORTSTATUS.CREATEDUSER
    LEFT  JOIN SYS_USER UPDATEDUSER 
      ON UPDATEDUSER.USERNAME = EO_WORKSSUPPORTSTATUS.UPDATEDUSER
	WHERE 
    EO_WORKSSUPPORTSTATUS.ISDELETED = V_ISDELETED
    AND (V_KEYWORDS IS NULL 
         OR UPPER ( EO_WORKSSUPPORTSTATUS.WORKSSUPPORTSTATUSNAME ) LIKE '%' ||UPPER ( V_KEYWORDS )|| '%')
  ORDER BY 
    EO_WORKSSUPPORTSTATUS.ORDERINDEX
  )
  WHERE
  V_PAGESIZE < 0 
  OR
  (STT > V_PAGEINDEX * V_PAGESIZE AND STT <= (V_PAGEINDEX + 1) * V_PAGESIZE);
END;
/