CREATE OR REPLACE PROCEDURE ERP.WORKSSUPORTGROUP_V2_CHECK
/*	CREATED BY	:	NGUYEN VAN HUAN
	DATE		:	21.6.2017
	DESCRIPTION	:	KIEM TRA TEN TRUNG NHAU TRONG BANG EO_WORKSSUPPORTGROUP
*/
(	
  V_WORKSSUPPORTGROUPID IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTGROUPID%TYPE,
  V_WORKSSUPPORTPROJECTID IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTPROJECTID%TYPE,
	V_WORKSSUPPORTGROUPNAME IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTGROUPNAME%TYPE,
	V_OUT OUT SYS_REFCURSOR
) 
AS
 T_CHECK_NAME NUMBER := 0;
 --T_CHECK_ORDER NUMBER := 0;
BEGIN
  -- CHECK WORKSSUPPORTSTATUSNAME EXISTED
  BEGIN
    SELECT 
      COUNT(1) INTO T_CHECK_NAME
    FROM 
      EO_WORKSSUPPORTGROUP EO
    WHERE 
      TRIM(UPPER(EO.WORKSSUPPORTGROUPNAME)) = TRIM(UPPER(V_WORKSSUPPORTGROUPNAME)) AND 
      EO.WORKSSUPPORTGROUPID <> V_WORKSSUPPORTGROUPID  AND 
      EO.WORKSSUPPORTPROJECTID = V_WORKSSUPPORTPROJECTID  AND EO.ISDELETED =0 ;
    EXCEPTION WHEN OTHERS THEN T_CHECK_NAME := 0;
  END; 
 
  OPEN V_OUT FOR
    SELECT T_CHECK_NAME AS GROUPNAME
      FROM DUAL D;
  RETURN;    

END;
/