CREATE OR REPLACE PROCEDURE ERP.EO_WORKSSUPPORTTYPE_WFNX_P_UPD
/*
	CREATED BY	:	LUONG TRUNG NHÂN 
	DATE		:	12/06/2017
	DESCRIPTION	:	C?P NH?T THÔNG TIN B?NG CH?A CÁC BU?C X? LÝ K? TI?P THEO
*/
(
	V_WORKSSUPPORTSTEPID IN EO_WORKSSUPPORTTYPE_WFNXPERMIS.WORKSSUPPORTSTEPID%TYPE,
	V_NEXTWORKSSUPPORTSTEPID IN EO_WORKSSUPPORTTYPE_WFNXPERMIS.NEXTWORKSSUPPORTSTEPID%TYPE,
  V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORTTYPE_WFNXPERMIS.WORKSSUPPORTMEMBERROLEID%TYPE,
  V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE_WFNXPERMIS.WORKSSUPPORTTYPEID%TYPE,
  V_ISCANCHOOSENEXTSTEP IN EO_WORKSSUPPORTTYPE_WFNXPERMIS.ISCANCHOOSENEXTSTEP%TYPE
)
AS
T_COUNT NUMBER;
BEGIN
	UPDATE EO_WORKSSUPPORTTYPE_WFNXPERMIS
	SET
		NEXTWORKSSUPPORTSTEPID = V_NEXTWORKSSUPPORTSTEPID,
    WORKSSUPPORTMEMBERROLEID = V_WORKSSUPPORTMEMBERROLEID,
    ISCANCHOOSENEXTSTEP = V_ISCANCHOOSENEXTSTEP
  WHERE WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID
      AND WORKSSUPPORTSTEPID = V_WORKSSUPPORTSTEPID;
END;
/