CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORT_V2_DELETE
/*
	CREATED BY	:NGUYEN THI KIM NGAN
	DATE		:	16.06.2017
	DESCRIPTION	:	XÓA THÔNG TIN CÔNG VI?C C?N H? TR? 
*/
(
 -- V_OUT OUT NUMBER,
	V_WORKSSUPPORTID IN EO_WORKSSUPPORT.WORKSSUPPORTID%TYPE,
  V_DELETEDUSER IN EO_WORKSSUPPORT.DELETEDUSER%TYPE DEFAULT NULL,
  V_CERTIFICATESTRING IN EO_WORKSSUPPORT_LOG.CERTIFICATESTRING%TYPE DEFAULT NULL,
	V_USERHOSTADDRESS IN EO_WORKSSUPPORT_LOG.USERHOSTADDRESS%TYPE DEFAULT NULL,
	V_LOGINLOGID IN EO_WORKSSUPPORT_LOG.LOGINLOGID%TYPE DEFAULT NULL
)
AS
BEGIN
	UPDATE EO_WORKSSUPPORT
	SET
		ISDELETED = 1,
		DELETEDDATE = SYSDATE,
		DELETEDUSER = V_DELETEDUSER
	WHERE
		WORKSSUPPORTID = V_WORKSSUPPORTID;
    INSERT
	INTO EO_WORKSSUPPORT_LOG
	(
		WORKSSUPPORTID,
		WORKSSUPPORTTYPEID,
		WORKSSUPPORTNAME,
		CONTENT,
		WORKSSUPPORTSTATUSID,
		EXPECTEDCOMPLETEDDATE,
		COMPLETEDDATE,
		CURRENTPROGRESS,
		UPDATEDUSER,
		UPDATEDDATE,
		LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID

	)
  SELECT 
	WORKSSUPPORTID,
		WORKSSUPPORTTYPEID,
		WORKSSUPPORTNAME,
		CONTENT,
		WORKSSUPPORTSTATUSID,
		EXPECTEDCOMPLETEDDATE,
		COMPLETEDDATE,
		CURRENTPROGRESS,
		V_DELETEDUSER,
		DELETEDDATE,
		3,
		V_USERHOSTADDRESS,
		V_CERTIFICATESTRING,
		V_LOGINLOGID
    FROM EO_WORKSSUPPORT
WHERE
		WORKSSUPPORTID = V_WORKSSUPPORTID
    ;
	--V_OUT:=V_WORKSSUPPORTID;
END;
/