CREATE OR REPLACE PROCEDURE ERP.WORKSSUPORTGROUP_V2_GETBYID
/*
	CREATED BY	:	NGUY?N TH? KIM NGÂN
	DATE		:	24/07/2017
	DESCRIPTION	:	L?Y NHOM CONG VIEC THEO ID
*/
(	
  V_OUT OUT SYS_REFCURSOR,
	V_WORKSSUPPORTGROUPID IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTGROUPID%TYPE
) 
AS
BEGIN
  OPEN V_OUT FOR
  SELECT
    EO_WORKSSUPPORTGROUP.WORKSSUPPORTGROUPID,
    EO_WORKSSUPPORTGROUP.WORKSSUPPORTGROUPNAME,
    EO_WORKSSUPPORTGROUP.WORKSSUPPORTPROJECTID,
    EO_WORKSSUPPORTGROUP.DESCRIPTION,
    EO_WORKSSUPPORTGROUP.ORDERINDEX,
    EO_WORKSSUPPORTGROUP.ISACTIVE,
    EO_WORKSSUPPORTGROUP.ICONURL,
    EO_WORKSSUPPORTGROUP.ISSYSTEM
  FROM
    EO_WORKSSUPPORTGROUP
  WHERE
    EO_WORKSSUPPORTGROUP.WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID
  --  AND EO_WORKSSUPPORTGROUP.ISACTIVE = 1
    AND EO_WORKSSUPPORTGROUP.ISDELETED = 0
  ;
END;
/