CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTMEMBERROLE_V2_ADD
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	16/12/2015
	DESCRIPTION	:	THÊM THÔNG TIN VAI TRO XU LY
*/
(
  V_OUT OUT NUMBER,
	--V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORTMEMBERROLE.WORKSSUPPORTMEMBERROLEID%TYPE,
	V_WORKSSUPPORTMEMBERROLENAME IN EO_WORKSSUPPORTMEMBERROLE.WORKSSUPPORTMEMBERROLENAME%TYPE,
  V_DESCRIPTION IN EO_WORKSSUPPORTMEMBERROLE.DESCRIPTION%TYPE,
  V_ICONURL IN EO_WORKSSUPPORTMEMBERROLE.ICONURL%TYPE,
	V_ORDERINDEX IN EO_WORKSSUPPORTMEMBERROLE.ORDERINDEX%TYPE,
	V_ISACTIVE IN EO_WORKSSUPPORTMEMBERROLE.ISACTIVE%TYPE,
	V_ISSYSTEM IN EO_WORKSSUPPORTMEMBERROLE.ISSYSTEM%TYPE,
	V_CREATEDUSER IN EO_WORKSSUPPORTMEMBERROLE.CREATEDUSER%TYPE,
  V_CERTIFICATESTRING IN EO_WORKSSUPPORTMEMBERROLE_LOG.CERTIFICATESTRING%TYPE,
	V_USERHOSTADDRESS IN EO_WORKSSUPPORTMEMBERROLE_LOG.USERHOSTADDRESS%TYPE,
	V_LOGINLOGID IN EO_WORKSSUPPORTMEMBERROLE_LOG.LOGINLOGID%TYPE
)
AS
T_ORDERINDEX EO_WORKSSUPPORTMEMBERROLE.ORDERINDEX%TYPE;
BEGIN
--   IF V_ISOTHER = 1 THEN  
--    UPDATE EO_EDOCUMENTPROCESSRESULT SET ISOTHER = 0 ;
--   END IF;
  SELECT COUNT(*)  + 1 INTO T_ORDERINDEX 
  FROM 
    EO_WORKSSUPPORTMEMBERROLE
  WHERE ISDELETED = 0;

	INSERT
	INTO EO_WORKSSUPPORTMEMBERROLE
	(
		--WORKSSUPPORTPRIORITYID,
		WORKSSUPPORTMEMBERROLENAME,
		DESCRIPTION,
    ICONURL,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		CREATEDUSER,
		CREATEDDATE
	)
	VALUES
	(
		--V_WORKSSUPPORTPRIORITYID,
		V_WORKSSUPPORTMEMBERROLENAME,
		V_DESCRIPTION,
  V_ICONURL,
		T_ORDERINDEX,
		V_ISACTIVE,
		V_ISSYSTEM,
		V_CREATEDUSER,
		SYSDATE
    --V_ISDELETED,
    --V_DELETEDUSER,
    --V_DELETEDDATE
	)RETURNING WORKSSUPPORTMEMBERROLEID INTO V_OUT;
	INSERT
	INTO EO_WORKSSUPPORTMEMBERROLE_LOG
	(
	  WORKSSUPPORTMEMBERROLENAME,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
    UPDATEDUSER,
		UPDATEDDATE,
	  LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID
	)
	VALUES
	(
		V_WORKSSUPPORTMEMBERROLENAME,
		V_DESCRIPTION,
		T_ORDERINDEX,
		V_ISACTIVE,
		V_ISSYSTEM,
   	V_CREATEDUSER,
		SYSDATE,
	  1,
		V_USERHOSTADDRESS,
		V_CERTIFICATESTRING,
		V_LOGINLOGID
	);

END;
/