CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTUSER_V2_SRH
/*
	CREATED BY	:	NGUYỄN VĂN PHẬN
	DATE		:	29/06/2017

*/
(
    V_OUT OUT SYS_REFCURSOR,
    V_DEPARTMENTID NUMBER DEFAULT -1,
    V_KEYWORDS NVARCHAR2 DEFAULT NULL

) 
AS
BEGIN
  IF(V_DEPARTMENTID > 0) THEN
  begin
        OPEN V_OUT FOR
      	SELECT
          SU.USERNAME,
      		SU.FULLNAME,
          SU.DEFAULTPICTUREURL,
          SD.DEPARTMENTID,
          SD.DEPARTMENTNAME

        
      	FROM 
          SYS_USER SU
        LEFT JOIN SYS_DEPARTMENT SD ON SU.DEPARTMENTID = SD.DEPARTMENTID  
      	WHERE 
          SU.ISDELETED = 0 AND SD.ISDELETED = 0 AND SU.DEPARTMENTID = V_DEPARTMENTID
          AND (UPPER(SU.FULLNAME) LIKE '%'|| UPPER (V_KEYWORDS) || '%');
        END;
   ELSE 
    BEGIN
       OPEN V_OUT FOR
	       SELECT
          SU.USERNAME,
      		SU.FULLNAME,
          SU.DEFAULTPICTUREURL,
          SD.DEPARTMENTID,
          SD.DEPARTMENTNAME
          
      	 FROM 
          SYS_USER SU
          LEFT JOIN SYS_DEPARTMENT SD ON SU.DEPARTMENTID = SD.DEPARTMENTID
         	WHERE 
           SU.ISDELETED = 0 AND SD.ISDELETED = 0 AND (UPPER(SU.FULLNAME) LIKE '%'|| UPPER (V_KEYWORDS )|| '%');         
    END;
  END IF;
END;
/