CREATE OR REPLACE PROCEDURE ERP.EO_WORKSSUPPORTTYPE_P_DEL
/*
	CREATED BY	:	LUONG TRUNG NHÂN 
	DATE		:	02/06/2017
	DESCRIPTION	:	XÓA THÔNG TIN B?NG LIÊN K?T LO?I CÔNG VI?C VÀ Ð? UU TIÊN
*/
(
	V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE_PRIORITY.WORKSSUPPORTTYPEID%TYPE
)
AS
BEGIN
	DELETE EO_WORKSSUPPORTTYPE_PRIORITY
	WHERE
		WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID;
END;
/