CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTSTATUS_V2_UPD
/*
	Created by	:	Hoàng Nhu Phong 
	Date		:	02/03/2013
	Description	:	C?p nh?t thông tin Tr?ng thái công vi?c c?n h? tr? 
*/
(
  V_out OUT SYS_REFCURSOR,

	v_WORKSSUPPORTSTATUSID IN EO_WORKSSUPPORTSTATUS.WORKSSUPPORTSTATUSID%TYPE,

    v_WORKSSUPPORTSTATUSNAME IN EO_WORKSSUPPORTSTATUS.WORKSSUPPORTSTATUSNAME%TYPE,
    
	v_ICONURL IN EO_WORKSSUPPORTSTATUS.ICONURL%TYPE,
	v_ISINITSTATUS IN EO_WORKSSUPPORTSTATUS.ISINITSTATUS%TYPE,
	v_ISCOMPLETESTATUS IN EO_WORKSSUPPORTSTATUS.ISCOMPLETESTATUS%TYPE,
	v_DESCRIPTION IN EO_WORKSSUPPORTSTATUS.DESCRIPTION%TYPE,
	v_ORDERINDEX IN EO_WORKSSUPPORTSTATUS.ORDERINDEX%TYPE,
	v_ISACTIVE IN EO_WORKSSUPPORTSTATUS.ISACTIVE%TYPE,
	v_ISSYSTEM IN EO_WORKSSUPPORTSTATUS.ISSYSTEM%TYPE,
	v_UPDATEDUSER IN EO_WORKSSUPPORTSTATUS.UPDATEDUSER%TYPE,
  v_ISCLOSESTATUS IN EO_WORKSSUPPORTSTATUS.ISCLOSESTATUS%TYPE,
	v_CERTIFICATESTRING IN EO_WORKSSUPPORTSTATUS_LOG.CERTIFICATESTRING%TYPE,
	v_USERHOSTADDRESS IN EO_WORKSSUPPORTSTATUS_LOG.USERHOSTADDRESS%TYPE,
	v_LOGINLOGID IN EO_WORKSSUPPORTSTATUS_LOG.LOGINLOGID%TYPE
    
) 
AS
  V_ORDERINDEXOLD NUMBER;
BEGIN

 --1. LAY ODERINDEX CU DUOC CAP NHAT THANH MOI
  SELECT ew.orderindex INTO v_orderindexold FROM EO_WORKSSUPPORTSTATUS ew
  WHERE workssupportstatusid = v_WORKSSUPPORTSTATUSID AND isdeleted =0 ;

   --2. c?p nh?t orderindex cho b?ng du?c hoán v? tru?ng orderindex.
  UPDATE EO_WORKSSUPPORTSTATUS
  	  SET
  		orderindex = v_orderindexold,
  		UPDATEDDATE	= sysdate
  WHERE orderindex = v_orderindex AND isdeleted = 0;

 IF v_ISINITSTATUS = 1 then 
    UPDATE eo_workssupportstatus eo SET ISINITSTATUS = 0
    WHERE ISINITSTATUS = 1 AND eo.workssupportstatusid = v_WORKSSUPPORTSTATUSID ;
  END IF;
  IF v_ISCOMPLETESTATUS = 1 then 
    UPDATE eo_workssupportstatus eo SET ISCOMPLETESTATUS = 0
    WHERE ISCOMPLETESTATUS = 1 and eo.workssupportstatusid = v_WORKSSUPPORTSTATUSID;
  END IF;



  IF V_ICONURL = '' OR V_ICONURL IS NULL  THEN
  	UPDATE EO_WORKSSUPPORTSTATUS
  	SET
  		WORKSSUPPORTSTATUSNAME	= v_WORKSSUPPORTSTATUSNAME,
  		--ICONURL	= v_ICONURL,
  		ISINITSTATUS	= v_ISINITSTATUS,
  		ISCOMPLETESTATUS	= v_ISCOMPLETESTATUS,
  		DESCRIPTION	= v_DESCRIPTION,
  		ISCLOSESTATUS	= v_ISCLOSESTATUS,
  		ISACTIVE	= v_ISACTIVE,
  		ISSYSTEM	= v_ISSYSTEM,
  		UPDATEDUSER	= v_UPDATEDUSER,
  		UPDATEDDATE	= sysdate,
      orderindex = v_orderindex
  	WHERE
  		WORKSSUPPORTSTATUSID = v_WORKSSUPPORTSTATUSID;
   ELSE
      UPDATE EO_WORKSSUPPORTSTATUS
  	SET
  		WORKSSUPPORTSTATUSNAME	= v_WORKSSUPPORTSTATUSNAME,
      orderindex = v_orderindex,
  		ICONURL	= v_ICONURL,
  		ISINITSTATUS	= v_ISINITSTATUS,
  		ISCOMPLETESTATUS	= v_ISCOMPLETESTATUS,
  		DESCRIPTION	= v_DESCRIPTION,
  		ISCLOSESTATUS	= v_ISCLOSESTATUS,
  		ISACTIVE	= v_ISACTIVE,
  		ISSYSTEM	= v_ISSYSTEM,
  		UPDATEDUSER	= v_UPDATEDUSER,
  		UPDATEDDATE	= SYSDATE
  	WHERE
  		WORKSSUPPORTSTATUSID = v_WORKSSUPPORTSTATUSID;
    END IF;
	INSERT
	INTO EO_WORKSSUPPORTSTATUS_LOG
	(
		WORKSSUPPORTSTATUSID,
		WORKSSUPPORTSTATUSNAME,
		ICONURL,
		ISINITSTATUS,
		ISCOMPLETESTATUS,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		UPDATEDUSER,
		UPDATEDDATE,
    ISCLOSESTATUS,
		LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID

	)
	VALUES
	(
		v_WORKSSUPPORTSTATUSID,
		v_WORKSSUPPORTSTATUSNAME,
		v_ICONURL,
		v_ISINITSTATUS,
		v_ISCOMPLETESTATUS,
		v_DESCRIPTION,
		v_ORDERINDEX,
		v_ISACTIVE,
		v_ISSYSTEM,
		v_UPDATEDUSER,
		SYSDATE,
    v_ISCLOSESTATUS,
		2,
		v_USERHOSTADDRESS,
		v_CERTIFICATESTRING,
		v_LOGINLOGID

	);
	 OPEN V_OUT FOR 
    SELECT * 
      FROM EO_WORKSSUPPORTSTATUS WHERE  workssupportstatusid = V_WORKSSUPPORTSTATUSID;
    RETURN;
END;
/