create or replace PROCEDURE WSPROJECT_MEMBER_V2_DEL
/*
	CREATED BY	:	NGUY?N TH? KIM NGÂN
	DATE		:	22.07.2017
	DESCRIPTION	:	XÓA THÔNG TIN THÀNH VIÊN D? ÁN 
*/
(
  V_WORKSSUPPORTPROJECTID IN EO_WORKSSUPPORTPROJECT_MEMBER.WORKSSUPPORTPROJECTID%TYPE,
	V_MEMBERUSERNAME IN EO_WORKSSUPPORTPROJECT_MEMBER.MEMBERUSERNAME%TYPE
)
AS
BEGIN
  --. XOA DU LIEU
  DELETE FROM 
    EO_WORKSSUPPORTPROJECT_MEMBER
  WHERE 
    WORKSSUPPORTPROJECTID = V_WORKSSUPPORTPROJECTID 
  AND 
    MEMBERUSERNAME = V_MEMBERUSERNAME;
END;
