CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORT_PRO_V2_DEL_BETA
/*
	CREATED BY	:	NGHIEM HUU QUANG 
	DATE		:	10/22/2013
	DESCRIPTION	:	XÓA THÔNG TIN TI?N D? CÔNG VI?C C?N H? TR? 
*/
(
	V_WORKSSUPPORTID IN EO_WORKSSUPPORT_PROGRESS.WORKSSUPPORTID%TYPE
)
AS
BEGIN
	DELETE FROM EO_WORKSSUPPORT_PROGRESS
	WHERE WORKSSUPPORTID = V_WORKSSUPPORTID;
END;
/