create or replace PROCEDURE EO_WORKSSUPPORTTYPE_WF_P_ADD
/*
	Created by	:	Trýõng Hoang Nhi
	Date		:	13/07/2017
	Description	:	Thêm thông tin Lo?i công vi?c c?n h? tr? 
*/
(
	V_WORKSSUPPORTSTEPID IN EO_WORKSSUPPORTTYPE_WF_PERMIS.WORKSSUPPORTSTEPID%TYPE,
	V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORTTYPE_WF_PERMIS.WORKSSUPPORTMEMBERROLEID%TYPE,
    V_ISCANEDITCONTENT IN EO_WORKSSUPPORTTYPE_WF_PERMIS.ISCANEDITCONTENT%TYPE,    
    V_ISCANEDITSOLUTIONCONTENT IN EO_WORKSSUPPORTTYPE_WF_PERMIS.ISCANEDITSOLUTIONCONTENT%TYPE,    
    V_ISCANADDATTACHMENT IN EO_WORKSSUPPORTTYPE_WF_PERMIS.ISCANADDATTACHMENT%TYPE,    
    V_ISCANCOMMENT IN EO_WORKSSUPPORTTYPE_WF_PERMIS.ISCANCOMMENT%TYPE,    
    -- V_ISCOMPLETEDDATE param of ISCANEDITEXPECTEDCOMPLETEDDATE
    V_ISCOMPLETEDDATE IN EO_WORKSSUPPORTTYPE_WF_PERMIS.ISCANEDITEXPECTEDCOMPLETEDDATE%TYPE,
    -- V_ISCOMPLETEDDATE param of ISCANEDITEXPECTEDCOMPLETEDDATE
    V_ISCANEDITQUALITY IN EO_WORKSSUPPORTTYPE_WF_PERMIS.ISCANEDITQUALITY%TYPE,    
    V_ISCANPROCESSWORKFLOW IN EO_WORKSSUPPORTTYPE_WF_PERMIS.ISCANPROCESSWORKFLOW%TYPE,
    V_ISCANCHANGEPROGRESS IN EO_WORKSSUPPORTTYPE_WF_PERMIS.ISCANCHANGEPROGRESS%TYPE,
    V_ISMUSTCHOOSEPROCESSUSER IN EO_WORKSSUPPORTTYPE_WF_PERMIS.ISMUSTCHOOSEPROCESSUSER%TYPE,
    V_CREATEDUSER IN EO_WORKSSUPPORTTYPE_WF_PERMIS.CREATEDUSER%TYPE
)
AS
--t_count number;
BEGIN
	INSERT
	INTO EO_WORKSSUPPORTTYPE_WF_PERMIS
	(
        WORKSSUPPORTSTEPID,
        WORKSSUPPORTMEMBERROLEID,    
        ISCANEDITCONTENT,
        ISCANEDITSOLUTIONCONTENT,
        ISCANADDATTACHMENT,
        ISCANCOMMENT,
        ISCANEDITEXPECTEDCOMPLETEDDATE,
        ISCANEDITQUALITY,
        ISCANPROCESSWORKFLOW,
        ISCANCHANGEPROGRESS,
        ISMUSTCHOOSEPROCESSUSER,
        CREATEDUSER,
        CREATEDDATE
	)
	VALUES
	(
        V_WORKSSUPPORTSTEPID,
        V_WORKSSUPPORTMEMBERROLEID,    
        V_ISCANEDITCONTENT,
        V_ISCANEDITSOLUTIONCONTENT,
        V_ISCANADDATTACHMENT,
        V_ISCANCOMMENT,
        V_ISCOMPLETEDDATE,
        V_ISCANEDITQUALITY,
        V_ISCANPROCESSWORKFLOW,
        V_ISCANCHANGEPROGRESS,
        V_ISMUSTCHOOSEPROCESSUSER,
        V_CREATEDUSER,
        SYSDATE
	);
END;