create or replace PROCEDURE     EO_WORKSSUPPORTPROJECT_P_DEL
/*
	Created by	:	Lýõng Trung Nhân
	Date		:	12/06/2017
	Description	:	Xóa thông tin quy?n trên d? án công vi?c c?n h? tr?
*/
(
	V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTPROJECT_PERMIS.WORKSSUPPORTTYPEID%TYPE
)
AS
BEGIN
	DELETE 
        EO_WORKSSUPPORTPROJECT_PERMIS
	WHERE
		WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID;
END;