CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTMEMBERROLE_V2_BY
/*	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	30.05.2017
	DESCRIPTION	:	NẠP THÔNG TIN VAI TRO CÔNG VIỆC CẦN HỖ TRỢ 
*/
(	
	V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORTMEMBERROLE.WORKSSUPPORTMEMBERROLEID%TYPE,	
	V_OUT OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN V_OUT FOR
	SELECT
	WORKSSUPPORTMEMBERROLEID,
  WORKSSUPPORTMEMBERROLENAME,
  DESCRIPTION,
  ICONURL,
  ORDERINDEX,
  ISACTIVE,
  ISSYSTEM,
  CREATEDUSER,
  CREATEDDATE,
  UPDATEDUSER,
  UPDATEDDATE
	FROM 
    EO_WORKSSUPPORTMEMBERROLE
	WHERE
		WORKSSUPPORTMEMBERROLEID = V_WORKSSUPPORTMEMBERROLEID
;
END;
/