CREATE OR REPLACE PROCEDURE ERP.WS_GROUP_MEMBER_V2_ADD
/*
	CREATED BY	:	NGUYEN VAN HUAN
	DATE		:	21.07.2017
	DESCRIPTION	:	THÊM THANH VIEN NHOM CONG VIEC CHO CONG VIEC CAN HO TRO
*/
(
  V_WORKSSUPPORTGROUPID IN EO_WORKSSUPPORTGROUP_MEMBER.WORKSSUPPORTGROUPID%TYPE,
	V_MEMBERUSERNAME IN EO_WORKSSUPPORTGROUP_MEMBER.MEMBERUSERNAME%TYPE,
  V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORTGROUP_MEMBER.WORKSSUPPORTMEMBERROLEID%TYPE,
  V_ISAUTOADDGROUPMEMBER IN EO_WORKSSUPPORTGROUP_MEMBER.ISAUTOADDMEMBERTOWORKSSUPPORT%TYPE,
  V_CREATEDUSER IN EO_WORKSSUPPORTGROUP_MEMBER.CREATEDUSER%TYPE
)
AS
  T_ORDERINDEX NUMBER := 0 ;
BEGIN 
  SELECT NVL(max(ORDERINDEX),0)+1 INTO T_ORDERINDEX 
    FROM 
         EO_WORKSSUPPORTGROUP_MEMBER
    WHERE ISDELETED = 0;
	INSERT
	INTO EO_WORKSSUPPORTGROUP_MEMBER
	(
		WORKSSUPPORTGROUPID,
		MEMBERUSERNAME,
		WORKSSUPPORTMEMBERROLEID,
    ORDERINDEX,
    ISAUTOADDMEMBERTOWORKSSUPPORT,
    CREATEDUSER,
		CREATEDDATE
	)
	VALUES
	(
		V_WORKSSUPPORTGROUPID,
		V_MEMBERUSERNAME,
		V_WORKSSUPPORTMEMBERROLEID,
    T_ORDERINDEX,
    V_ISAUTOADDGROUPMEMBER,
    V_CREATEDUSER,
		SYSDATE
	);
END;
/