CREATE OR REPLACE PROCEDURE ERP.EO_WORKSSUPPORTTYPE_Q_DEL
/*
	CREATED BY	:	LUONG TRUNG NHÂN 
	DATE		:	02/06/2017
	DESCRIPTION	:	XÓA THÔNG TIN B?NG LIÊN K?T LO?I CÔNG VI?C VÀ CH?T LU?NG CÔNG VI?C
*/
(
	V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE_QUALITY.WORKSSUPPORTTYPEID%TYPE
)
AS
BEGIN
	DELETE EO_WORKSSUPPORTTYPE_QUALITY
	WHERE
		WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID;
END;
/