CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTTYPEPERIOD_V2_GETS
  /*
	Created by	:	NGUYEN THI KIM NGAN
	Date		:	30.05.2017
	Description	:	N?p danh sách loai cong viec
*/
(
  V_OUT OUT SYS_REFCURSOR
)
AS
BEGIN
  OPEN V_OUT FOR
  SELECT
    EO_WORKSSUPPORTTYPEPERIOD.PERIODID,
    EO_WORKSSUPPORTTYPEPERIOD.PERIODNAME
    
  FROM
    EO_WORKSSUPPORTTYPEPERIOD
  ORDER BY
    EO_WORKSSUPPORTTYPEPERIOD.PERIODID
  ;
END;
/