CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTQUALITY_V2_DEL
/*
	CREATED BY	:	LUONG TRUNG NHÂN 
	DATE		:	30/05/2017
	DESCRIPTION	:	XÓA THÔNG TIN TR?NG THÁI CÔNG VI?C C?N H? TR? 
*/
(
	V_WORKSSUPPORTQUALITYID IN EO_WORKSSUPPORTQUALITY.WORKSSUPPORTQUALITYID%TYPE
,
	V_DELETEDUSER IN EO_WORKSSUPPORTQUALITY.DELETEDUSER%TYPE,
  V_CERTIFICATESTRING IN EO_WORKSSUPPORTQUALITY_LOG.CERTIFICATESTRING%TYPE,
	V_USERHOSTADDRESS IN EO_WORKSSUPPORTQUALITY_LOG.USERHOSTADDRESS%TYPE,
	V_LOGINLOGID IN EO_WORKSSUPPORTQUALITY_LOG.LOGINLOGID%TYPE
)
AS
   V_ORDERINDEXDEL NUMBER;
BEGIN
  --1. LAY ODERINDEX CU DUOC DOI CAP NHAT THANH MOI
  SELECT ew.orderindex INTO V_ORDERINDEXDEL FROM EO_WORKSSUPPORTQUALITY ew
  WHERE workssupportqualityid = V_WORKSSUPPORTQUALITYID AND isdeleted =0;

  --2. XOA DU LIEU
	UPDATE EO_WORKSSUPPORTQUALITY
	SET
		ISDELETED = 1,
		DELETEDDATE = SYSDATE,
		DELETEDUSER = V_DELETEDUSER
	WHERE
		workssupportqualityid = v_workssupportqualityid ;

 --3. CAP NHAT LAI TAT CA CAC GIA TR? ORDERINDEX CÓ GIÁ TR? L?N HON ORDERINDEX B? XÓA
	UPDATE EO_WORKSSUPPORTQUALITY
	SET
		orderindex = orderindex-1
	WHERE
		orderindex > v_orderindexdel AND isdeleted = 0 ;

 --4. chen vao bang log
    INSERT
	INTO EO_WORKSSUPPORTQUALITY_LOG
	(
		WORKSSUPPORTQUALITYID,
		WORKSSUPPORTQUALITYNAME,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		UPDATEDUSER,
		UPDATEDDATE,
		LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID

	)
  SELECT
		WORKSSUPPORTQUALITYID,
		WORKSSUPPORTQUALITYNAME,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		V_DELETEDUSER,
		UPDATEDDATE,
    3,
		V_USERHOSTADDRESS,
		V_CERTIFICATESTRING,
		V_LOGINLOGID
    FROM 
      EO_WORKSSUPPORTQUALITY
    WHERE 
      WORKSSUPPORTQUALITYID = V_WORKSSUPPORTQUALITYID;
END;
/