CREATE OR REPLACE PROCEDURE ERP.WORKSUPORTGROUP_V2_DEL
/*
	CREATED BY	:	NGUY?N VAN HUAN
	DATE		:	09/06/2017
	DESCRIPTION	:	XÓA THÔNG TIN NHOM CONG VIEC
*/
(
	V_WORKSSUPPORTGROUPID IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTGROUPID%TYPE,
	V_DELETEDUSER IN EO_WORKSSUPPORTGROUP.DELETEDUSER%TYPE,
  V_CERTIFICATESTRING IN EO_WORKSSUPPORTGROUP_LOG.CERTIFICATESTRING%TYPE,
	V_USERHOSTADDRESS IN EO_WORKSSUPPORTGROUP_LOG.USERHOSTADDRESS%TYPE,
	V_LOGINLOGID IN EO_WORKSSUPPORTGROUP_LOG.LOGINLOGID%TYPE
)
AS
  T_GROUPID NUMBER:= 0;
BEGIN
  -- XÓA NHOM CÔNG VI?C C?N H? TR?
	UPDATE EO_WORKSSUPPORTGROUP
	SET
		ISDELETED = 1,
		DELETEDDATE = SYSDATE,
		DELETEDUSER = V_DELETEDUSER
	WHERE
		WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID;

  -- XÓA CÔNG VI?C C?N HO TRO TUONG UNG V?I D? ÁN

  UPDATE EO_WORKSSUPPORT  
    SET ISDELETED = 1,
        DELETEDUSER =V_DELETEDUSER,
        DELETEDDATE = SYSDATE 
    WHERE WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID;
    
END;
/