create or replace PROCEDURE EO_WORKSSUPPORT_COMMENT_V2_ADD
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:11.07.2017
	DESCRIPTION	:	THEM CONG VIEC LIEN QUAN VAO CONG VIEC CAN HO TRO 
*/ (
    V_WORKSSUPPORTID   IN EO_WORKSSUPPORT_COMMENT.WORKSSUPPORTID%TYPE,
    V_COMMENTCONTENT   IN EO_WORKSSUPPORT_COMMENT.COMMENTCONTENT%TYPE,
    V_COMMENTUSER      IN EO_WORKSSUPPORT_COMMENT.COMMENTUSER%TYPE,
    V_OUT              OUT NUMBER
) AS
    T_ORDERINDEX   EO_WORKSSUPPORT_COMMENT.ORDERINDEX%TYPE;
BEGIN
    SELECT
        COUNT(*) + 1
    INTO
        T_ORDERINDEX
    FROM
        EO_WORKSSUPPORTPRIORITY
    WHERE
        ISDELETED = 0;

    INSERT INTO EO_WORKSSUPPORT_COMMENT (
        WORKSSUPPORTID,
        COMMENTDATE,
        COMMENTCONTENT,
        COMMENTUSER,
        ORDERINDEX,
        CREATEDUSER,
        CREATEDDATE
    ) VALUES (
        V_WORKSSUPPORTID,
        SYSDATE,
        V_COMMENTCONTENT,
        V_COMMENTUSER,
        T_ORDERINDEX,
        V_COMMENTUSER,
        SYSDATE
    )RETURNING COMMENTID INTO V_OUT;
END;