create or replace PROCEDURE     EO_WORKSSUPPORTTYPE_WF_IDNAME
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	02/03/2013
	DESCRIPTION	:	N?P THÔNG TIN BUOC XU LY CÔNG VI?C C?N H? TR? 
*/
(	
	V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE_WORKFLOW.WORKSSUPPORTTYPEID%TYPE,	
    V_WORKSSUPPORTSTEPNAME IN EO_WORKSSUPPORTTYPE_WORKFLOW.WORKSSUPPORTSTEPNAME%TYPE,	
	V_OUT OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN V_OUT FOR
	SELECT 
  WORKSSUPPORTSTEPID,
  WORKSSUPPORTTYPEID,
  WORKSSUPPORTSTEPNAME,
  UPDATEDUSER,
  UPDATEDDATE,
  PROCESSFUNCTIONID,
  STEPCOLORCODE,
  MAXPROCESSTIME,
  ISINITSTEP,
  ISFINISHSTEP,
  ISMUSTCHOOSEPROCESSUSER,
  AUTOCHANGETOSTATUSID,
  DESCRIPTION,
  ORDERINDEX, 
  ISACTIVE,
  ISSYSTEM,
  CREATEDUSER,
  CREATEDDATE,
  ISDELETED,
  DELETEDUSER,
  DELETEDDATE,
  ISCANMODIFIEDCONTENT,
  ISCANMODIFIEDCONTENTSOLUTION,
  ISCANMODIFIEDCOMPLETEDDATE,
  ISCANATTACH,
  ISCANCOMMENT,
  ISCANUPDATEPROCESS,
  ISCANUPDATEQUALITY
		
	FROM 
    EO_WORKSSUPPORTTYPE_WORKFLOW
	WHERE
    WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID
     AND (
        V_WORKSSUPPORTSTEPNAME IS NULL
        OR (CAST(TRIM(V_WORKSSUPPORTSTEPNAME) AS NVARCHAR2(2000)) = CAST(TRIM(WORKSSUPPORTSTEPNAME) AS NVARCHAR2(2000)))
        OR (UPPER(WORKSSUPPORTSTEPNAME) LIKE '%'|| UPPER(TRIM(V_WORKSSUPPORTSTEPNAME)) || '%')                 
      )
;
END;
