CREATE OR REPLACE PROCEDURE ERP.EO_WORKSSUPPORTSTATUS_SEL
/*
	Created by	:	Hoàng Nhu Phong 
	Date		:	02/03/2013
	Description	:	N?p thông tin Tr?ng thái công vi?c c?n h? tr? 
*/
(	
	v_WORKSSUPPORTSTATUSID IN EO_WORKSSUPPORTSTATUS.WORKSSUPPORTSTATUSID%type,	
	v_Out OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN v_Out FOR
	SELECT
		WORKSSUPPORTSTATUSID,
		WORKSSUPPORTSTATUSNAME,
		ICONURL,
		ISINITSTATUS,
		ISCOMPLETESTATUS,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		CREATEDUSER,
		CREATEDDATE,
		UPDATEDUSER,
		UPDATEDDATE,
		ISDELETED,
		DELETEDUSER,
		DELETEDDATE,
    ISCLOSESTATUS
	FROM 
    EO_WORKSSUPPORTSTATUS
	WHERE
    ISDELETED =0 and
		WORKSSUPPORTSTATUSID = v_WORKSSUPPORTSTATUSID
;
END;
/