CREATE OR REPLACE PROCEDURE ERP.EO_WORKS_V2_SHR
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	06.07.2017
	DESCRIPTION	:	THEM CONG VIEC LIEN QUAN CHO CONG VIEC CAN HO TRO 
*/
(
  V_OUT OUT SYS_REFCURSOR,
	V_PROJECTID IN EO_WORKS.PROJECTID%TYPE DEFAULT NULL,
	V_KEYWORDS  IN EO_WORKS.WORKSNAME%TYPE DEFAULT NULL,
  V_TYPESEARCH IN NUMBER DEFAULT -1,
	V_STARTDATE IN EO_WORKS.STARTDATE%TYPE DEFAULT NULL,
	V_ENDDATE IN EO_WORKS.ENDDATE%TYPE DEFAULT NULL,
  V_PAGEINDEX NUMBER DEFAULT -1,
  V_PAGESIZE NUMBER DEFAULT -1
)
AS
BEGIN
    OPEN V_OUT FOR
   SELECT 
    WS.WORKSID,
		WS.WORKSNAME,
		WS.PROJECTID,
		WS.STARTDATE,
		WS.ENDDATE,
		WS.ISDELETED,
		WS.CREATEDDATE,
		WS.CURRENTPROGRESS,
		WS.DELETEDDATE,
    WS.EXECUSER
   FROM(
	SELECT
		WORKS.WORKSID,
		WORKS.WORKSNAME,
		WORKS.PROJECTID,
		WORKS.STARTDATE,
		WORKS.ENDDATE,
		WORKS.ISDELETED,
		WORKS.CREATEDDATE,
		WORKS.CURRENTPROGRESS,
		WORKS.DELETEDDATE,
    EXECUSER.EXECUSER,
    ROW_NUMBER() OVER (ORDER BY WORKS.CREATEDDATE DESC) STT,
    SUM(1) OVER()AS TOTALROWS
	FROM 
    EO_WORKS WORKS
    LEFT  JOIN SYS_USER CREATEDUSER 
      ON CREATEDUSER.USERNAME = WORKS.CREATEDUSER
    LEFT JOIN EO_WORKS_EXECUSER EXECUSER
      ON EXECUSER.WORKSID = WORKS.WORKSID AND EXECUSER.ISDELETED = 0
    LEFT JOIN Eo_Project Project
       ON UPPER Project.PROJECTID LIKE '%' || UPPER WORKS.PROJECTID || '%'
	WHERE 
    WORKS.ISDELETED = 0
    AND (V_KEYWORDS IS NULL 
         OR EXECUSER.EXECUSER IS NULL OR(UPPER (EXECUSER.EXECUSER) LIKE '%' || UPPER ( V_KEYWORDS )|| '%' AND V_TYPESEARCH = 2)
         OR WORKS.WORKSNAME IS NULL OR( UPPER ( WORKS.WORKSNAME ) LIKE '%' ||UPPER ( V_KEYWORDS )|| '%' AND V_TYPESEARCH = 1))
--   AND (IF(V_TYPESEARCH = 1) THEN                    
--              UPPER ( WORKS.WORKSNAME ) LIKE '%' ||UPPER ( V_KEYWORDS )|| '%'
--          ELSIF(V_TYPESEARCH = 2) THEN
--              UPPER (EXECUSER.EXECUSER) LIKE '%' || UPPER ( V_KEYWORDS )|| '%' 
--          END IF
--         )
    AND (UPPER (WORKS.PROJECTID) LIKE '%' || UPPER (V_PROJECTID) || '%' )
    AND (V_STARTDATE IS NULL OR V_STARTDATE IS NOT NULL AND TRUNC(WORKS.STARTDATE) >= TRUNC(V_STARTDATE))
    AND (V_ENDDATE IS NULL OR V_ENDDATE IS NOT NULL AND TRUNC(WORKS.ENDDATE) <= TRUNC(V_ENDDATE))
  )WS
  WHERE
  V_PAGESIZE < 0 
  OR
  (STT > V_PAGEINDEX * V_PAGESIZE AND STT <= (V_PAGEINDEX + 1) * V_PAGESIZE);
END;
/