create or replace PROCEDURE EO_WORKSSUPPORTTYPE_WF_NX_ADD
/*
	CREATED BY	:	LÝÕNG TRUNG NHÂN 
	DATE		:	02/06/2017
	DESCRIPTION	:	THÊM THÔNG TIN B?NG CH?A CÁC BÝ?C X? L? K? TI?P
*/
(
	V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE_WF_NX.WORKSSUPPORTTYPEID%TYPE,
	V_WORKSSUPPORTSTEPID IN EO_WORKSSUPPORTTYPE_WF_NX.WORKSSUPPORTSTEPID%TYPE,
  V_NEXTWORKSSUPPORTSTEPID IN EO_WORKSSUPPORTTYPE_WF_NX.NEXTWORKSSUPPORTSTEPID%TYPE,
)
AS
T_COUNT NUMBER;
BEGIN
	INSERT
	INTO EO_WORKSSUPPORTTYPE_WF_NX
	(
		WORKSSUPPORTTYPEID,
		WORKSSUPPORTSTEPID,
        NEXTWORKSSUPPORTSTEPID
	)
	VALUES
	(
		V_WORKSSUPPORTTYPEID,
		V_WORKSSUPPORTSTEPID,
        V_NEXTWORKSSUPPORTSTEPID    
	);
END;