CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTGROUP_V2_ADD
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	08/06/2017
	DESCRIPTION	:	N?P DANH SÁCH NHÓM CÔNG VI?C C?N H? TR? 
*/
(
  V_WORKSSUPPORTGROUPNAME IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTGROUPNAME%TYPE,
  V_WORKSSUPPORTPROJECTID IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTPROJECTID%TYPE,
	V_DESCRIPTION IN EO_WORKSSUPPORTGROUP.DESCRIPTION%TYPE,
	V_ISACTIVE IN EO_WORKSSUPPORTGROUP.ISACTIVE%TYPE,
	V_ISSYSTEM IN EO_WORKSSUPPORTGROUP.ISSYSTEM%TYPE,
	V_CREATEDUSER IN EO_WORKSSUPPORTGROUP.CREATEDUSER%TYPE,
  V_CERTIFICATESTRING IN EO_WORKSSUPPORTGROUP_LOG.CERTIFICATESTRING%TYPE,
	V_USERHOSTADDRESS IN EO_WORKSSUPPORTGROUP_LOG.USERHOSTADDRESS%TYPE,
	V_LOGINLOGID IN EO_WORKSSUPPORTGROUP_LOG.LOGINLOGID%TYPE
)
AS
T_ORDERINDEX EO_WORKSSUPPORTGROUP.ORDERINDEX%TYPE;
   V_OUT NUMBER:=0;
BEGIN

  SELECT COUNT(*) + 1 INTO T_ORDERINDEX 
  FROM 
    EO_WORKSSUPPORTGROUP
  WHERE ISDELETED = 0;

	INSERT
	INTO EO_WORKSSUPPORTGROUP
	(
		WORKSSUPPORTGROUPNAME,
		WORKSSUPPORTPROJECTID,
		DESCRIPTION,
    ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		CREATEDUSER,
		CREATEDDATE
	)
	VALUES
	(
		--V_WORKSSUPPORTPRIORITYID,
		V_WORKSSUPPORTGROUPNAME,
		V_WORKSSUPPORTPROJECTID,
		V_DESCRIPTION,
		T_ORDERINDEX,
		V_ISACTIVE,
		V_ISSYSTEM,
		V_CREATEDUSER,
		SYSDATE

	)RETURNING WORKSSUPPORTGROUPID into V_OUT;

	INSERT
	INTO EO_WORKSSUPPORTGROUP_LOG
	(
		--V_OUT,
    workssupporttypeid,
		WORKSSUPPORTGROUPNAME,
		WORKSSUPPORTPROJECTID,
		DESCRIPTION,
    ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		UPDATEDUSER,
		UPDATEDDATE,
	  LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID
	)
	VALUES
	(
    V_OUT,
		V_WORKSSUPPORTGROUPNAME,
		V_WORKSSUPPORTPROJECTID,
		V_DESCRIPTION,
		T_ORDERINDEX,
		V_ISACTIVE,
		V_ISSYSTEM,
   	V_CREATEDUSER,
		SYSDATE,
	  1,
		V_USERHOSTADDRESS,
		V_CERTIFICATESTRING,
		V_LOGINLOGID
	);

END;
/