CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTQUALITY_V2_SEL
/*
	Created by	:	LƯƠNG TRUNG NHÂN 
	Date		:	30/05/2017
	Description	:	Nạp thông tin Trạng thái công việc cần hỗ trợ 
*/
(	
	v_WORKSSUPPORTQUALITYID IN EO_WORKSSUPPORTQUALITY.WORKSSUPPORTQUALITYID%type,	
	v_Out OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN v_Out FOR
	SELECT
		WORKSSUPPORTQUALITYID,
		WORKSSUPPORTQUALITYNAME,
		DESCRIPTION,
		ICONURL,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		CREATEDUSER,
		CREATEDDATE,
		UPDATEDUSER,
		UPDATEDDATE,
		ISDELETED,
		DELETEDUSER,
		DELETEDDATE
	FROM 
    EO_WORKSSUPPORTQUALITY
	WHERE
		WORKSSUPPORTQUALITYID = v_WORKSSUPPORTQUALITYID
;
END;
/