CREATE OR REPLACE PROCEDURE ERP.WORKSMEMBERROLE_CHECKNAME
/*	CREATED BY	:	NGUYEN VAN HUAN
	DATE		:	21.6.2017
	DESCRIPTION	:	KIEM TRA TEN TRUNG NHAU 
*/
(	
  V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORTMEMBERROLE.WORKSSUPPORTMEMBERROLEID%TYPE,
	V_WORKSSUPPORTMEMBERROLENAME IN EO_WORKSSUPPORTMEMBERROLE.WORKSSUPPORTMEMBERROLENAME%TYPE,
  V_ORDERINDEX IN EO_WORKSSUPPORTMEMBERROLE.ORDERINDEX%TYPE,	
	V_OUT OUT SYS_REFCURSOR
) 
AS
 T_CHECK_NAME NUMBER := 0;
 T_CHECK_ORDER NUMBER := -1;
BEGIN

  BEGIN
    SELECT count(1) INTO T_CHECK_NAME
    FROM EO_WORKSSUPPORTMEMBERROLE EW
    WHERE UPPER(WORKSSUPPORTMEMBERROLENAME) = UPPER(V_WORKSSUPPORTMEMBERROLENAME)
      AND WORKSSUPPORTMEMBERROLEID <> V_WORKSSUPPORTMEMBERROLEID
      AND ISDELETED =0;   
    EXCEPTION WHEN OTHERS THEN T_CHECK_NAME := 0;

  END;

  -- CHECK ORDERINDEX EXISTED
  IF (V_ORDERINDEX > 0) THEN
   BEGIN
    SELECT count(1) INTO T_CHECK_ORDER
    FROM EO_WORKSSUPPORTMEMBERROLE EW
    WHERE  ORDERINDEX = V_ORDERINDEX
      AND ISDELETED =0;  
    EXCEPTION WHEN OTHERS THEN T_CHECK_ORDER := 0;
  END; 
  END IF;
      
   -- RETURN TABLE
  OPEN V_OUT FOR
    SELECT T_CHECK_NAME AS WORKSSUPPORTMEMBERROLENAME, T_CHECK_ORDER AS ORDERINDEX
      FROM dual d;
  RETURN;    


END;
/