-- Script was generated by Devart dbForge Studio for Oracle, Version 3.1.260.0
-- Product home page: http://www.devart.com/dbforge/oracle/studio
-- Script date 6/23/2017 1:02:17 PM
-- Server version: Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production With the Partitioning, OLAP, Data Mining and Real Application Testing options
-- Client version: 

CREATE OR REPLACE PROCEDURE ERP.WORKSSUPORTPROJECT_V2_SEL
/*
	CREATED BY	:	NGUY?N VAN PH?N
	DATE		    :	15/06/2017
	DESCRIPTION	:	DANH SACH DU AN
 
*/
(	
    V_OUT OUT SYS_REFCURSOR,
    V_KEYWORDS NVARCHAR2 DEFAULT NULL,
    V_PAGEINDEX NUMBER DEFAULT -1,
    V_PAGESIZE NUMBER DEFAULT -1,
    V_ISDELETED EO_WORKSSUPPORTPROJECT.ISDELETED%TYPE DEFAULT -1
) 
AS
BEGIN
  OPEN V_OUT FOR
       SELECT * 
    FROM
    (
  			SELECT
  			  EDB.WORKSSUPPORTPROJECTID,
          EDB.WORKSSUPPORTPROJECTNAME,
          EDB.WORKSSUPPORTTYPEID,
          EDB.DESCRIPTION,
          EDB.ORDERINDEX,
          EDB.ISACTIVE,
          EDB.ISSYSTEM,
          EDB.ISDELETED,
  			  ROW_NUMBER() OVER (ORDER BY EDB.ORDERINDEX ASC ,EDB.CREATEDDATE DESC) STT,
          SUM(1) OVER()AS TOTALROWS
  			FROM
  				EO_WORKSSUPPORTPROJECT EDB
    		WHERE (V_ISDELETED < 0 
              OR EDB.ISDELETED = V_ISDELETED)
              AND (
                    V_KEYWORDS IS NULL
                    OR (CAST(TRIM(V_KEYWORDS) AS NVARCHAR2(2000)) = CAST(TRIM(EDB.WORKSSUPPORTPROJECTNAME) AS NVARCHAR2(2000)))
                    OR (UPPER(EDB.WORKSSUPPORTPROJECTNAME) LIKE '%'|| UPPER(TRIM(V_KEYWORDS)) || '%')                 
                  )
    
      --ORDER BY TO_CHAR(EDB.CREATEDDATE,'DD/MM/YYYY HH12:MI:SS') DESC ,ORDERINDEX ASC,TO_CHAR(EDB.CREATEDDATE,'DD/MM/YYYY HH12:MI:SS') DESC
		 )EDOB
     WHERE
          V_PAGESIZE < 0 
          OR
          (STT > V_PAGEINDEX * V_PAGESIZE AND STT <= (V_PAGEINDEX + 1) * V_PAGESIZE)
      ;
END;
/