CREATE OR REPLACE PROCEDURE ERP.WORKSSP_PROJECT_MEMBER_V2_ADD
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	17.07.2017
	DESCRIPTION	:	THÊM THANH VIEN DU AN CHO CONG VIEC CAN HO TRO
*/
(
  V_WORKSSUPPORTPROJECTID IN EO_WORKSSUPPORTPROJECT_MEMBER.WORKSSUPPORTPROJECTID%TYPE,
	V_MEMBERUSERNAME IN EO_WORKSSUPPORTPROJECT_MEMBER.MEMBERUSERNAME%TYPE,
  V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORTPROJECT_MEMBER.WORKSSUPPORTMEMBERROLEID%TYPE,
  V_ISAUTOADDMEMBERTOWORKSGROUP IN EO_WORKSSUPPORTPROJECT_MEMBER.ISAUTOADDMEMBERTOWORKSGROUP%TYPE,
  V_CREATEDUSER IN EO_WORKSSUPPORTPROJECT_MEMBER.CREATEDUSER%TYPE
)
AS
  T_ORDERINDEX NUMBER := 0 ;
BEGIN 
  SELECT NVL(max(ORDERINDEX),0)+1 INTO T_ORDERINDEX 
    FROM 
         EO_WORKSSUPPORTPROJECT_MEMBER
    WHERE ISDELETED = 0;
	INSERT
	INTO EO_WORKSSUPPORTPROJECT_MEMBER
	(
		WORKSSUPPORTPROJECTID,
		MEMBERUSERNAME,
		WORKSSUPPORTMEMBERROLEID,
    ORDERINDEX,
    ISAUTOADDMEMBERTOWORKSGROUP,
    CREATEDUSER,
		CREATEDDATE
	)
	VALUES
	(
		V_WORKSSUPPORTPROJECTID,
		V_MEMBERUSERNAME,
		V_WORKSSUPPORTMEMBERROLEID,
    T_ORDERINDEX,
    V_ISAUTOADDMEMBERTOWORKSGROUP,
    V_CREATEDUSER,
		SYSDATE
	);
END;
/