CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORT_MEMBER_V2_UPD
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	02/03/2013
	DESCRIPTION	:	C?P NH?T THÔNG TIN THANH VIEN THEO CONG VIEC
*/
(
  V_OUT OUT SYS_REFCURSOR,
	V_WORKSSUPPORTID IN EO_WORKSSUPPORT_MEMBER.WORKSSUPPORTID%TYPE,
	V_WORKSSUPPORTDATE IN EO_WORKSSUPPORT_MEMBER.WORKSSUPPORTDATE%TYPE,
	V_MEMBERUSERNAME IN EO_WORKSSUPPORT_MEMBER.MEMBERUSERNAME%TYPE,
	V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORT_MEMBER.WORKSSUPPORTMEMBERROLEID%TYPE,
	V_NOTE IN EO_WORKSSUPPORT_MEMBER.NOTE%TYPE,
	V_UPDATEDUSER IN EO_WORKSSUPPORT_MEMBER.UPDATEDUSER%TYPE,
	V_UPDATEDDATE IN EO_WORKSSUPPORT_MEMBER.UPDATEDDATE%TYPE,
	V_ISDELETED IN EO_WORKSSUPPORT_MEMBER.ISDELETED%TYPE,
	V_DELETEDUSER IN EO_WORKSSUPPORT_MEMBER.DELETEDUSER%TYPE,
  V_DELETEDDATE IN EO_WORKSSUPPORT_MEMBER.DELETEDDATE%TYPE
    
) 
AS
BEGIN
  	UPDATE EO_WORKSSUPPORT_MEMBER
  	SET
  		WORKSSUPPORTID	= V_WORKSSUPPORTID,
  		WORKSSUPPORTDATE	= V_WORKSSUPPORTDATE,
  		MEMBERUSERNAME	= V_MEMBERUSERNAME,
  		WORKSSUPPORTMEMBERROLEID	= V_WORKSSUPPORTMEMBERROLEID,
  		NOTE	= V_NOTE,
  		UPDATEDUSER	= V_UPDATEDUSER,
  		UPDATEDDATE	= SYSDATE,
  		ISDELETED	= V_ISDELETED,
  		DELETEDUSER	= V_DELETEDUSER,
      DELETEDDATE =SYSDATE
  	WHERE
  		WORKSSUPPORTID = V_WORKSSUPPORTID;
  
	 OPEN V_OUT FOR 
    SELECT * 
      FROM EO_WORKSSUPPORT_MEMBER WHERE  WORKSSUPPORTID = V_WORKSSUPPORTID;
    RETURN;
END;
/