CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORT_GROUP_SEL_ROLE
/*
	CREATED BY	:	Nguyen Van Huan
	DATE		:	27.06.2017
	DESCRIPTION	:	lay tat ca role theo project id
*/
(	 
  V_PROJECTID IN EO_WORKSSUPPORTPROJECT.WORKSSUPPORTPROJECTID%TYPE,
  V_OUT OUT SYS_REFCURSOR
)
AS
BEGIN
 OPEN V_OUT FOR
  SELECT EWR.WORKSSUPPORTMEMBERROLEID, EWR.WORKSSUPPORTMEMBERROLENAME FROM 
    EO_WORKSSUPPORTPROJECT EWP
    LEFT JOIN ERP.EO_WORKSSUPPORTTYPE EWT 
    ON EWP.WORKSSUPPORTTYPEID = EWT.WORKSSUPPORTTYPEID 
    LEFT JOIN ERP.EO_WORKSSUPPORTTYPE_MEMBERROLE EWM 
    ON EWT.WORKSSUPPORTTYPEID = EWM.WORKSSUPPORTTYPEID 
    LEFT JOIN ERP.EO_WORKSSUPPORTMEMBERROLE EWR 
    ON EWR.WORKSSUPPORTMEMBERROLEID = EWM.WORKSSUPPORTMEMBERROLEID 
    WHERE 
    EWP.WORKSSUPPORTPROJECTID = V_PROJECTID AND 
    EWP.ISDELETED =0 AND
    EWT.ISDELETED =0 AND
    EWR.ISDELETED =0;                                                                                                                                                                                                                                         
END;
/