CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORT_MEMBER_V2_GETALL
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	27.06.2017
	DESCRIPTION	:	N?P DANH SÁCH THANH VIEN THUOC CONG VIEC CUA CÔNG VI?C C?N H? TR? 

*/
(
  V_OUT OUT SYS_REFCURSOR
)
AS
BEGIN
  OPEN V_OUT FOR
  SELECT
    EO_WORKSSUPPORT_MEMBER.WORKSSUPPORTID,
    EO_WORKSSUPPORT_MEMBER.WORKSSUPPORTDATE,
    EO_WORKSSUPPORT_MEMBER.MEMBERUSERNAME,
    EO_WORKSSUPPORT_MEMBER.WORKSSUPPORTMEMBERROLEID,
    EO_WORKSSUPPORT_MEMBER.NOTE,
    EO_WORKSSUPPORT_MEMBER.UPDATEDUSER,
    EO_WORKSSUPPORT_MEMBER.UPDATEDDATE,
    EO_WORKSSUPPORT_MEMBER.ISDELETED,
    EO_WORKSSUPPORT_MEMBER.DELETEDUSER,
    EO_WORKSSUPPORT_MEMBER.DELETEDDATE
   
  FROM
    ERP.EO_WORKSSUPPORT_MEMBER
  WHERE
   -- EO_WORKSSUPPORT_MEMBER.ISACTIVE = 1AND 
    EO_WORKSSUPPORT_MEMBER.ISDELETED = 0

  ORDER BY
    EO_WORKSSUPPORT_MEMBER.WORKSSUPPORTID
  ;
END;
/