CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTGROUP_V2_GETALL
/*
	CREATED BY	:	NGUYEN VAN HUAN
	DATE		:	26/06/2017
	DESCRIPTION	:	N?P DANH SÁCH NHÓM CÔNG VI?C C?N H? TR? THEO PROJECTID
*/
(   
    V_PROJECTID EO_WORKSSUPPORTGROUP.WORKSSUPPORTPROJECTID%TYPE,
    V_OUT OUT SYS_REFCURSOR
)
  AS
  BEGIN
    OPEN V_OUT FOR
      SELECT WS.WORKSSUPPORTGROUPID,
             WS.WORKSSUPPORTGROUPNAME,
             WS.DESCRIPTION,
             WS.ORDERINDEX,
             WS.ISACTIVE,
             WS.ISSYSTEM,
             WS.ISDELETED,
             WS.CREATEDUSER,
             WS.CREATEDDATE,
             WS.UPDATEDUSER,
             WS.UPDATEDDATE,
             WS.ISDELETED,
             WS.DELETEDUSER,
             WS.DELETEDDATE
        FROM EO_WORKSSUPPORTGROUP WS
        WHERE WS.WORKSSUPPORTPROJECTID = V_PROJECTID AND
              WS.ISDELETED = 0;
  END;
/