CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTGROUP_V2_GETGROUP
/*
	CREATED BY	:	NGUYEN VAN HUAN
	DATE		:	26/06/2017
	DESCRIPTION	:	N?P DANH SÁCH NHÓM CÔNG VI?C C?N H? TR? THEO PROJECTID
*/
(   
    V_PROJECTID IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTPROJECTID%TYPE,
    V_OUT OUT SYS_REFCURSOR
)
  AS
  BEGIN
    OPEN V_OUT FOR
      SELECT WS.WORKSSUPPORTGROUPID,
             WS.WORKSSUPPORTGROUPNAME,
            (SELECT COUNT(1) FROM EO_WORKSSUPPORTGROUP_MEMBER EWM 
              WHERE EWM.WORKSSUPPORTGROUPID = WS.WORKSSUPPORTGROUPID AND EWM.ISDELETED = 0
             ) AS NUMBEROFMEMBER,
            (SELECT COUNT(1) FROM EO_WORKSSUPPORT  EWW 
              WHERE EWW.WORKSSUPPORTGROUPID = WS.WORKSSUPPORTGROUPID AND EWW.ISDELETED = 0
             ) AS numberofwork,
             WS.ICONURL
                   
        FROM EO_WORKSSUPPORTGROUP WS
        WHERE WS.WORKSSUPPORTPROJECTID = V_PROJECTID AND
              WS.ISDELETED = 0
        ORDER BY WS.CREATEDDATE DESC;
  END;
/