CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTQUALITY_V2_ADD
/*
	CREATED BY	:	LƯƠNG TRUNG NHÂN 
	DATE		:	30/05/2017
	DESCRIPTION	:	THÊM THÔNG TIN CHẤT LƯỢNG CÔNG VIỆC CẦN HỖ TRỢ
*/
(
	V_WORKSSUPPORTQUALITYID IN EO_WORKSSUPPORTQUALITY.WORKSSUPPORTQUALITYID%TYPE,
	V_WORKSSUPPORTQUALITYNAME IN EO_WORKSSUPPORTQUALITY.WORKSSUPPORTQUALITYNAME%TYPE,
	V_DESCRIPTION IN EO_WORKSSUPPORTQUALITY.DESCRIPTION%TYPE,
  V_ICONURL IN EO_WORKSSUPPORTQUALITY.ICONURL%TYPE,
	V_ORDERINDEX IN EO_WORKSSUPPORTQUALITY.ORDERINDEX%TYPE,
	V_ISACTIVE IN EO_WORKSSUPPORTQUALITY.ISACTIVE%TYPE,
	V_ISSYSTEM IN EO_WORKSSUPPORTQUALITY.ISSYSTEM%TYPE,
	V_CREATEDUSER IN EO_WORKSSUPPORTQUALITY.CREATEDUSER%TYPE,
	V_CERTIFICATESTRING IN EO_WORKSSUPPORTQUALITY_LOG.CERTIFICATESTRING%TYPE,
	V_USERHOSTADDRESS IN EO_WORKSSUPPORTQUALITY_LOG.USERHOSTADDRESS%TYPE,
	V_LOGINLOGID IN EO_WORKSSUPPORTQUALITY_LOG.LOGINLOGID%TYPE

)
AS
--T_COUNT NUMBER;
  T_ORDERINDEX EO_WORKSSUPPORTQUALITY.ORDERINDEX%TYPE;
BEGIN
  BEGIN
   -- SELECT COUNT(ORDERINDEX) INTO T_COUNT FROM EO_WORKSSUPPORTQUALITY;
    SELECT COUNT(*) +1 INTO T_ORDERINDEX 
    FROM 
      EO_WORKSSUPPORTQUALITY 
    WHERE ISDELETED = 0;
  --  EXCEPTION WHEN OTHERS THEN T_COUNT:=0;
  END; 
	INSERT
	INTO EO_WORKSSUPPORTQUALITY
	(
	--	WORKSSUPPORTQUALITYID,
		WORKSSUPPORTQUALITYNAME,
		DESCRIPTION,
  ICONURL,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		CREATEDUSER,
		CREATEDDATE
	)
	VALUES
	(
	--	V_WORKSSUPPORTQUALITYID,
		V_WORKSSUPPORTQUALITYNAME,
		V_DESCRIPTION,
  V_ICONURL,
		T_ORDERINDEX,
    --V_ORDERINDEX,
		V_ISACTIVE,
		V_ISSYSTEM,
		V_CREATEDUSER,
		SYSDATE
	);
	INSERT
	INTO EO_WORKSSUPPORTQUALITY_LOG
	(
		WORKSSUPPORTQUALITYID,
		WORKSSUPPORTQUALITYNAME,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		UPDATEDUSER,
		UPDATEDDATE,
		LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID   
	)
	VALUES
	(
		V_WORKSSUPPORTQUALITYID,
		V_WORKSSUPPORTQUALITYNAME,
		V_DESCRIPTION,
		T_ORDERINDEX,
   -- V_ORDERINDEX,
		V_ISACTIVE,
		V_ISSYSTEM,
		V_CREATEDUSER,
		SYSDATE,
		1,
		V_USERHOSTADDRESS,
		V_CERTIFICATESTRING,
		V_LOGINLOGID

	);
END;
/