CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTPRIORITY_V2_CHECK
/*	CREATED BY	:	NGUYEN VAN HUAN
	DATE		:	21.6.2017
	DESCRIPTION	:	KIEM TRA TEN TRUNG NHAU TRONG BANG EO_WORKSSUPPORTPRIORITY
*/
(	
  V_WORKSSUPPORTPRIORITYID IN EO_WORKSSUPPORTPRIORITY.workssupportpriorityid%TYPE,
	V_WORKSSUPPORTPRIORITYNAME IN EO_WORKSSUPPORTPRIORITY.WORKSSUPPORTPRIORITYNAME%TYPE,
  V_ORDERINDEX IN EO_WORKSSUPPORTPRIORITY.ORDERINDEX%TYPE,
	V_OUT OUT SYS_REFCURSOR
) 
AS
 T_CHECK_NAME NUMBER := 0;
 T_CHECK_ORDER NUMBER := -1;
BEGIN
  -- CHECK WORKSSUPPORTPRIORITYNAME EXISTED
  BEGIN
    SELECT count(1) INTO T_CHECK_NAME
    FROM EO_WORKSSUPPORTPRIORITY EO
    WHERE UPPER(EO.WORKSSUPPORTPRIORITYNAME) = UPPER(V_WORKSSUPPORTPRIORITYNAME) AND eo.workssupportpriorityid <> v_workssupportpriorityid
    AND isdeleted =0;    
    EXCEPTION WHEN OTHERS THEN T_CHECK_NAME := 0;
  END;
  
  -- CHECK ORDERINDEX EXISTED
  IF (V_ORDERINDEX > 0) THEN
  BEGIN
    SELECT count(1) INTO T_CHECK_ORDER
    FROM EO_WORKSSUPPORTPRIORITY EO
    WHERE EO.orderindex = V_ORDERINDEX 
    AND isdeleted =0;    
    EXCEPTION WHEN OTHERS THEN T_CHECK_ORDER := 0;
  END;
  END IF;
  -- RETURN TABLE
  OPEN v_out FOR
    SELECT T_CHECK_NAME AS PRIORITYNAME, t_check_order AS ORDERINDEX
      FROM dual d;
  RETURN;    

END;
/