CREATE OR REPLACE PROCEDURE ERP.WORKS_GROUP_MEMBER_V2_ADD
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	30/05/2017
	DESCRIPTION	:	THÊM THÔNG TIN THANH VIEN THEO NHOM CÔNG VI?C C?N H? TR?
*/
(
	V_WORKSSUPPORTGROUPID IN EO_WORKSSUPPORTGROUP_MEMBER.WORKSSUPPORTGROUPID%TYPE,
	V_MEMBERUSERNAME IN EO_WORKSSUPPORTGROUP_MEMBER.MEMBERUSERNAME%TYPE,
	V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORTGROUP_MEMBER.WORKSSUPPORTMEMBERROLEID%TYPE,
  V_ISAUTOADDWORKSSUPPORT IN EO_WORKSSUPPORTGROUP_MEMBER.ISAUTOADDMEMBERTOWORKSSUPPORT%TYPE,
	V_DESCRIPTION IN EO_WORKSSUPPORTGROUP_MEMBER.DESCRIPTION%TYPE,
	V_ORDERINDEX IN EO_WORKSSUPPORTGROUP_MEMBER.ORDERINDEX%TYPE,
	V_ISACTIVE IN EO_WORKSSUPPORTGROUP_MEMBER.ISACTIVE%TYPE,
  V_ISSYSTEM IN EO_WORKSSUPPORTGROUP_MEMBER.ISSYSTEM%TYPE,
  V_CREATEDUSER IN EO_WORKSSUPPORTGROUP_MEMBER.CREATEDUSER%TYPE

)
AS
  T_ORDERINDEX EO_WORKSSUPPORTGROUP_MEMBER.ORDERINDEX%TYPE;
BEGIN
  BEGIN
    SELECT COUNT(*) +1 INTO T_ORDERINDEX 
    FROM 
      EO_WORKSSUPPORTGROUP_MEMBER 
    WHERE ISDELETED = 0;
  END; 
	INSERT
	INTO EO_WORKSSUPPORTGROUP_MEMBER
	(
    WORKSSUPPORTGROUPID,
		MEMBERUSERNAME,
		WORKSSUPPORTMEMBERROLEID,
    ISAUTOADDMEMBERTOWORKSSUPPORT,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		CREATEDUSER,
    CREATEDDATE
	)
	VALUES
	(
    V_WORKSSUPPORTGROUPID,
    V_MEMBERUSERNAME,
    V_WORKSSUPPORTMEMBERROLEID,
    V_ISAUTOADDWORKSSUPPORT,
    V_DESCRIPTION,
    T_ORDERINDEX,
    V_ISACTIVE,
    V_ISSYSTEM,
    V_CREATEDUSER,
    SYSDATE
	);
END;
/