CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORT_MEMBER_V2_SEL
/*
	Created by	:	NGUYEN THI KIM NGAN
	Date		:	02/03/2013
	Description	:	N?p thông tin THANH VIEN  CUA CONG VIEC TRONG công vi?c c?n h? tr? 
*/
(	
	v_WORKSSUPPORTID IN EO_WORKSSUPPORT_MEMBER.WORKSSUPPORTID%type,	
	v_Out OUT SYS_REFCURSOR
) 
AS
  T_STATUS NUMBER:=0;
BEGIN
    OPEN v_Out FOR
	SELECT
		WORKSSUPPORTID,
		WORKSSUPPORTDATE,
		MEMBERUSERNAME,
		WORKSSUPPORTMEMBERROLEID,
		NOTE,
		UPDATEDUSER,
		UPDATEDDATE,
		ISDELETED,
		DELETEDUSER,
		DELETEDDATE
	
	FROM 
    EO_WORKSSUPPORT_MEMBER
	WHERE
    ISDELETED =0 and
		WORKSSUPPORTID = V_WORKSSUPPORTID;
END;
/