CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTMEMBERROLE_V2_SEL 
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		    :	30/05/2017
	DESCRIPTION	:	DANH SACH VAI TRO TRONG CONG VIEC CAN HO TRO
*/
(
    V_OUT OUT SYS_REFCURSOR,
    V_KEYWORDS NVARCHAR2 DEFAULT NULL,
    V_ISDELETED EO_WORKSSUPPORTMEMBERROLE.ISDELETED%TYPE DEFAULT 0,
    --V_ISACTIVE EO_WORKSSUPPORTMEMBERROLE.ISACTIVE%TYPE DEFAULT -1,
    V_PAGEINDEX NUMBER DEFAULT -1,
    V_PAGESIZE NUMBER DEFAULT -1
) 
AS
BEGIN
  OPEN V_OUT FOR
       SELECT * 
        FROM(
	SELECT
		EO_WORKSSUPPORTMEMBERROLE.WORKSSUPPORTMEMBERROLEID,
		EO_WORKSSUPPORTMEMBERROLE.WORKSSUPPORTMEMBERROLENAME,
		EO_WORKSSUPPORTMEMBERROLE.DESCRIPTION,
  EO_WORKSSUPPORTMEMBERROLE.ICONURL,
		EO_WORKSSUPPORTMEMBERROLE.ORDERINDEX,
		EO_WORKSSUPPORTMEMBERROLE.ISACTIVE,
		EO_WORKSSUPPORTMEMBERROLE.ISSYSTEM,
		NVL2(EO_WORKSSUPPORTMEMBERROLE.CREATEDUSER,	EO_WORKSSUPPORTMEMBERROLE.CREATEDUSER ||'-'||CREATEDUSER.FULLNAME,'') CREATEDUSER,
		EO_WORKSSUPPORTMEMBERROLE.CREATEDDATE,
		NVL2( EO_WORKSSUPPORTMEMBERROLE.UPDATEDUSER,EO_WORKSSUPPORTMEMBERROLE.UPDATEDUSER ||'-'||UPDATEDUSER.FULLNAME,'') UPDATEDUSER,
		EO_WORKSSUPPORTMEMBERROLE.UPDATEDDATE,
		EO_WORKSSUPPORTMEMBERROLE.ISDELETED,
		EO_WORKSSUPPORTMEMBERROLE.DELETEDUSER,
		EO_WORKSSUPPORTMEMBERROLE.DELETEDDATE,
    ROW_NUMBER() OVER (ORDER BY EO_WORKSSUPPORTMEMBERROLE.ORDERINDEX ASC ,EO_WORKSSUPPORTMEMBERROLE.CREATEDDATE DESC) STT,
    SUM(1) OVER()AS TOTALROWS
	FROM 
    EO_WORKSSUPPORTMEMBERROLE
    LEFT  JOIN SYS_USER CREATEDUSER 
      ON CREATEDUSER.USERNAME = EO_WORKSSUPPORTMEMBERROLE.CREATEDUSER
    LEFT  JOIN SYS_USER UPDATEDUSER 
      ON UPDATEDUSER.USERNAME = EO_WORKSSUPPORTMEMBERROLE.UPDATEDUSER
	WHERE 
    EO_WORKSSUPPORTMEMBERROLE.ISDELETED = V_ISDELETED
    AND (V_KEYWORDS IS NULL 
         OR EO_WORKSSUPPORTMEMBERROLE.WORKSSUPPORTMEMBERROLEID LIKE '%' || V_KEYWORDS || '%'
         OR UPPER ( EO_WORKSSUPPORTMEMBERROLE.WORKSSUPPORTMEMBERROLENAME ) LIKE '%' ||UPPER ( V_KEYWORDS )|| '%')
        ORDER BY 
    EO_WORKSSUPPORTMEMBERROLE.ORDERINDEX
  )
    WHERE
    V_PAGESIZE < 0 
    OR
    (STT > V_PAGEINDEX * V_PAGESIZE AND STT <= (V_PAGEINDEX + 1) * V_PAGESIZE);
END;
/