CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORT_CM_V2_UPD_BETA
/*
	Created by	:	YourName 
	Date		:	09/03/2013
	Description	:	C?p nh?t thông tin  
*/
(
	v_COMMENTID IN EO_WORKSSUPPORT_COMMENT.COMMENTID%TYPE,
	v_WORKSSUPPORTID IN EO_WORKSSUPPORT_COMMENT.WORKSSUPPORTID%TYPE,
	v_COMMENTDATE IN EO_WORKSSUPPORT_COMMENT.COMMENTDATE%TYPE,
	v_COMMENTCONTENT IN EO_WORKSSUPPORT_COMMENT.COMMENTCONTENT%TYPE,
	v_COMMENTUSER IN EO_WORKSSUPPORT_COMMENT.COMMENTUSER%TYPE,
	v_ORDERINDEX IN EO_WORKSSUPPORT_COMMENT.ORDERINDEX%TYPE,
	v_ISACTIVE IN EO_WORKSSUPPORT_COMMENT.ISACTIVE%TYPE,
	v_ISSYSTEM IN EO_WORKSSUPPORT_COMMENT.ISSYSTEM%TYPE,
	v_UPDATEDUSER IN EO_WORKSSUPPORT_COMMENT.UPDATEDUSER%TYPE
) 
AS
BEGIN
	UPDATE EO_WORKSSUPPORT_COMMENT
	SET
		WORKSSUPPORTID	= v_WORKSSUPPORTID,
		COMMENTDATE	= SYSDATE,
		COMMENTCONTENT	= v_COMMENTCONTENT,
		COMMENTUSER	= v_COMMENTUSER,
		ORDERINDEX	= v_ORDERINDEX,
		ISACTIVE	= v_ISACTIVE,
		ISSYSTEM	= v_ISSYSTEM,
		UPDATEDUSER	= v_UPDATEDUSER,
		UPDATEDDATE	= SYSDATE
	WHERE
		COMMENTID = v_COMMENTID
;
	
END;
/