create or replace PROCEDURE     WORKSSUPPORTSTATUS_V2_SEL
/*
	Created by	:	Hoàng Nhý Phong 
	Date		:	02/03/2013
	Description	:	N?p thông tin Tr?ng thái công vi?c c?n h? tr? 
*/
(	
	v_WORKSSUPPORTSTATUSID IN EO_WORKSSUPPORTSTATUS.WORKSSUPPORTSTATUSID%type,	
	v_Out OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN v_Out FOR
	SELECT
	WORKSSUPPORTSTATUSID,
  WORKSSUPPORTSTATUSNAME,
  ICONURL,
  ISCOMPLETESTATUS,
  ISCLOSESTATUS,
  DESCRIPTION,
  ISINITSTATUS,
  ORDERINDEX,
  ISACTIVE,
  ISSYSTEM  
	FROM 
    EO_WORKSSUPPORTSTATUS
	WHERE
    ISDELETED =0 and
		WORKSSUPPORTSTATUSID = v_WORKSSUPPORTSTATUSID
;
END;
