CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTTYPE_CHECKNAME
/*	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	22.6.2017
	DESCRIPTION	:	KIEM TRA TEN TRUNG NHAU TRONG BANG EO_WORKSSUPPORTTYPE
*/
(	
  V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE.WORKSSUPPORTTYPEID%TYPE,
	V_WORKSSUPPORTTYPENAME IN EO_WORKSSUPPORTTYPE.WORKSSUPPORTTYPENAME%TYPE,
  V_ORDERINDEX IN EO_WORKSSUPPORTTYPE.ORDERINDEX%TYPE,	
	V_OUT OUT SYS_REFCURSOR
) 
AS
 T_CHECK_NAME NUMBER := 0;
 T_CHECK_ORDER NUMBER := 0;
BEGIN

  BEGIN
    SELECT 1 INTO T_CHECK_NAME
    FROM EO_WORKSSUPPORTTYPE EW
    WHERE UPPER(WORKSSUPPORTTYPENAME) = UPPER(V_WORKSSUPPORTTYPENAME)
      AND WORKSSUPPORTTYPEID <> V_WORKSSUPPORTTYPEID
      AND ISDELETED =0
      AND ROWNUM = 1;    
    EXCEPTION WHEN OTHERS THEN T_CHECK_NAME := 0;

  END; 

   BEGIN
    SELECT 1 INTO T_CHECK_ORDER
    FROM EO_WORKSSUPPORTTYPE EW
    WHERE (V_ORDERINDEX > 0 AND ORDERINDEX = V_ORDERINDEX)
      AND WORKSSUPPORTTYPEID <> V_WORKSSUPPORTTYPEID
      AND ISDELETED =0
      AND ROWNUM = 1;    
    EXCEPTION WHEN OTHERS THEN T_CHECK_ORDER := 0;

  END; 
      
   -- RETURN TABLE
  OPEN V_OUT FOR
    SELECT T_CHECK_NAME AS WORKSSUPPORTTYPENAME, T_CHECK_ORDER AS ORDERINDEX
      FROM dual d;
  RETURN;    


END;
/