CREATE OR REPLACE PROCEDURE ERP.WSPROJECT_MEMBER_V2_UPD
/*
	CREATED BY	:	NGUY?N VAN PH?N
	DATE		:	09/06/2017
	DESCRIPTION	:	C?P NH?T THÔNG TIN THANH VIEN THAM GIA DU AN
*/
(
	V_WORKSSUPPORTPROJECTID IN EO_WORKSSUPPORTPROJECT_MEMBER.WORKSSUPPORTPROJECTID%TYPE,
	V_MEMBERUSERNAME IN EO_WORKSSUPPORTPROJECT_MEMBER.MEMBERUSERNAME%TYPE,
  V_UPDATEDUSER IN EO_WORKSSUPPORTPROJECT_MEMBER.UPDATEDUSER%TYPE,
  V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORTPROJECT_MEMBER.WORKSSUPPORTMEMBERROLEID%TYPE,
  V_ISAUTOADDMEMBERTOWORKSGROUP IN EO_WORKSSUPPORTPROJECT_MEMBER.ISAUTOADDMEMBERTOWORKSGROUP%TYPE
) 
AS

BEGIN
	UPDATE EO_WORKSSUPPORTPROJECT_MEMBER
	   SET
        ISAUTOADDMEMBERTOWORKSGROUP = V_ISAUTOADDMEMBERTOWORKSGROUP,
    		WORKSSUPPORTMEMBERROLEID = V_WORKSSUPPORTMEMBERROLEID,
    		UPDATEDUSER	= V_UPDATEDUSER,
    		updateddate =	sysdate
	WHERE
		        WORKSSUPPORTPROJECTID = V_WORKSSUPPORTPROJECTID
        AND MEMBERUSERNAME= V_MEMBERUSERNAME 
        AND (ISAUTOADDMEMBERTOWORKSGROUP <> V_ISAUTOADDMEMBERTOWORKSGROUP 
         OR  V_WORKSSUPPORTMEMBERROLEID <> WORKSSUPPORTMEMBERROLEID);

END;
/