CREATE OR REPLACE PROCEDURE ERP.EO_WorksSupportType_WF_GETALL
  /*
	Created by	:	Nguyen thi kim ngan
	Date		:	02.06.2017
	Description	:	Xóa thông tin buoc xu ly công vi?c c?n h? tr? 
*/
(
  V_OUT OUT SYS_REFCURSOR
)
AS
BEGIN
  OPEN V_OUT FOR
  SELECT *
  FROM
    ERP.EO_WORKSSUPPORTTYPE_WORKFLOW
  WHERE
    EO_WORKSSUPPORTTYPE_WORKFLOW.ISACTIVE = 1
    AND EO_WORKSSUPPORTTYPE_WORKFLOW.ISDELETED = 0
  ORDER BY
    EO_WORKSSUPPORTTYPE_WORKFLOW.ORDERINDEX
  ;
END;
/