CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTTYPE_V2_CHECK
/*	CREATED BY	:	NGUYEN VAN HUAN
	DATE		:	21.6.2017
	DESCRIPTION	:	KIEM TRA TEN TRUNG NHAU TRONG BANG EO_WORKSSUPPORTPRIORITY
*/
(	
  V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE.WORKSSUPPORTTYPEID%TYPE,
	V_WORKSSUPPORTTYPENAME IN EO_WORKSSUPPORTTYPE.WORKSSUPPORTTYPENAME%TYPE,
  V_ORDERINDEX IN EO_WORKSSUPPORTTYPE.ORDERINDEX%TYPE,
	V_OUT OUT SYS_REFCURSOR
) 
AS
 T_CHECK_NAME NUMBER := 0;
 T_CHECK_ORDER NUMBER := -1;
BEGIN
  -- CHECK WORKSSUPPORTPRIORITYNAME EXISTED
  BEGIN
    SELECT COUNT(1) INTO T_CHECK_NAME
    FROM EO_WORKSSUPPORTTYPE EW 
    WHERE UPPER(EW.WORKSSUPPORTTYPENAME) = UPPER(V_WORKSSUPPORTTYPENAME) AND EW.WORKSSUPPORTTYPEID <> V_WORKSSUPPORTTYPEID
    AND ISDELETED =0;    
    EXCEPTION WHEN OTHERS THEN T_CHECK_NAME := 0;
  END;
  
  -- CHECK ORDERINDEX EXISTED
  IF (V_ORDERINDEX > 0) THEN
  BEGIN
    SELECT count(1) INTO T_CHECK_ORDER
    FROM EO_WORKSSUPPORTTYPE EW
    WHERE EW.ORDERINDEX = V_ORDERINDEX 
    AND ISDELETED =0;    
    EXCEPTION WHEN OTHERS THEN T_CHECK_ORDER := 0;
  END;
  END IF;
  -- RETURN TABLE
  OPEN v_out FOR
    SELECT T_CHECK_NAME AS PORTTYPENAME, T_CHECK_ORDER AS ORDERINDEX
      FROM DUAL D;
  RETURN;    

END;
/