CREATE OR REPLACE PROCEDURE ERP.WORKSSUPORTWORK_V2_CHK_WORK
/*	CREATED BY	:	NGUYEN VAN HUAN
  	DATE		    :	15.08.2017
  	DESCRIPTION	:	KIEM TRA TEN CONG VIEC TRUNG NHAU!.
*/
(	
  V_WORKSSUPPORTID IN EO_WORKSSUPPORT.WORKSSUPPORTID%TYPE,
  V_WORKSSUPPORTGROUPID IN EO_WORKSSUPPORT.WORKSSUPPORTGROUPID%TYPE,
  V_WORKSSUPPORTNAME IN EO_WORKSSUPPORT.WORKSSUPPORTNAME%TYPE,
	V_OUT OUT NUMBER
) 
AS
 T_CHECK_NAME NUMBER := 0;
BEGIN
  -- CHECK WORKSSUPPORTSTATUSNAME EXISTED
  BEGIN
    SELECT 
      COUNT(1) INTO T_CHECK_NAME
    FROM 
      EO_WORKSSUPPORT EW
    WHERE 
      UPPER(EW.WORKSSUPPORTNAME) = UPPER(V_WORKSSUPPORTNAME) AND EW.WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID AND
      EW.WORKSSUPPORTID <> V_WORKSSUPPORTID  AND EW.ISDELETED = 0;    
    EXCEPTION WHEN OTHERS THEN T_CHECK_NAME := 0;
  END; 
  -- RETURN TABLE
  V_OUT := T_CHECK_NAME;
  RETURN;    

END;
/