CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTMEMBERROLE_V2_DEL
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	30.05.2017
	DESCRIPTION	:	XÓA THÔNG TIN VAI TRO CÔNG VI?C C?N H? TR? 
*/
(
	V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORTMEMBERROLE.WORKSSUPPORTMEMBERROLEID%TYPE,
	V_DELETEDUSER IN EO_WORKSSUPPORTMEMBERROLE.DELETEDUSER%TYPE,
  V_CERTIFICATESTRING IN EO_WORKSSUPPORTMEMBERROLE_LOG.CERTIFICATESTRING%TYPE,
	V_USERHOSTADDRESS IN EO_WORKSSUPPORTMEMBERROLE_LOG.USERHOSTADDRESS%TYPE,
	V_LOGINLOGID IN EO_WORKSSUPPORTMEMBERROLE_LOG.LOGINLOGID%TYPE
)
AS
   V_ORDERINDEXDEL NUMBER;
BEGIN
  --1. LAY ODERINDEX CU DUOC DOI CAP NHAT THANH MOI
  SELECT ew.orderindex INTO V_ORDERINDEXDEL FROM EO_WORKSSUPPORTMEMBERROLE EW
  WHERE workssupportmemberroleid = V_WORKSSUPPORTMEMBERROLEID AND isdeleted =0;
 --2. XOA DU LIEU
	UPDATE EO_WORKSSUPPORTMEMBERROLE
	SET
		ISDELETED = 1,
		DELETEDDATE = SYSDATE,
		DELETEDUSER = V_DELETEDUSER
	WHERE
		WORKSSUPPORTMEMBERROLEID = V_WORKSSUPPORTMEMBERROLEID;
   --3. CAP NHAT LAI TAT CA CAC GIA TR? ORDERINDEX CÓ GIÁ TR? L?N HON ORDERINDEX B? XÓA
	UPDATE EO_WORKSSUPPORTMEMBERROLE
	SET
		orderindex = orderindex-1
	WHERE
		orderindex > v_orderindexdel AND isdeleted = 0 ;
  -- INSERT LOG
    INSERT
	INTO EO_WORKSSUPPORTMEMBERROLE_LOG
	(
		WORKSSUPPORTMEMBERROLEID,
		WORKSSUPPORTMEMBERROLENAME,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		UPDATEDUSER,
    UPDATEDDATE,
		LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID
	)
  SELECT
		WORKSSUPPORTMEMBERROLEID,
		WORKSSUPPORTMEMBERROLENAME,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		V_DELETEDUSER,
		SYSDATE,
		3,
		V_USERHOSTADDRESS,
		V_CERTIFICATESTRING,
		V_LOGINLOGID
    FROM 
      EO_WORKSSUPPORTMEMBERROLE
    WHERE 
      WORKSSUPPORTMEMBERROLEID = V_WORKSSUPPORTMEMBERROLEID;
END;
/