create or replace PROCEDURE WORKSSUPPORT_V2_WF_PER
/*
	CREATED BY	:	TRUONG HOANG NHI
	DATE		:	01/08/2017
	DESCRIPTION	:	N?P QUYEN NHÓM CÔNG VI?C C?N H? TR? THEO VAI TRO THANH VIEN DU AN
*/
(       
    V_USERNAME IN EO_WORKSSUPPORTGROUP_MEMBER.MEMBERUSERNAME%TYPE,
    V_WORKSSUPPORTGROUPID IN EO_WORKSSUPPORTGROUP_MEMBER.WORKSSUPPORTGROUPID%TYPE,
    V_OUT OUT SYS_REFCURSOR
)
 AS  
  BEGIN
     OPEN V_OUT FOR
      SELECT  
            WF_PERMIS.ISCANEDITCONTENT,
            WF_PERMIS.ISCANEDITSOLUTIONCONTENT,
            WF_PERMIS.ISCANADDATTACHMENT,
            WF_PERMIS.ISCANCOMMENT,
            WF_PERMIS.ISCANEDITEXPECTEDCOMPLETEDDATE,
            WF_PERMIS.ISCANCHANGEPROGRESS,
            WF_PERMIS.ISCANEDITQUALITY,
            WF_PERMIS.ISCANPROCESSWORKFLOW,
            WF_PERMIS.ISMUSTCHOOSEPROCESSUSER
        FROM 
            EO_WORKSSUPPORTTYPE_WF_PERMIS WF_PERMIS
        INNER JOIN 
            EO_WORKSSUPPORTGROUP_MEMBER MEMBERS
        ON 
            WF_PERMIS.WORKSSUPPORTMEMBERROLEID = MEMBERS.WORKSSUPPORTMEMBERROLEID 
        AND 
            MEMBERS.MEMBERUSERNAME = V_USERNAME
        AND 
            MEMBERS.WORKSSUPPORTSTEPID = V_WORKSSUPPORTGROUPID
        INNER JOIN
            EO_WORKSSUPPORTPROJECT PROJECTS
        ON
            PROJECTS.WORKSSUPPORTTYPEID = WF_PERMIS.WORKSSUPPORTTYPEID
        INNER JOIN 
            EO_WORKSSUPPORTGROUP EO_WORKSSUPPORTGROUP
        ON 
            PROJECTS.WORKSSUPPORTPROJECTID = EO_WORKSSUPPORTGROUP.WORKSSUPPORTPROJECTID
        AND 
            EO_WORKSSUPPORTGROUP.WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID
        GROUP BY 
            WF_PERMIS.ISCANEDITCONTENT,
            WF_PERMIS.ISCANEDITSOLUTIONCONTENT,
            WF_PERMIS.ISCANADDATTACHMENT,
            WF_PERMIS.ISCANCOMMENT,
            WF_PERMIS.ISCANEDITEXPECTEDCOMPLETEDDATE,
            WF_PERMIS.ISCANCHANGEPROGRESS,
            WF_PERMIS.ISCANEDITQUALITY,
            WF_PERMIS.ISCANPROCESSWORKFLOW,
            WF_PERMIS.ISMUSTCHOOSEPROCESSUSER;
  END;
  