//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientAuthen.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ssoservice.egovsams.com/handshake.asmx")]
        public string WebClientAuthen_SSOService_HandShake_HandShake {
            get {
                return ((string)(this["WebClientAuthen_SSOService_HandShake_HandShake"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://samsmasterdataservices.egovsams.com/Users/Users.asmx")]
        public string WebClientAuthen_ERPMasterDataServices_Users_Users_Users {
            get {
                return ((string)(this["WebClientAuthen_ERPMasterDataServices_Users_Users_Users"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ssoservice.egovsams.com/TokenAuthentication.asmx")]
        public string WebClientAuthen_SSOService_TokenAuthentication_TokenAuthentication {
            get {
                return ((string)(this["WebClientAuthen_SSOService_TokenAuthentication_TokenAuthentication"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ssoservice.egovsams.com/WSWebServiceHost.asmx")]
        public string WebClientAuthen_SSOService_WSWebServiceHost_WSWebServiceHost {
            get {
                return ((string)(this["WebClientAuthen_SSOService_WSWebServiceHost_WSWebServiceHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://samsmasterdataservices.egovsams.com/SYS/WSUser.asmx")]
        public string WebClientAuthen_SAMSMasterDataServices_WSUser_WSUser {
            get {
                return ((string)(this["WebClientAuthen_SAMSMasterDataServices_WSUser_WSUser"]));
            }
        }
    }
}
