CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTSTATUS_V2_DEL
/*
	Created by	:	Hoàng Nhu Phong 
	Date		:	02/03/2013
	Description	:	Xóa thông tin Tr?ng thái công vi?c c?n h? tr? 
*/
(
	v_WORKSSUPPORTSTATUSID IN EO_WORKSSUPPORTSTATUS.WORKSSUPPORTSTATUSID%TYPE,
	v_DELETEDUSER IN EO_WORKSSUPPORTSTATUS.DELETEDUSER%TYPE,
  v_CERTIFICATESTRING IN EO_WORKSSUPPORTSTATUS_LOG.CERTIFICATESTRING%TYPE,
	v_USERHOSTADDRESS IN EO_WORKSSUPPORTSTATUS_LOG.USERHOSTADDRESS%TYPE,
	v_LOGINLOGID IN EO_WORKSSUPPORTSTATUS_LOG.LOGINLOGID%TYPE
)
AS
   V_ORDERINDEXDEL NUMBER;
BEGIN
  --1. LAY ODERINDEX CU DUOC DOI CAP NHAT THANH MOI
  SELECT ew.orderindex INTO V_ORDERINDEXDEL FROM EO_WORKSSUPPORTSTATUS ew 
  WHERE workssupportstatusid = v_WORKSSUPPORTSTATUSID AND isdeleted =0;

  --2. XOA DU LIEU
	UPDATE EO_WORKSSUPPORTSTATUS
	SET
		ISDELETED = 1,
		DELETEDDATE = SYSDATE,
		DELETEDUSER = v_DELETEDUSER
	WHERE
		WORKSSUPPORTSTATUSID = v_WORKSSUPPORTSTATUSID;

  --3. CAP NHAT LAI TAT CA CAC GIA TR? ORDERINDEX CÓ GIÁ TR? L?N HON ORDERINDEX B? XÓA
	UPDATE EO_WORKSSUPPORTSTATUS
	SET
		orderindex = orderindex-1
	WHERE
		orderindex > v_orderindexdel AND isdeleted = 0 ;

  INSERT
	INTO EO_WORKSSUPPORTSTATUS_LOG
	(
		WORKSSUPPORTSTATUSID,
		WORKSSUPPORTSTATUSNAME,
		ICONURL,
		ISINITSTATUS,
		ISCOMPLETESTATUS,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		UPDATEDUSER,
		UPDATEDDATE,
    ISCLOSESTATUS,
		LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID

	)
  SELECT
		WORKSSUPPORTSTATUSID,
		WORKSSUPPORTSTATUSNAME,
		ICONURL,
		ISINITSTATUS,
		ISCOMPLETESTATUS,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		v_DELETEDUSER,
		UPDATEDDATE,
    ISCLOSESTATUS,
    3,
		v_USERHOSTADDRESS,
		v_CERTIFICATESTRING,
		v_LOGINLOGID
    FROM 
      EO_WORKSSUPPORTSTATUS
    WHERE 
      WORKSSUPPORTSTATUSID = v_WORKSSUPPORTSTATUSID;
END;
/