CREATE OR REPLACE PROCEDURE ERP.WORKSSUPORTPROJECT_V2_DEL
/*
	Created by	:	Nguy?n Van Ph?n 
	Date		:	09/06/2017
	Description	:	Xóa thông tin d? án
*/
(
	v_WORKSSUPPORTPROJECTID IN EO_WORKSSUPPORTPROJECT.WORKSSUPPORTPROJECTID%TYPE,
	v_DELETEDUSER IN EO_WORKSSUPPORTPROJECT.DELETEDUSER%TYPE,
  v_CERTIFICATESTRING IN EO_WORKSSUPPORTPROJECT_LOG.CERTIFICATESTRING%TYPE,
	v_USERHOSTADDRESS IN EO_WORKSSUPPORTPROJECT_LOG.USERHOSTADDRESS%TYPE,
	v_LOGINLOGID IN EO_WORKSSUPPORTPROJECT_LOG.LOGINLOGID%TYPE
)
AS
  T_GROUPID NUMBER:= 0;
BEGIN
  -- Xóa d? án công vi?c c?n h? tr?
	UPDATE EO_WORKSSUPPORTPROJECT
	SET
		ISDELETED = 1,
		DELETEDDATE = SYSDATE,
		DELETEDUSER = v_DELETEDUSER
	WHERE
		WORKSSUPPORTPROJECTID = v_WORKSSUPPORTPROJECTID;
  INSERT
	INTO EO_WORKSSUPPORTPROJECT_LOG
	(
		WORKSSUPPORTPROJECTID,
		WORKSSUPPORTPROJECTNAME,
		WORKSSUPPORTTYPEID,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		UPDATEDUSER,
		UPDATEDDATE,
		LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID

	)
  SELECT
		WORKSSUPPORTPROJECTID,
		WORKSSUPPORTPROJECTNAME,
		WORKSSUPPORTTYPEID,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM, 
		v_DELETEDUSER,
		UPDATEDDATE,
    3,
		v_USERHOSTADDRESS,
		v_CERTIFICATESTRING,
		v_LOGINLOGID

    FROM 
      EO_WORKSSUPPORTPROJECT
    WHERE 
      WORKSSUPPORTPROJECTID = v_WORKSSUPPORTPROJECTID;
  -- Xóa nhóm công vi?c c?n ho tro tuong ung v?i d? án

  UPDATE EO_WORKSSUPPORTGROUP  
    SET ISDELETED = 1,
        DELETEDUSER =V_DELETEDUSER,
        DELETEDDATE = SYSDATE 
    WHERE WORKSSUPPORTPROJECTID = V_WORKSSUPPORTPROJECTID ;
    INSERT
	INTO EO_WORKSSUPPORTGROUP_LOG
	(
		WORKSSUPPORTGROUPID,
		WORKSSUPPORTGROUPNAME,
		WORKSSUPPORTPROJECTID,
    WORKSSUPPORTTYPEID,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		UPDATEDUSER,
		UPDATEDDATE,
		LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID

	)
  SELECT
		WORKSSUPPORTGROUPID,
		WORKSSUPPORTGROUPNAME,
		WORKSSUPPORTPROJECTID,
    1,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM, 
		v_DELETEDUSER,
		UPDATEDDATE,
    3,
		v_USERHOSTADDRESS,
		v_CERTIFICATESTRING,
		v_LOGINLOGID

    FROM 
      EO_WORKSSUPPORTGROUP 
    WHERE 
      WORKSSUPPORTPROJECTID = v_WORKSSUPPORTPROJECTID;
END;
/