CREATE OR REPLACE PROCEDURE ERP."SYS_USER_DEL" 
/*
	Created by	:	Truong Trung L?i 
	Date		:	18/07/2012
	Description	:	Xóa thông tin Ngu?i dùng 
*/
(
	v_USERNAME IN SYS_USER.USERNAME%TYPE
,
	v_DELETEDUSER IN SYS_USER.DELETEDUSER%TYPE,
  v_CERTIFICATESTRING IN SYS_USER_LOG.CERTIFICATESTRING%TYPE,
	v_USERHOSTADDRESS IN SYS_USER_LOG.USERHOSTADDRESS%TYPE,
	v_LOGINLOGID IN SYS_USER_LOG.LOGINLOGID%TYPE 
)
AS
BEGIN

  RAISE_APPLICATION_ERROR( -20002, '[+Ch?c nang h?y ngu?i dùng không cho phép s? d?ng.+]' );

	UPDATE SYS_USER
	SET
		ISDELETED = 1,
		DELETEDDATE = SYSDATE,
		DELETEDUSER = v_DELETEDUSER
	WHERE
		USERNAME = v_USERNAME;
      
   DELETE Sys_User_Company
     WHERE username = v_USERNAME;

   DELETE Sys_User_Usergroup
     WHERE username = v_USERNAME;
     
   DELETE Sys_User_Store
     WHERE username = v_USERNAME;

   DELETE Sys_User_Maingroup
     WHERE username = v_USERNAME;

   DELETE Sys_User_Module
     WHERE username = v_USERNAME;

  DELETE Sys_User_Pricearea
     WHERE username = v_USERNAME;

  DELETE Sys_User_Usertype
       WHERE username = v_USERNAME;
INSERT
	INTO SYS_USER_LOG
	(
		USERNAME,
		PASSWORD,
		FULLNAME,
		FIRSTNAME,
		LASTNAME,
		GENDER,
		BIRTHDAY,
		EMAIL,
		PHONENUMBER,
		MOBI,
		ADDRESS,
		DEPARTMENTID,
		POSITIONID,
		AREAID,
		DESCRIPTION,
		BANKACCOUNTID,
		IDCARD,
		BEGINWORKDATE,
		WORKSTOREID,
		SIGNATUREPICTURE,
		DEFAULTPICTUREURL,
    WORKINGPOSITIONID,
    ISREALSTAFF,
		ISGROUPUSER,
		ISACTIVE,
		ISSYSTEM,
    ISAUTOADDCUMULATIONTIMEOFFDAYS,
		UPDATEDUSER,
		UPDATEDDATE,
		LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID

	)
  select 
    USERNAME,
		PASSWORD,
		FULLNAME,
		FIRSTNAME,
		LASTNAME,
		GENDER,
		BIRTHDAY,
		EMAIL,
		PHONENUMBER,
		MOBI,
		ADDRESS,
		DEPARTMENTID,
		POSITIONID,
		AREAID,
		DESCRIPTION,
		BANKACCOUNTID,
		IDCARD,
		BEGINWORKDATE,
		WORKSTOREID,
		SIGNATUREPICTURE,
		DEFAULTPICTUREURL,
    WORKINGPOSITIONID,
    ISREALSTAFF,
		ISGROUPUSER,
		ISACTIVE,
		ISSYSTEM,ISAUTOADDCUMULATIONTIMEOFFDAYS,
		v_DELETEDUSER,
		DELETEDDATE,
		3,
		v_USERHOSTADDRESS,
		v_CERTIFICATESTRING,
		v_LOGINLOGID
    from SYS_USER
    where USERNAME = v_USERNAME;
END;
/