create or replace PROCEDURE WORKSSUPPORT_WFNX_V2_GETBY
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	02/06/2017
	DESCRIPTION	:	N?P DANH SACH BUOC XU LY KE TIEP TRONG CONG VIEC CAN HO TRO
*/ (
    V_OUT              OUT SYS_REFCURSOR,
    V_WORKSSUPPORTID   IN EO_WORKSSUPPORT.WORKSSUPPORTID%TYPE,
    V_USER IN EO_WORKSSUPPORT.CREATEDUSER%TYPE
)
    AS
BEGIN
    OPEN V_OUT FOR

    SELECT 
        NX.NEXTWORKSSUPPORTSTEPID,
        WF.WORKSSUPPORTSTEPNAME,
        WF.ISMUSTCHOOSEPROCESSUSER
    FROM 
        EO_WORKSSUPPORTTYPE_WFNXPERMIS NX
    LEFT JOIN
        EO_WORKSSUPPORTTYPE_WORKFLOW WF
    ON
        NX.NEXTWORKSSUPPORTSTEPID = WF.WORKSSUPPORTSTEPID
    INNER JOIN
        EO_WORKSSUPPORT SP
    ON
        WF.WORKSSUPPORTTYPEID = SP.WORKSSUPPORTTYPEID
    WHERE 
        SP.WORKSSUPPORTID = V_WORKSSUPPORTID
    AND 
        NX.WORKSSUPPORTSTEPID = SP.CURRENTWORKSSUPPORTSTEPID
        and
    NX.WORKSSUPPORTMEMBERROLEID = 
    (
    select
    MEMBER.WORKSSUPPORTMEMBERROLEID
    from 
    EO_WORKSSUPPORTGROUP_MEMBER MEMBER
        INNER JOIN
        EO_WORKSSUPPORT EO_WORKSSUPPORT
    ON 
        MEMBER.WORKSSUPPORTGROUPID = EO_WORKSSUPPORT.WORKSSUPPORTGROUPID
    AND
        EO_WORKSSUPPORT.WORKSSUPPORTID = V_WORKSSUPPORTID
    AND 
        MEMBER.MEMBERUSERNAME = V_USER
    )
    ORDER BY
        WF.WORKSSUPPORTSTEPID ASC;
END;