CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORT_MEMBER_V2_ADD
/*
	CREATED BY	:	NGUYEN THI KIM NGAN 
	DATE		:	27.06.2017
	DESCRIPTION	:	THÊM THÔNG TIN DANH SACH THANH VIEN THEO CONG VIEC CUA CONG VIEC CAN HO TRO

*/
(
	V_WORKSSUPPORTID IN EO_WORKSSUPPORT_MEMBER.WORKSSUPPORTID%TYPE,
	V_WORKSSUPPORTDATE IN EO_WORKSSUPPORT_MEMBER.WORKSSUPPORTDATE%TYPE,
	V_MEMBERUSERNAME IN EO_WORKSSUPPORT_MEMBER.MEMBERUSERNAME%TYPE,
	V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORT_MEMBER.WORKSSUPPORTMEMBERROLEID%TYPE,
	V_NOTE IN EO_WORKSSUPPORT_MEMBER.NOTE%TYPE,
	V_UPDATEDUSER IN EO_WORKSSUPPORT_MEMBER.UPDATEDUSER%TYPE,
	V_UPDATEDDATE IN EO_WORKSSUPPORT_MEMBER.UPDATEDDATE%TYPE,
	V_ISDELETED IN EO_WORKSSUPPORT_MEMBER.ISDELETED%TYPE,
	V_DELETEDUSER IN EO_WORKSSUPPORT_MEMBER.DELETEDUSER%TYPE,
  V_DELETEDDATE IN EO_WORKSSUPPORT_MEMBER.DELETEDDATE%TYPE
 
)
AS
BEGIN
	INSERT
	INTO EO_WORKSSUPPORT_MEMBER
	(
		WORKSSUPPORTID,
		WORKSSUPPORTDATE,
		MEMBERUSERNAME,
		WORKSSUPPORTMEMBERROLEID,
		NOTE,
		UPDATEDUSER,
		UPDATEDDATE,
		ISDELETED,
		DELETEDUSER,
		DELETEDDATE
	)
	VALUES
	(
    V_WORKSSUPPORTID,
    V_WORKSSUPPORTDATE,
    V_MEMBERUSERNAME,
    V_WORKSSUPPORTMEMBERROLEID,
    V_NOTE,
    V_UPDATEDUSER,
    V_UPDATEDDATE,
    V_ISDELETED,
    V_DELETEDUSER,
    V_DELETEDDATE
);
END;
/