CREATE OR REPLACE PROCEDURE ERP.WS_CMT_ATTACHMENT_V2_SRH
/*
	Created by	:	Hoàng Van Minh 
	Date		:	8/8/2016
	Description	:	L?y danh sách file dính kèm c?a bình lu?n công vi?c c?n h? tr?
*/
(
    V_OUT OUT SYS_REFCURSOR,
    V_COMMENTID IN EO_WORKSSUPPORT_CMT_ATTACHMENT.COMMENTID%TYPE
) 
AS
BEGIN
    OPEN V_OUT FOR
  	SELECT
  		ATTACHMENTID,
  		COMMENTID,
  		COMMENTDATE,
  		FILEPATH,
  		FILENAME,
  		FILEID
  	FROM EO_WORKSSUPPORT_CMT_ATTACHMENT
  	WHERE ISDELETED = 0 AND TRIM(COMMENTID) = TRIM(V_COMMENTID);
END;
/