create or replace PROCEDURE EO_WORKSSUPPORTTYPE_WFNX_P_ADD
/*
	CREATED BY	:	LÝÕNG TRUNG NHÂN 
	DATE		:	12/06/2017
	DESCRIPTION	:	THÊM THÔNG TIN B?NG CH?A QUY?N TRÊN CÁC BÝ?C X? L? K? TI?P THEO
*/ (

	V_WORKSSUPPORTSTEPID         IN EO_WORKSSUPPORTTYPE_WFNXPERMIS.WORKSSUPPORTSTEPID%TYPE,
    V_NEXTWORKSSUPPORTSTEPID     IN EO_WORKSSUPPORTTYPE_WFNXPERMIS.NEXTWORKSSUPPORTSTEPID%TYPE,
	V_WORKSSUPPORTMEMBERROLEID   IN EO_WORKSSUPPORTTYPE_WFNXPERMIS.WORKSSUPPORTMEMBERROLEID%TYPE,  
    V_WORKSSUPPORTTYPEID         IN EO_WORKSSUPPORTTYPE_WFNXPERMIS.WORKSSUPPORTTYPEID%TYPE

)
AS BEGIN
    INSERT INTO EO_WORKSSUPPORTTYPE_WFNXPERMIS (
        WORKSSUPPORTSTEPID,
        NEXTWORKSSUPPORTSTEPID,
        WORKSSUPPORTMEMBERROLEID,
        WORKSSUPPORTTYPEID,
        ISCANCHOOSENEXTSTEP
    ) VALUES (
        V_WORKSSUPPORTSTEPID,
        V_NEXTWORKSSUPPORTSTEPID,
        V_WORKSSUPPORTMEMBERROLEID,
        V_WORKSSUPPORTTYPEID,
        1
    );

END;