create or replace PROCEDURE  EO_WORKSSUPPORTPROJECT_P_SEL
/*
	CREATED BY	:	LÝÕNG TRUNG NHÂN 
	DATE		:	07/06/2017
	DESCRIPTION	:	N?P THÔNG TIN QUY?N THEO D? ÁN
*/
(	
	V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTPROJECT_PERMIS.WORKSSUPPORTTYPEID%TYPE,	
	V_OUT OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN V_OUT FOR
	SELECT
		WORKSSUPPORTTYPEID,
		SYS_USER.USERNAME,
        FULLNAME,
		ISCANADDPROJECT,
		ISCANEDITPROJECT,
		ISCANDELETEPROJECT,
		ISCANVIEWPROJECT,
        ISCANVIEWPROJECTREPORT
	FROM 
    EO_WORKSSUPPORTPROJECT_PERMIS
    LEFT JOIN SYS_USER
    ON EO_WORKSSUPPORTPROJECT_PERMIS.USERNAME = SYS_USER.username
	WHERE
		WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID
;
END;
