CREATE OR REPLACE PROCEDURE ERP.EO_WORKSSUPPORTTYPE_P_ADD
/*
	CREATED BY	:	LUONG TRUNG NHÂN 
	DATE		:	02/06/2017
	DESCRIPTION	:	THÊM THÔNG TIN B?NG LIÊN K?T LO?I CÔNG VI?C VÀ Ð? UU TIÊN CÔNG VI?C
*/
(
	V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE_PRIORITY.WORKSSUPPORTTYPEID%TYPE,
	V_WORKSSUPPORTPRIORITYID IN EO_WORKSSUPPORTTYPE_PRIORITY.WORKSSUPPORTPRIORITYID%TYPE
)
AS
T_COUNT NUMBER;
BEGIN
	INSERT
	INTO EO_WORKSSUPPORTTYPE_PRIORITY
	(
		WORKSSUPPORTTYPEID,
		WORKSSUPPORTPRIORITYID
	)
	VALUES
	(
		V_WORKSSUPPORTTYPEID,
		V_WORKSSUPPORTPRIORITYID
	);
END;
/