CREATE OR REPLACE PROCEDURE EO_WORKSSUPPORT_SEL_ID
/*
	CREATED BY	:	TRÝÕNG HOÀNG NHI
	DATE		:	02/08/2017
	DESCRIPTION	:	N?P THÔNG TIN CÔNG VI?C C?N H? TR? 
*/ (
    V_WORKSSUPPORTID   IN EO_WORKSSUPPORT.WORKSSUPPORTID%TYPE,
    V_OUT              OUT SYS_REFCURSOR
)
    AS
BEGIN
    OPEN V_OUT FOR
         SELECT
            EO_WORKSSUPPORT.WORKSSUPPORTID,
            EO_WORKSSUPPORT.WORKSSUPPORTNAME,
            EO_WORKSSUPPORT.CREATEDDATE,
            EO_WORKSSUPPORT.CURRENTPROGRESS,
            EO_WORKSSUPPORT.EXPECTEDCOMPLETEDDATE,
            EO_WORKSSUPPORT.COMPLETEDDATE,
            EO_WORKSSUPPORT.CONTENT,
            EO_WORKSSUPPORT.WORKSSUPPORTPRIORITYID,            
            EO_WORKSSUPPORT.ATTACHMENTFILECOUNT
        FROM
            EO_WORKSSUPPORT
        WHERE
            EO_WORKSSUPPORT.WORKSSUPPORTID = V_WORKSSUPPORTID
        AND
            EO_WORKSSUPPORT.ISDELETED = 0;

END;