CREATE OR REPLACE PROCEDURE ERP.EO_WORKSSUPPORTTYPE_WF_DEL
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	02/03/2013
	DESCRIPTION	:	XÓA THÔNG TIN BUOC XU LY CÔNG VI?C C?N H? TR? 
*/ (
    V_WORKSSUPPORTTYPEID   IN EO_WORKSSUPPORTTYPE_WORKFLOW.WORKSSUPPORTTYPEID%TYPE
)
    AS
BEGIN
    DELETE EO_WORKSSUPPORTTYPE_WORKFLOW WHERE
        WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID;
END;
/