create or replace PROCEDURE EO_WORKSSUPPORT_WORKS_V2_ADD
/*
	CREATED BY	:	TRUONG HOANG NHI
	DATE		:	02/08/2017
	DESCRIPTION	:	THÊM THÔNG TIN CÔNG VI?C LIÊN QUAN
*/ (
    V_WORKSSUPPORTID         IN EO_WORKSSUPPORT_WORKS.WORKSSUPPORTID%TYPE,
    V_WORKSID      IN EO_WORKSSUPPORT_WORKS.WORKSID%TYPE
) AS
BEGIN

    INSERT INTO EO_WORKSSUPPORT_WORKS (
        WORKSSUPPORTID,
        WORKSID        
    ) VALUES (
        V_WORKSSUPPORTID,
        V_WORKSID
    );
END;