CREATE OR REPLACE PROCEDURE ERP.EO_WORKSSUPPORTPROJECT_BYID
/*
	CREATED BY	:	Truong Hoang Nhi
	DATE		:	30/08/2017
	DESCRIPTION	:	N?P THÔNG TIN B?NG LIÊN K?T LO?I CÔNG VI?C VÀ Ð? UU TIÊN CÔNG VI?C
*/
(	
	V_WORKSSUPPORTPROJECTID IN EO_WORKSSUPPORTPROJECT.WORKSSUPPORTPROJECTID%TYPE,	
	V_OUT OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN V_OUT FOR
	SELECT
    WORKSSUPPORTPRIORITY.WORKSSUPPORTPRIORITYID,
    WORKSSUPPORTPRIORITY.WORKSSUPPORTPRIORITYNAME
FROM  
    EO_WORKSSUPPORTPRIORITY WORKSSUPPORTPRIORITY
WHERE 
WORKSSUPPORTPRIORITY.WORKSSUPPORTPRIORITYID  IN (
    SELECT 
        PRIORITY.WORKSSUPPORTPRIORITYID
    FROM 
        EO_WORKSSUPPORTTYPE_PRIORITY PRIORITY
        INNER JOIN 
        EO_WORKSSUPPORTPROJECT PRTPROJECT
        ON PRIORITY.WORKSSUPPORTTYPEID = PRTPROJECT.WORKSSUPPORTTYPEID
        WHERE
            PRTPROJECT.WORKSSUPPORTPROJECTID = V_WORKSSUPPORTPROJECTID
);
END;
/