create or replace PROCEDURE     EO_WORKSSUPPORTTYPE_WF_P_DEL
/*
	CREATED BY	:	LÝÕNG TRUNG NHÂN 
	DATE		:	12/06/2017
	DESCRIPTION	:	XÓA THÔNG TIN B?NG CH?A QUY?N TRÊN CÁC BÝ?C X? L? K? TI?P THEO
*/
(
	V_WORKSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE_WF_PERMIS.WORKSSUPPORTSTEPID%TYPE
)
AS
BEGIN
--	DELETE EO_WORKSSUPPORTTYPE_WF_PERMIS
--	WHERE
--    WORKSSUPPORTSTEPID = V_WORKSSUPPORTSTEPID
--    AND
--    WORKSSUPPORTMEMBERROLEID = V_WORKSSUPPORTMEMBERROLEID;
    
    DELETE 
        EO_WORKSSUPPORTTYPE_WF_PERMIS
    WHERE
        WORKSSUPPORTSTEPID IN (
    SELECT
        PERMIS.WORKSSUPPORTSTEPID
    FROM 
        EO_WORKSSUPPORTTYPE_WF_PERMIS PERMIS
        INNER JOIN
        EO_WORKSSUPPORTTYPE_WORKFLOW WORKFLOW
        ON
        PERMIS.WORKSSUPPORTSTEPID = WORKFLOW.WORKSSUPPORTSTEPID
    WHERE 
        WORKFLOW.WORKSSUPPORTTYPEID = V_WORKSUPPORTTYPEID
);
END;