CREATE OR REPLACE PROCEDURE ERP.EO_WORKSSUPPORTTYPE_Q_ADD
/*
	CREATED BY	:	LUONG TRUNG NHÂN 
	DATE		:	02/06/2017
	DESCRIPTION	:	THÊM THÔNG TIN B?NG LIÊN K?T LO?I CÔNG VI?C VÀ CH?T LU?NG CÔNG VI?C
*/
(
	V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE_QUALITY.WORKSSUPPORTTYPEID%TYPE,
	V_WORKSSUPPORTQUALITYID IN EO_WORKSSUPPORTTYPE_QUALITY.WORKSSUPPORTQUALITYID%TYPE
)
AS
T_COUNT NUMBER;
BEGIN
	INSERT
	INTO EO_WORKSSUPPORTTYPE_QUALITY
	(
		WORKSSUPPORTTYPEID,
		WORKSSUPPORTQUALITYID
	)
	VALUES
	(
		V_WORKSSUPPORTTYPEID,
		V_WORKSSUPPORTQUALITYID
	);
END;
/