create or replace PROCEDURE     EO_WORKSSUPPORTTYPE_WF_UPDATE
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	02/03/2013
	DESCRIPTION	:	C?P NH?T THÔNG TIN BUOC XU LY CÔNG VI?C C?N H? TR? 
*/
(
		V_WORKSSUPPORTSTEPID IN EO_WORKSSUPPORTTYPE_WORKFLOW.WORKSSUPPORTSTEPID%TYPE,
	  V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE_WORKFLOW.WORKSSUPPORTTYPEID%TYPE,
	  V_WORKSSUPPORTSTEPNAME IN EO_WORKSSUPPORTTYPE_WORKFLOW.WORKSSUPPORTSTEPNAME%TYPE,
  	V_PROCESSFUNCTIONID IN EO_WORKSSUPPORTTYPE_WORKFLOW.PROCESSFUNCTIONID%TYPE,
  	V_STEPCOLORCODE IN EO_WORKSSUPPORTTYPE_WORKFLOW.STEPCOLORCODE%TYPE,
  	V_MAXPROCESSTIME IN EO_WORKSSUPPORTTYPE_WORKFLOW.MAXPROCESSTIME%TYPE,
  	V_ISINITSTEP IN EO_WORKSSUPPORTTYPE_WORKFLOW.ISINITSTEP%TYPE,
  	V_ISFINISHSTEP IN EO_WORKSSUPPORTTYPE_WORKFLOW.ISFINISHSTEP%TYPE,
  	V_ISMUSTCHOOSEPROCESSUSER IN EO_WORKSSUPPORTTYPE_WORKFLOW.ISMUSTCHOOSEPROCESSUSER%TYPE,
  	V_AUTOCHANGETOSTATUSID IN EO_WORKSSUPPORTTYPE_WORKFLOW.AUTOCHANGETOSTATUSID%TYPE,
  	V_DESCRIPTION IN EO_WORKSSUPPORTTYPE_WORKFLOW.DESCRIPTION%TYPE,
    V_ORDERINDEX IN EO_WORKSSUPPORTTYPE_WORKFLOW.ORDERINDEX%TYPE,
    V_ISACTIVE IN EO_WORKSSUPPORTTYPE_WORKFLOW.ISACTIVE%TYPE,
    V_ISSYSTEM IN EO_WORKSSUPPORTTYPE_WORKFLOW.ISSYSTEM%TYPE,
    V_UPDATEDUSER IN EO_WORKSSUPPORTTYPE_WORKFLOW.UPDATEDUSER%TYPE,
    V_ISCANMODIFIEDCONTENT IN EO_WORKSSUPPORTTYPE_WORKFLOW.ISCANMODIFIEDCONTENT%TYPE,
    V_ISCANMODIFIEDCONTENTSOLUTION IN EO_WORKSSUPPORTTYPE_WORKFLOW.ISCANMODIFIEDCONTENTSOLUTION%TYPE,
    V_ISCANMODIFIEDCOMPLETEDDATE IN EO_WORKSSUPPORTTYPE_WORKFLOW.ISCANMODIFIEDCOMPLETEDDATE%TYPE,
    V_ISCANATTACH IN EO_WORKSSUPPORTTYPE_WORKFLOW.ISCANATTACH%TYPE,
    --V_ISCANATTACH IN EO_WORKSSUPPORTTYPE_WORKFLOW.ISCANATTACH%TYPE,
    V_ISCANCOMMENT IN EO_WORKSSUPPORTTYPE_WORKFLOW.ISCANCOMMENT%TYPE,
    V_ISCANUPDATEPROCESS IN EO_WORKSSUPPORTTYPE_WORKFLOW.ISCANUPDATEPROCESS%TYPE,
    V_ISCANUPDATEQUALITY IN EO_WORKSSUPPORTTYPE_WORKFLOW.ISCANUPDATEQUALITY%TYPE,
    V_WORKSSUPPORTSTATUSID IN EO_WORKSSUPPORTTYPE_WORKFLOW.WORKSSUPPORTSTATUSID%TYPE,
    V_WORKSSUPPORTSTEPPROGRESS IN EO_WORKSSUPPORTTYPE_WORKFLOW.WORKSSUPPORTSTEPPROGRESS%TYPE
) 
AS
BEGIN
	UPDATE EO_WORKSSUPPORTTYPE_WORKFLOW
	SET
	 WORKSSUPPORTSTEPID= V_WORKSSUPPORTSTEPID,
  WORKSSUPPORTTYPEID= V_WORKSSUPPORTTYPEID,
  WORKSSUPPORTSTEPNAME= V_WORKSSUPPORTSTEPNAME,
  PROCESSFUNCTIONID= V_PROCESSFUNCTIONID,
  STEPCOLORCODE= V_STEPCOLORCODE,
  MAXPROCESSTIME= V_MAXPROCESSTIME,
  ISINITSTEP= V_ISINITSTEP,
  ISFINISHSTEP= V_ISFINISHSTEP,
  ISMUSTCHOOSEPROCESSUSER= V_ISMUSTCHOOSEPROCESSUSER,
  AUTOCHANGETOSTATUSID= V_AUTOCHANGETOSTATUSID ,
  DESCRIPTION= V_DESCRIPTION,
  ORDERINDEX= V_ORDERINDEX,
  ISACTIVE= V_ISACTIVE ,
  ISSYSTEM = V_ISSYSTEM,
  UPDATEDUSER= V_UPDATEDUSER,
  UPDATEDDATE=SYSDATE,
  ISCANMODIFIEDCONTENT= V_ISCANMODIFIEDCONTENT,
  ISCANMODIFIEDCONTENTSOLUTION= V_ISCANMODIFIEDCONTENTSOLUTION,
  ISCANMODIFIEDCOMPLETEDDATE= V_ISCANMODIFIEDCOMPLETEDDATE,
  ISCANATTACH= V_ISCANATTACH,
  ISCANCOMMENT= V_ISCANCOMMENT,
  ISCANUPDATEPROCESS= V_ISCANUPDATEPROCESS,
  ISCANUPDATEQUALITY= V_ISCANUPDATEQUALITY,
  WORKSSUPPORTSTATUSID = V_WORKSSUPPORTSTATUSID,
  WORKSSUPPORTSTEPPROGRESS = V_WORKSSUPPORTSTEPPROGRESS
	WHERE
		WORKSSUPPORTSTEPID = V_WORKSSUPPORTSTEPID
    AND WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID
;
END;