create or replace PROCEDURE  EO_WORKSSUPPORT_WORKS_DEL
/*
	Created by	:	Truong Hoang Nhi
	Date		:	05/08/2017
	Description	:	Xóa các công vi?c liên quan.
*/
(
	V_WORKSSUPPORTID IN EO_WORKSSUPPORT_WORKS.WORKSSUPPORTID%TYPE,
    V_WORKSID IN EO_WORKSSUPPORT_WORKS.WORKSID%TYPE    
)
AS
BEGIN
	DELETE 
        EO_WORKSSUPPORT_WORKS
	WHERE
		WORKSSUPPORTID = V_WORKSSUPPORTID
    AND
    WORKSID = V_WORKSID;
END;