create or replace PROCEDURE EO_WORKSSUPPORTTYPE_WF_DELBYID
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	02/03/2013
	DESCRIPTION	:	XÓA THÔNG TIN BUOC XU LY CÔNG VI?C C?N H? TR? 
*/ (
    V_WORKSSUPPORTSTATUSID   IN EO_WORKSSUPPORTTYPE_WORKFLOW.WORKSSUPPORTSTATUSID%TYPE
)
    AS
BEGIN
    DELETE EO_WORKSSUPPORTTYPE_WORKFLOW WHERE
        WORKSSUPPORTSTATUSID = V_WORKSSUPPORTSTATUSID;
END;