CREATE OR REPLACE PROCEDURE ERP.EO_WORKSSUPPORT_REPEXC
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:19/06/2017
	DESCRIPTION	:	N?P DANH SÁCH CÔNG VI?C C?N H? TR? 
*/
(
    V_OUT OUT SYS_REFCURSOR,
   V_PROJECT IN NUMBER DEFAULT -1
) 
AS
  T_COUNTGROUP NUMBER := 0;
  T_COUNTWORKS NUMBER := 0;
  T_COUNTPERSON NUMBER := 0;
  T_COUNTKT NUMBER:=0;
  T_COUNTXL NUMBER:=0;
  
BEGIN
  BEGIN
    -- TONG NHOM TRONG DU AN
    SELECT COUNT(1) INTO T_COUNTGROUP 
    FROM EO_WORKSSUPPORTGROUP WGROUP 
    WHERE 
      WGROUP.WORKSSUPPORTPROJECTID = V_PROJECT AND
      WGROUP.ISDELETED =0;

  END;
  
  -- TONG CONG VIEC TRONG DU AN
  BEGIN

    SELECT COUNT(1) INTO T_COUNTWORKS
      FROM EO_WORKSSUPPORT SUPPORT
    WHERE EXISTS (SELECT 1 
                      FROM EO_WORKSSUPPORTGROUP WGROUP
                      WHERE WGROUP.WORKSSUPPORTPROJECTID = V_PROJECT AND WGROUP.ISDELETED =0
                            AND WGROUP.WORKSSUPPORTGROUPID = SUPPORT.WORKSSUPPORTGROUPID
                            AND SUPPORT.ISDELETED = 0 );
  END;
-- TONG NHAN LUC TRONG DU AN
  BEGIN 
     SELECT COUNT(1) INTO T_COUNTPERSON
      FROM EO_WORKSSUPPORTPROJECT_MEMBER PROJECT_MEMBER
      WHERE PROJECT_MEMBER.WORKSSUPPORTPROJECTID = V_PROJECT;
     
  END;
    -- TRANG THAI
--  BEGIN
--    SELECT STATUS.ISINITSTATUS,STATUS.ISCOMPLETESTATUS,SUPPORT.COMPLETEDDATE,SUPPORT.EXPECTEDCOMPLETEDDATE,
--      CASE 
--  WHEN STATUS.ISINITSTATUS = 1 THEN  '0' 
--  WHEN STATUS.ISINITSTATUS = 0 AND
--      STATUS.ISCOMPLETESTATUS = 0 AND 
--      SUPPORT.COMPLETEDDATE <= SUPPORT.EXPECTEDCOMPLETEDDATE
--           THEN '0' 
--  WHEN STATUS.ISCOMPLETESTATUS =1 THEN '0' 
--  WHEN SUPPORT.COMPLETEDDATE > SUPPORT.EXPECTEDCOMPLETEDDATE AND STATUS.ISCOMPLETESTATUS = 0 THEN '0' 
--    END INTO 
--
--      FROM EO_WORKSSUPPORT SUPPORT
--      JOIN EO_WORKSSUPPORTSTATUS STATUS
--            ON STATUS.WORKSSUPPORTSTATUSID = SUPPORT.WORKSSUPPORTSTATUSID
--
--       WHERE EXISTS (SELECT 1
--                      FROM EO_WORKSSUPPORTGROUP WGROUP
--                      WHERE WGROUP.WORKSSUPPORTGROUPID = SUPPORT.WORKSSUPPORTGROUPID
--                      AND WGROUP.WORKSSUPPORTPROJECTID = V_PROJECT
--                      AND SUPPORT.ISDELETED = 0 );
--    
--  END;
 BEGIN 
     SELECT COUNT(1) INTO T_COUNTKT
      FROM EO_WORKSSUPPORT SUPPORT
       JOIN EO_WORKSSUPPORTSTATUS STATUS
           ON STATUS.WORKSSUPPORTSTATUSID = SUPPORT.WORKSSUPPORTSTATUSID
      WHERE EXISTS (SELECT 1
                      FROM EO_WORKSSUPPORTGROUP WGROUP
                      WHERE WGROUP.WORKSSUPPORTGROUPID = SUPPORT.WORKSSUPPORTGROUPID
                      AND WGROUP.WORKSSUPPORTPROJECTID = V_PROJECT
                      AND SUPPORT.ISDELETED = 0 )and STATUS.ISINITSTATUS = 1;
     
  END;

   BEGIN 
     SELECT COUNT(1) INTO T_COUNTXL
      FROM EO_WORKSSUPPORT SUPPORT
       JOIN EO_WORKSSUPPORTSTATUS STATUS
           ON STATUS.WORKSSUPPORTSTATUSID = SUPPORT.WORKSSUPPORTSTATUSID
      WHERE EXISTS (SELECT 1
                      FROM EO_WORKSSUPPORTGROUP WGROUP
                      WHERE WGROUP.WORKSSUPPORTGROUPID = SUPPORT.WORKSSUPPORTGROUPID
                      AND WGROUP.WORKSSUPPORTPROJECTID = V_PROJECT
                      AND SUPPORT.ISDELETED = 0 ) 
                   AND STATUS.ISINITSTATUS = 0 AND STATUS.ISCOMPLETESTATUS = 0 
                   AND SUPPORT.COMPLETEDDATE <= SUPPORT.EXPECTEDCOMPLETEDDATE;
  END;

  -- TONG CONG VIEC TRONG NHOM
  
  OPEN V_OUT FOR
  SELECT 
    T_COUNTGROUP AS SUMGROUP, 
    T_COUNTWORKS AS SUMWORKS, 
    T_COUNTPERSON AS SUMPERSON,
    T_COUNTKT AS SUMKT,
    T_COUNTXL AS SUMXL

  FROM DUAL D;
  RETURN;   

END;
/