create or replace PROCEDURE     EO_WORKSSUPPORTTYPE_M_SEL
/*
	CREATED BY	:	LÝÕNG TRUNG NHÂN
	DATE		:	07/06/2017
	DESCRIPTION	:	N?P THÔNG TIN QUY?N THEO VAI TR?
*/
(	
	V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE_MEMBERROLE.WORKSSUPPORTTYPEID%TYPE,	
	V_OUT OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN V_OUT FOR
	SELECT 
  WORKSSUPPORTTYPEID,
  EO_WORKSSUPPORTTYPE_MEMBERROLE.WORKSSUPPORTMEMBERROLEID,
  EO_WORKSSUPPORTMEMBERROLE.WORKSSUPPORTMEMBERROLENAME,
  ISCANADDWORKSSUPPORTGROUP,
  ISCANADDWORKSSUPPORT,
  ISCANEDITWORKSSUPPORT,
  ISCANEDITWORKSSUPPORTGROUP,
  ISCANDELETEWORKSSUPPORTGROUP,
  ISCANDELETEWORKSSUPPORT,
  ISDEFAULTROLE
	FROM 
    EO_WORKSSUPPORTTYPE_MEMBERROLE
  LEFT JOIN EO_WORKSSUPPORTMEMBERROLE
    ON EO_WORKSSUPPORTTYPE_MEMBERROLE.WORKSSUPPORTMEMBERROLEID = EO_WORKSSUPPORTMEMBERROLE.WORKSSUPPORTMEMBERROLEID
	WHERE
		WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID
;
END;