create or replace PROCEDURE     EO_WORKSSUPPORTTYPE_M_UPD
/*
	CREATED BY	:	LÝÕNG TRUNG NHÂN
	DATE		:	12/06/2017
	DESCRIPTION	:	C?P NH?T THÔNG TIN VAI TR? C?A M?T CÔNG VI?C C?N H? TR?
*/
(
	V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE_MEMBERROLE.WORKSSUPPORTTYPEID%TYPE,
	V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORTTYPE_MEMBERROLE.WORKSSUPPORTMEMBERROLEID%TYPE,
  V_ISCANADDWORKSSUPPORTGROUP IN EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANADDWORKSSUPPORTGROUP%TYPE,
	V_ISCANADDWORKSSUPPORT IN EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANADDWORKSSUPPORT%TYPE,
  V_ISCANEDITWORKSSUPPORT IN EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANEDITWORKSSUPPORT%TYPE,
  V_ISCANEDITWORKSSUPPORTGROUP IN EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANEDITWORKSSUPPORTGROUP%TYPE,
  V_ISCANDELETEWORKSSUPPORTGROUP IN EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANDELETEWORKSSUPPORTGROUP%TYPE,
  V_ISCANDELETEWORKSSUPPORT IN EO_WORKSSUPPORTTYPE_MEMBERROLE.ISCANDELETEWORKSSUPPORT%TYPE
)
AS
BEGIN
	UPDATE EO_WORKSSUPPORTTYPE_MEMBERROLE
	SET
      WORKSSUPPORTMEMBERROLEID= V_WORKSSUPPORTMEMBERROLEID,
      ISCANADDWORKSSUPPORTGROUP= V_ISCANADDWORKSSUPPORTGROUP,
      ISCANADDWORKSSUPPORT= V_ISCANADDWORKSSUPPORT,
      ISCANEDITWORKSSUPPORT= V_ISCANEDITWORKSSUPPORT,
      ISCANEDITWORKSSUPPORTGROUP= V_ISCANEDITWORKSSUPPORTGROUP,
      ISCANDELETEWORKSSUPPORTGROUP= V_ISCANDELETEWORKSSUPPORTGROUP,
      ISCANDELETEWORKSSUPPORT= V_ISCANDELETEWORKSSUPPORT
  WHERE
		WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID
  ;
END;
