create or replace PROCEDURE  SOLUTION_ATTACHMENT_DELWORKID
/*
	CREATED BY	:	LÝÕNG TRUNG NHÂN 
	DATE		:	21/06/2017
	DESCRIPTION	:	XÓA THÔNG TIN DANH SÁCH FILE DÍNH KÈM C?A CÔNG VI?C C?N H? TR? 
*/
(
	V_WORKSSUPPORTID IN EO_WORKSSUPPORT_SOLUTIONATM.WORKSSUPPORTID%TYPE,
	V_DELETEDUSER IN EO_WORKSSUPPORT_SOLUTIONATM.DELETEDUSER%TYPE
)
AS
BEGIN
	UPDATE EO_WORKSSUPPORT_SOLUTIONATM
	SET
		ISDELETED = 1,
		DELETEDDATE = SYSDATE,
		DELETEDUSER = V_DELETEDUSER
	WHERE
		WORKSSUPPORTID = V_WORKSSUPPORTID;
END;