CREATE OR REPLACE PROCEDURE ERP.SYS_DEPARTMENT_MEMBERS_SRH
/*
	CREATED BY	:	NGUYEN VAN HUAN
	DATE		:	18/07/2012
	DESCRIPTION	:	NAP DANH SACH NHAN VIEN CUA CC PHONG BAN  
*/
(
    V_OUT OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN V_OUT FOR
	SELECT
		SYS_DEPARTMENT.DEPARTMENTID,
		SYS_DEPARTMENT.DEPARTMENTNAME,
    SYS_USER.USERNAME,
    SYS_USER.FULLNAME
	FROM 
    SYS_DEPARTMENT
    LEFT JOIN SYS_USER
        ON SYS_USER.DEPARTMENTID = SYS_DEPARTMENT.DEPARTMENTID AND SYS_USER.ISDELETED =0
	WHERE 
  SYS_DEPARTMENT.ISDELETED = 0 AND  SYS_DEPARTMENT.ISACTIVE = 1
  ORDER BY SYS_DEPARTMENT.DEPARTMENTNAME ASC ;
 
END;
/