create or replace PROCEDURE     WORKSSUPPORTQUALITY_V2_SEL
/*
	Created by	:	LÝÕNG TRUNG NHÂN 
	Date		:	30/05/2017
	Description	:	N?p thông tin Tr?ng thái công vi?c c?n h? tr? 
*/
(	
	v_WORKSSUPPORTQUALITYID IN EO_WORKSSUPPORTQUALITY.WORKSSUPPORTQUALITYID%type,	
	v_Out OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN v_Out FOR
	SELECT
		WORKSSUPPORTQUALITYID,
		WORKSSUPPORTQUALITYNAME,
		DESCRIPTION,
        ICONURL,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM
	FROM 
    EO_WORKSSUPPORTQUALITY
	WHERE
		WORKSSUPPORTQUALITYID = v_WORKSSUPPORTQUALITYID
;
END;
