CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORT_V2_SHRMEMBER
/*
  CREATED BY: NGUYEN THI KIM NGAN
	DATE:	31/02/2017
	DESC: LOAD DANH SÁCH NGUOI THUC HIEN THEO NHOM CONG VIEC , DU AN

*/
(
    V_OUT OUT SYS_REFCURSOR,
    V_WORKSSUPPORTGROUPID IN NVARCHAR2 DEFAULT -1
) 
AS 
BEGIN
  OPEN V_OUT FOR
      SELECT 
        GROUP_MEMBER.MEMBERUSERNAME,
        GROUP_MEMBER.WORKSSUPPORTGROUPID,
        GROUP_MEMBER.ISAUTOADDMEMBERTOWORKSSUPPORT

      FROM EO_WORKSSUPPORTGROUP_MEMBER GROUP_MEMBER 
      WHERE GROUP_MEMBER.WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID
        AND GROUP_MEMBER.ISDELETED = 0;
END;
/