CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORT_MEMBER_DEL
/*
	Created by	:	Luong Trung Nhân 
	Date		:	21/06/2017
	Description	:	Xóa thông tin  
*/
(
  v_WORKSSUPPORTID IN EO_WORKSSUPPORT_MEMBER.WORKSSUPPORTID%TYPE,
	v_DELETEDUSER IN EO_WORKSSUPPORT_MEMBER.DELETEDUSER%TYPE
)
AS
BEGIN
	UPDATE EO_WORKSSUPPORT_MEMBER
	SET
		ISDELETED = 1,
		DELETEDDATE = SYSDATE,
		DELETEDUSER = v_DELETEDUSER
	WHERE (v_WORKSSUPPORTID  <=0 OR WORKSSUPPORTID = v_WORKSSUPPORTID)
    ;
END;
/