CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTQUALITY_V2_SRH
/*
	CREATED BY	:	LUONG TRUNG NHÂN 
	DATE		:	30/05/2017
	DESCRIPTION	:	N?P DANH SÁCH CH?T LU?NG CÔNG VI?C C?N H? TR?
  UPDATE BY :NGUY?N TH? KIM NGÂN
  DATE : 06.06.2017
  DESCRIPTION: THÊM PHÂN TRANG
*/
(
    V_OUT OUT SYS_REFCURSOR,
    V_KEYWORDS NVARCHAR2 DEFAULT NULL,
    V_ISDELETED EO_WORKSSUPPORTQUALITY.ISDELETED%TYPE DEFAULT 0,
    V_PAGEINDEX NUMBER DEFAULT -1,
    V_PAGESIZE NUMBER DEFAULT -1
) 
AS
BEGIN
  OPEN V_OUT FOR
   SELECT * 
    FROM(
	SELECT
		EO_WORKSSUPPORTQUALITY.WORKSSUPPORTQUALITYID,
		EO_WORKSSUPPORTQUALITY.WORKSSUPPORTQUALITYNAME,
		EO_WORKSSUPPORTQUALITY.DESCRIPTION,
    EO_WORKSSUPPORTQUALITY.ICONURL,
    EO_WORKSSUPPORTQUALITY.COLORCODE,
		EO_WORKSSUPPORTQUALITY.ORDERINDEX,
		EO_WORKSSUPPORTQUALITY.ISACTIVE,
		EO_WORKSSUPPORTQUALITY.ISSYSTEM,
		NVL2(EO_WORKSSUPPORTQUALITY.CREATEDUSER,	EO_WORKSSUPPORTQUALITY.CREATEDUSER ||'-'||CREATEDUSER.FULLNAME,'') CREATEDUSER,
		EO_WORKSSUPPORTQUALITY.CREATEDDATE,
		NVL2( EO_WORKSSUPPORTQUALITY.UPDATEDUSER,EO_WORKSSUPPORTQUALITY.UPDATEDUSER ||'-'||UPDATEDUSER.FULLNAME,'') UPDATEDUSER,
		EO_WORKSSUPPORTQUALITY.UPDATEDDATE,
		EO_WORKSSUPPORTQUALITY.ISDELETED,
		EO_WORKSSUPPORTQUALITY.DELETEDUSER,
		EO_WORKSSUPPORTQUALITY.DELETEDDATE,
    ROW_NUMBER() OVER (ORDER BY EO_WORKSSUPPORTQUALITY.ORDERINDEX ASC ,EO_WORKSSUPPORTQUALITY.CREATEDDATE DESC) STT,
    SUM(1) OVER()AS TOTALROWS
	FROM 
    EO_WORKSSUPPORTQUALITY
    LEFT  JOIN SYS_USER CREATEDUSER 
      ON CREATEDUSER.USERNAME = EO_WORKSSUPPORTQUALITY.CREATEDUSER
    LEFT  JOIN SYS_USER UPDATEDUSER 
      ON UPDATEDUSER.USERNAME = EO_WORKSSUPPORTQUALITY.UPDATEDUSER
	WHERE 
    EO_WORKSSUPPORTQUALITY.ISDELETED = V_ISDELETED
    AND (V_KEYWORDS IS NULL 
         OR UPPER ( EO_WORKSSUPPORTQUALITY.WORKSSUPPORTQUALITYNAME ) LIKE '%' ||UPPER ( V_KEYWORDS )|| '%')
  ORDER BY 
    EO_WORKSSUPPORTQUALITY.ORDERINDEX
  )
  WHERE
  V_PAGESIZE < 0 
  OR
  (STT > V_PAGEINDEX * V_PAGESIZE AND STT <= (V_PAGEINDEX + 1) * V_PAGESIZE);
END;
/