CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTTYPE_V2_GETBYUSER
/*
	AUTHOR	      :	NGUYEN VAN HUAN
	DATE CREATED  :	JULY, 29, 2017
	DESCRIPTION   :	LOAD ALL WORKSSUPPORTTYPE BY USERNAME
*/
(	
  V_OUT OUT SYS_REFCURSOR,
  V_USERNAME IN EO_WORKSSUPPORTPROJECT.WORKSSUPPORTPROJECTNAME%TYPE
) 
AS
BEGIN
  IF(lower(v_username) = lower('administrator')) THEN
    BEGIN
      OPEN V_OUT FOR
      SELECT
        EW.WORKSSUPPORTTYPEID,
        EW.WORKSSUPPORTTYPENAME,
        1 AS ISCANADDPROJECT,
        1 AS ISCANEDITPROJECT,
        ( SELECT COUNT(1) 
          FROM EO_WORKSSUPPORTTYPE_MEMBERROLE EWM
          WHERE EWM.WORKSSUPPORTTYPEID = EW.WORKSSUPPORTTYPEID)
          AS ISDEFAULTROLE
      FROM
        EO_WORKSSUPPORTTYPE EW     
      WHERE
         EW.ISDELETED = 0 AND EW.ISACTIVE = 1 
        ORDER BY EW.ORDERINDEX ASC;
    END;  
  ELSE 
    BEGIN
      OPEN V_OUT FOR
        SELECT
          EW.WORKSSUPPORTTYPEID,
          EW.WORKSSUPPORTTYPENAME,
          EWP.ISCANADDPROJECT,
          EWP.ISCANEDITPROJECT,
          ( SELECT COUNT(1) 
            FROM EO_WORKSSUPPORTTYPE_MEMBERROLE EWM
            WHERE EWM.WORKSSUPPORTTYPEID = EW.WORKSSUPPORTTYPEID)
            AS ISDEFAULTROLE
        FROM
          EO_WORKSSUPPORTPROJECT_PERMIS EWP, EO_WORKSSUPPORTTYPE EW
        WHERE
          EW.WORKSSUPPORTTYPEID = EWP.WORKSSUPPORTTYPEID AND 
          EWP.USERNAME = V_USERNAME AND  EW.ISDELETED = 0 AND EW.ISACTIVE = 1 
          ORDER BY EW.ORDERINDEX ASC;
    END;
  END IF;
END;
/