CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTSTATUS_V2_ADD
/*
	CREATED BY	:	HOÀNG NHU PHONG 
	DATE		:	02/03/2013
	DESCRIPTION	:	THÊM THÔNG TIN TR¿NG THÁI CÔNG VI¿C C¿N H¿ TR¿ 
  	EDIT BY	:	NGUY¿N TU¿N ANH 
	DATE		:	13/06/2017
	DESCRIPTION	:	H¿Y THÊM TRU¿NG WORKSSUPPORTSTATUSID
*/
(
	--V_WORKSSUPPORTSTATUSID IN EO_WORKSSUPPORTSTATUS.WORKSSUPPORTSTATUSID%TYPE,
	V_WORKSSUPPORTSTATUSNAME IN EO_WORKSSUPPORTSTATUS.WORKSSUPPORTSTATUSNAME%TYPE,
	V_ICONURL IN EO_WORKSSUPPORTSTATUS.ICONURL%TYPE,
  V_COLORCODE IN EO_WORKSSUPPORTSTATUS.COLORCODE%TYPE,
	V_ISINITSTATUS IN EO_WORKSSUPPORTSTATUS.ISINITSTATUS%TYPE,
	V_ISCOMPLETESTATUS IN EO_WORKSSUPPORTSTATUS.ISCOMPLETESTATUS%TYPE,
	V_DESCRIPTION IN EO_WORKSSUPPORTSTATUS.DESCRIPTION%TYPE,
	V_ORDERINDEX IN EO_WORKSSUPPORTSTATUS.ORDERINDEX%TYPE,
	V_ISACTIVE IN EO_WORKSSUPPORTSTATUS.ISACTIVE%TYPE,
	V_ISSYSTEM IN EO_WORKSSUPPORTSTATUS.ISSYSTEM%TYPE,
	V_CREATEDUSER IN EO_WORKSSUPPORTSTATUS.CREATEDUSER%TYPE,
  V_ISCLOSESTATUS IN EO_WORKSSUPPORTSTATUS.ISCLOSESTATUS%TYPE,
	V_CERTIFICATESTRING IN EO_WORKSSUPPORTSTATUS_LOG.CERTIFICATESTRING%TYPE,
	V_USERHOSTADDRESS IN EO_WORKSSUPPORTSTATUS_LOG.USERHOSTADDRESS%TYPE,
	V_LOGINLOGID IN EO_WORKSSUPPORTSTATUS_LOG.LOGINLOGID%TYPE,
  V_OUT OUT NUMBER
)
AS
T_ORDERINDEX EO_WORKSSUPPORTSTATUS.ORDERINDEX%TYPE;
--T_COUNT NUMBER;
--T_ORDERINDEX EO_WORKSSUPPORTSTATUS.ORDERINDEX%TYPE;
--WORKSTATUSID INT:=0;
BEGIN
  --BEGIN 
    SELECT COUNT(*)+1 INTO T_ORDERINDEX 
    FROM 
         EO_WORKSSUPPORTSTATUS
    WHERE ISDELETED = 0;
    --SELECT COUNT(ORDERINDEX) INTO T_COUNT FROM EO_WORKSSUPPORTSTATUS  ;
--    SELECT COUNT(*) INTO T_ORDERINDEX 
--    FROM 
--      EO_WORKSSUPPORTSTATUS  
--     WHERE ISDELETED = 0;
    --EXCEPTION WHEN OTHERS THEN T_COUNT:=0;
  --END; 
-- cap nhat lai trang thai bat dau 
 IF V_ISINITSTATUS = 1 THEN 
    UPDATE EO_WORKSSUPPORTSTATUS EO 
       SET ISINITSTATUS = 0
     WHERE     ISINITSTATUS = 1 
           AND EO.ISINITSTATUS = V_ISINITSTATUS 
           AND EO.ISDELETED = 0 ;
  END IF;
 -- cap nhat lai tran thai hoan thanh
  IF V_ISCOMPLETESTATUS = 1 THEN 
    UPDATE EO_WORKSSUPPORTSTATUS EO 
       SET ISCOMPLETESTATUS = 0
     WHERE     ISCOMPLETESTATUS = 1 
           AND EO.ISCOMPLETESTATUS = V_ISCOMPLETESTATUS 
           AND EO.ISDELETED = 0;
  END IF;
 -- cap nhat lai trang thai ket thuc
 IF V_ISCLOSESTATUS = 1 THEN 
    UPDATE EO_WORKSSUPPORTSTATUS EO 
       SET ISCLOSESTATUS = 0
     WHERE     ISCLOSESTATUS = 1 
           AND EO.ISCLOSESTATUS = V_ISCLOSESTATUS
           AND EO.ISDELETED = 0;
  END IF;

	INSERT
	INTO EO_WORKSSUPPORTSTATUS
	(
--		WORKSSUPPORTSTATUSID,
		WORKSSUPPORTSTATUSNAME,
		ICONURL,
    COLORCODE,
		ISINITSTATUS,
		ISCOMPLETESTATUS,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		CREATEDUSER,
		CREATEDDATE,
    ISCLOSESTATUS
	)
	VALUES
	(
		--V_WORKSSUPPORTSTATUSID,
		V_WORKSSUPPORTSTATUSNAME,
		V_ICONURL,
    V_COLORCODE,
		V_ISINITSTATUS,
		V_ISCOMPLETESTATUS,
		V_DESCRIPTION,
  	T_ORDERINDEX,
--		T_ORDERINDEX,
		V_ISACTIVE,
		V_ISSYSTEM,
		V_CREATEDUSER,
		SYSDATE,
    V_ISCLOSESTATUS
	) RETURNING WORKSSUPPORTSTATUSID INTO V_OUT;
  

	INSERT 
	INTO EO_WORKSSUPPORTSTATUS_LOG
	(
		--WORKSSUPPORTSTATUSID,
		WORKSSUPPORTSTATUSNAME,
		ICONURL,
		ISINITSTATUS,
		ISCOMPLETESTATUS,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		UPDATEDUSER,
		UPDATEDDATE,
    ISCLOSESTATUS,
		LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID   
	)
	VALUES
	(
		--T_WORKSTATUSID,
		V_WORKSSUPPORTSTATUSNAME,
		V_ICONURL,
		V_ISINITSTATUS,
		V_ISCOMPLETESTATUS,
		V_DESCRIPTION,
		--T_COUNT,
   T_ORDERINDEX,
		V_ISACTIVE,
		V_ISSYSTEM,
		V_CREATEDUSER,
		SYSDATE,
    V_ISCLOSESTATUS,
		1,
		V_USERHOSTADDRESS,
		V_CERTIFICATESTRING,
		V_LOGINLOGID

	);

END;
/