CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTGROUPMEMBER_V2_ADD
/*
	CREATED BY	:	NGUYEN VAN HUAN
	DATE		:	30.06.2017
	DESCRIPTION	:	THEM THANH VIEN VAO NHOM CONG VIEC
*/
(
  V_GROUPID IN EO_WORKSSUPPORTGROUP_MEMBER.WORKSSUPPORTGROUPID%TYPE,
  V_USERNAME IN EO_WORKSSUPPORTGROUP_MEMBER.MEMBERUSERNAME%TYPE,
	V_MEMBERROLEID IN EO_WORKSSUPPORTGROUP_MEMBER.WORKSSUPPORTMEMBERROLEID%TYPE,
	V_CREATEDUSER IN EO_WORKSSUPPORTGROUP_MEMBER.CREATEDUSER%TYPE
)
AS
T_ORDERINDEX EO_WORKSSUPPORTGROUP.ORDERINDEX%TYPE;  
BEGIN

  SELECT COUNT(*) + 1 INTO T_ORDERINDEX 
  FROM 
    EO_WORKSSUPPORTGROUP_MEMBER
  WHERE ISDELETED = 0;

	INSERT
	INTO EO_WORKSSUPPORTGROUP_MEMBER
	(
		WORKSSUPPORTGROUPID,
		MEMBERUSERNAME,
		WORKSSUPPORTMEMBERROLEID,
    ORDERINDEX,
    ISACTIVE,
    ISSYSTEM,
		CREATEDUSER,
		CREATEDDATE,
    isautoaddmembertoworkssupport,
    isdeleted
	)
	VALUES
	(
		V_GROUPID,
		V_USERNAME,
		V_MEMBERROLEID,
		T_ORDERINDEX,
		1,
		0,
		V_CREATEDUSER,
		sysdate,
    0,
    0
	);
END;
/