CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTGROUP_MEMBER_DEL
  /*
  CREATED BY: NGUYEN VAN HUAN
  DATE      : 29.6.2017
  DESCRIPTION: XOA THANH VIEN TRONG NHOM CONG VIEC
    */
(
  V_USERID ERP.EO_WORKSSUPPORTGROUP_MEMBER.MEMBERUSERNAME%TYPE,
  V_DELETEUSER ERP.EO_WORKSSUPPORTGROUP_MEMBER.DELETEDUSER%TYPE,
  V_GROUPID ERP.EO_WORKSSUPPORTGROUP_MEMBER.WORKSSUPPORTGROUPID%TYPE
  )
    AS
  BEGIN
    UPDATE EO_WORKSSUPPORTGROUP_MEMBER EWM
    SET 
      EWM.ISDELETED =1,
      EWM.DELETEDUSER = V_DELETEUSER,
      EWM.DELETEDDATE = SYSDATE 
    WHERE EWM.MEMBERUSERNAME =V_USERID AND
      EWM.WORKSSUPPORTGROUPID = V_GROUPID;   
END;
/