CREATE OR REPLACE PROCEDURE ERP.WORKSSUPORTREPORT_V2_PROJECT
 /*
	CREATED BY	:	NGUYEN VAN HUAN 
	DATE		:	02/03/2013
	DESCRIPTION	:	LAY DU AN THE QUYEN VIEW REPORT   
*/ 
(
  V_OUT OUT SYS_REFCURSOR,
  V_USERNAME IN ERP.EO_WORKSSUPPORTPROJECT_MEMBER.MEMBERUSERNAME%TYPE
)
AS
BEGIN
  IF(UPPER(V_USERNAME) = UPPER('ADMINISTRATOR')) THEN 
    OPEN V_OUT FOR
     SELECT * 
       FROM (
     SELECT  PROJECT.WORKSSUPPORTPROJECTID
            ,PROJECT.WORKSSUPPORTPROJECTNAME
            ,ROW_NUMBER() OVER (PARTITION BY PROJECT.WORKSSUPPORTPROJECTID ORDER BY PROJECT.WORKSSUPPORTPROJECTID) AS NUM 
       FROM  ERP.EO_WORKSSUPPORTPROJECT PROJECT
  LEFT JOIN  EO_WORKSSUPPORTTYPE EW
         ON      EW.WORKSSUPPORTTYPEID = PROJECT.WORKSSUPPORTPROJECTID
             AND EW.ISDELETED = 0
             AND EW.ISACTIVE = 1 
      WHERE      PROJECT.ISACTIVE = 1
             AND PROJECT.ISDELETED = 0) w_project
      WHERE  W_project.NUM = 1         
   ORDER BY  W_project.WORKSSUPPORTPROJECTNAME DESC;
  ELSE 
    OPEN V_OUT FOR
    SELECT * 
      FROM (
     SELECT  PROJECT.WORKSSUPPORTPROJECTID
            ,PROJECT.WORKSSUPPORTPROJECTNAME
            ,ROW_NUMBER() OVER (PARTITION BY PROJECT.WORKSSUPPORTPROJECTID ORDER BY PROJECT.WORKSSUPPORTPROJECTID) AS NUM 
       FROM ERP.EO_WORKSSUPPORTPROJECT PROJECT
  LEFT JOIN EO_WORKSSUPPORTTYPE EW
         ON EW.WORKSSUPPORTTYPEID = PROJECT.WORKSSUPPORTTYPEID
            AND EW.ISDELETED =0
            AND EW.ISACTIVE = 1
  LEFT JOIN EO_WORKSSUPPORTPROJECT_PERMIS EWP
         ON EWP.WORKSSUPPORTTYPEID = EW.WORKSSUPPORTTYPEID
      WHERE PROJECT.ISACTIVE = 1
            AND PROJECT.ISDELETED =0
            AND EWP.ISCANVIEWPROJECTREPORT = 1         
     ) W_project
    WHERE  W_project.NUM = 1
    ORDER BY W_project.WORKSSUPPORTPROJECTNAME DESC;
  END IF;
END;
/