CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTPROJECTMB_V2_SRH
/*
  CREATED BY :NGUY?N TH? KIM NGÂN
  DATE : 09.06.2017
  DESCRIPTION: N?P DANH SÁCH THANH VIEN CÔNG VI?C C?N H? TR? 
*/
(
    V_OUT OUT SYS_REFCURSOR,
    V_KEYWORDS NVARCHAR2 DEFAULT NULL
    --V_ISDELETED EO_WORKSSUPPORTPROJECT_MEMBER.ISDELETED%TYPE DEFAULT 0
    -- PHONG BAN
) 
AS
BEGIN
   OPEN V_OUT FOR
	SELECT
		EO_WORKSSUPPORTPROJECT_MEMBER.WORKSSUPPORTPROJECTID,
		EO_WORKSSUPPORTPROJECT_MEMBER.MEMBERUSERNAME,
		EO_WORKSSUPPORTPROJECT_MEMBER.WORKSSUPPORTMEMBERROLEID,
		EO_WORKSSUPPORTPROJECT_MEMBER.ISAUTOADDMEMBERTOWORKSGROUP,
		EO_WORKSSUPPORTPROJECT_MEMBER.DESCRIPTION,
		EO_WORKSSUPPORTPROJECT_MEMBER.ORDERINDEX,
		EO_WORKSSUPPORTPROJECT_MEMBER.ISACTIVE,
		EO_WORKSSUPPORTPROJECT_MEMBER.ISSYSTEM,
		EO_WORKSSUPPORTPROJECT_MEMBER.ISSYSTEM,
		NVL2(EO_WORKSSUPPORTPROJECT_MEMBER.CREATEDUSER,	EO_WORKSSUPPORTPROJECT_MEMBER.CREATEDUSER ||'-'||CREATEDUSER.FULLNAME,'') CREATEDUSER,
		EO_WORKSSUPPORTPROJECT_MEMBER.CREATEDDATE,
		NVL2( EO_WORKSSUPPORTPROJECT_MEMBER.UPDATEDUSER,EO_WORKSSUPPORTPROJECT_MEMBER.UPDATEDUSER ||'-'||UPDATEDUSER.FULLNAME,'') UPDATEDUSER,
		EO_WORKSSUPPORTPROJECT_MEMBER.UPDATEDDATE,
		EO_WORKSSUPPORTPROJECT_MEMBER.ISDELETED,
		EO_WORKSSUPPORTPROJECT_MEMBER.DELETEDUSER,
		EO_WORKSSUPPORTPROJECT_MEMBER.DELETEDDATE
 
	FROM 
    EO_WORKSSUPPORTPROJECT_MEMBER
    LEFT  JOIN SYS_USER CREATEDUSER 
      ON CREATEDUSER.USERNAME = EO_WORKSSUPPORTPROJECT_MEMBER.CREATEDUSER
    LEFT  JOIN SYS_USER UPDATEDUSER 
      ON UPDATEDUSER.USERNAME = EO_WORKSSUPPORTPROJECT_MEMBER.UPDATEDUSER
	WHERE 
    EO_WORKSSUPPORTPROJECT_MEMBER.ISDELETED = 0
    AND (V_KEYWORDS IS NULL 
         OR EO_WORKSSUPPORTPROJECT_MEMBER.WORKSSUPPORTMEMBERROLEID LIKE '%' || V_KEYWORDS || '%'
         OR UPPER ( EO_WORKSSUPPORTPROJECT_MEMBER.MEMBERUSERNAME ) LIKE '%' ||UPPER ( V_KEYWORDS )|| '%')
  ORDER BY 
    EO_WORKSSUPPORTPROJECT_MEMBER.ORDERINDEX;
END;
/