create or replace PROCEDURE     WORKSSUPPORTQUALITY_V2_GETALL
(
  V_OUT OUT SYS_REFCURSOR
)
AS
BEGIN
  OPEN V_OUT FOR
  SELECT
    EO_WORKSSUPPORTQUALITY.WORKSSUPPORTQUALITYID,
    EO_WORKSSUPPORTQUALITY.WORKSSUPPORTQUALITYNAME,
    EO_WORKSSUPPORTQUALITY.DESCRIPTION,
    EO_WORKSSUPPORTQUALITY.ICONURL,
    EO_WORKSSUPPORTQUALITY.ORDERINDEX,
    EO_WORKSSUPPORTQUALITY.ISACTIVE,
    EO_WORKSSUPPORTQUALITY.ISSYSTEM
  FROM
    ERP.EO_WORKSSUPPORTQUALITY
  WHERE
    --EO_WORKSSUPPORTQUALITY.ISACTIVE = 1 AND
     EO_WORKSSUPPORTQUALITY.ISDELETED = 0
  ORDER BY
    EO_WORKSSUPPORTQUALITY.ORDERINDEX
  ;
END;
