CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORT_CM_V2_SEWSID_BETA
/*
	Created by	:	Nguy?n Ðang Quang
	Date		:	5/27/2014
	Description	:	N?p thông tin Bình lu?n v? ch?ng t? di?n t? theo EFormID
*/
(	
  v_Out OUT SYS_REFCURSOR,
  v_WORKSSUPPORTID IN EO_WORKSSUPPORT_COMMENT.WORKSSUPPORTID%TYPE,	
  v_PageSize NUMBER DEFAULT 10,
  v_PageIndex NUMBER DEFAULT -1
	
) 
AS
BEGIN
    OPEN v_Out FOR
    	SELECT *
  FROM(
	SELECT
	  EO_WORKSSUPPORT_COMMENT.COMMENTID,
        EO_WORKSSUPPORT_COMMENT.WORKSSUPPORTID,
        EO_WORKSSUPPORT_COMMENT.COMMENTDATE,
        EO_WORKSSUPPORT_COMMENT.COMMENTCONTENT,
        EO_WORKSSUPPORT_COMMENT.COMMENTUSER,
        EO_WORKSSUPPORT_COMMENT.ORDERINDEX,
        EO_WORKSSUPPORT_COMMENT.ISACTIVE,
        EO_WORKSSUPPORT_COMMENT.ISSYSTEM,
        EO_WORKSSUPPORT_COMMENT.CREATEDUSER,
        EO_WORKSSUPPORT_COMMENT.CREATEDDATE,
        EO_WORKSSUPPORT_COMMENT.UPDATEDUSER,
        EO_WORKSSUPPORT_COMMENT.UPDATEDDATE,
        EO_WORKSSUPPORT_COMMENT.ISDELETED,
        EO_WORKSSUPPORT_COMMENT.DELETEDUSER,
        EO_WORKSSUPPORT_COMMENT.DELETEDDATE,
        
        SYS_USER.FULLNAME,
        SYS_POSITION.POSITIONNAME,
        SYS_DEPARTMENT.DEPARTMENTNAME,
        SYS_USER.DEFAULTPICTUREURL,
    ROW_NUMBER() OVER (ORDER BY  EO_WORKSSUPPORT_COMMENT.CREATEDDATE DESC) STT,
    SUM(1) over()AS TOTALROWS

	 FROM
        EO_WORKSSUPPORT_COMMENT
        JOIN SYS_USER
          ON LOWER(EO_WORKSSUPPORT_COMMENT.CREATEDUSER) = LOWER(SYS_USER.USERNAME)
        JOIN SYS_DEPARTMENT 
          ON SYS_USER.DEPARTMENTID = SYS_DEPARTMENT.DEPARTMENTID
       JOIN SYS_POSITION
          ON SYS_USER.POSITIONID = SYS_POSITION.POSITIONID
	WHERE
		 EO_WORKSSUPPORT_COMMENT.ISDELETED = 0
        AND EO_WORKSSUPPORT_COMMENT.WORKSSUPPORTID = v_WORKSSUPPORTID
   )
  WHERE
      (STT > v_PageIndex * v_PageSize AND STT <= (v_PageIndex + 1) * v_PageSize)
        OR v_PageIndex = -1
;
END;
/