create or replace PROCEDURE  WORKSSUPPORT_ATTACHMENT_DELID
/*
	CREATED BY	:	LÝÕNG TRUNG NHÂN 
	DATE		:	21/06/2017
	DESCRIPTION	:	XÓA THÔNG TIN DANH SÁCH FILE DÍNH KÈM C?A CÔNG VI?C C?N H? TR? 
*/
(
	V_ATTACHMENTID IN EO_WORKSSUPPORT_ATTACHMENT.ATTACHMENTID%TYPE,
	V_DELETEDUSER IN EO_WORKSSUPPORT_ATTACHMENT.DELETEDUSER%TYPE
)
AS
BEGIN
	UPDATE EO_WORKSSUPPORT_ATTACHMENT
	SET
		ISDELETED = 1,
		DELETEDDATE = SYSDATE,
		DELETEDUSER = V_DELETEDUSER
	WHERE
		ATTACHMENTID = V_ATTACHMENTID;
END;
