CREATE OR REPLACE PROCEDURE ERP.WORKS_ROJECT_V2_SHRMEMBER
/*
  CREATED BY: NGUYEN THI KIM NGAN
	DATE:	31/02/2017
	DESC: LOAD DANH SÁCH NGUOI THUC HIEN THEO DU AN

*/
(
    V_OUT OUT SYS_REFCURSOR,
    V_WORKSSUPPORTProjectID IN NVARCHAR2 DEFAULT -1
) 
AS 
BEGIN
  OPEN V_OUT FOR
      SELECT 
        PROJECT_MEMBER.MEMBERUSERNAME,
        PROJECT_MEMBER.WORKSSUPPORTPROJECTID,
        PROJECT_MEMBER.ISAUTOADDMEMBERTOWORKSGROUP

      FROM EO_WORKSSUPPORTPROJECT_MEMBER PROJECT_MEMBER  
      WHERE PROJECT_MEMBER.WORKSSUPPORTPROJECTID = V_WORKSSUPPORTProjectID
        AND PROJECT_MEMBER.ISDELETED = 0;
END;
/