CREATE OR REPLACE PROCEDURE WORKSSUPPORTGROUP_V2_UPD
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:	08/06/2017
	DESCRIPTION	:	C?P NH?T THÔNG TIN NHÓM CÔNG VI?C C?N H? TR? 
*/ (
    V_WORKSSUPPORTGROUPID     IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTGROUPID%TYPE,
    V_WORKSSUPPORTGROUPNAME   IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTGROUPNAME%TYPE,
    V_WORKSSUPPORTPROJECTID   IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTPROJECTID%TYPE,
    V_DESCRIPTION             IN EO_WORKSSUPPORTGROUP.DESCRIPTION%TYPE,
    V_UPDATEDUSER             IN EO_WORKSSUPPORTGROUP.UPDATEDUSER%TYPE,
    V_ICONURL                 IN EO_WORKSSUPPORTGROUP.ICONURL%TYPE,
    V_CERTIFICATESTRING       IN EO_WORKSSUPPORTGROUP_LOG.CERTIFICATESTRING%TYPE,
    V_USERHOSTADDRESS         IN EO_WORKSSUPPORTGROUP_LOG.USERHOSTADDRESS%TYPE,
    V_LOGINLOGID              IN EO_WORKSSUPPORTGROUP_LOG.LOGINLOGID%TYPE
)
    AS
BEGIN
    UPDATE EO_WORKSSUPPORTGROUP
        SET
            WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID,
            WORKSSUPPORTGROUPNAME = V_WORKSSUPPORTGROUPNAME,
            WORKSSUPPORTPROJECTID = V_WORKSSUPPORTPROJECTID,
            DESCRIPTION = V_DESCRIPTION,
            ICONURL = V_ICONURL,
            UPDATEDUSER = V_UPDATEDUSER,
            UPDATEDDATE = SYSDATE
    WHERE
        WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID;

    INSERT INTO EO_WORKSSUPPORTGROUP_LOG (
        WORKSSUPPORTGROUPID,
        WORKSSUPPORTGROUPNAME,
        WORKSSUPPORTPROJECTID,
        WORKSSUPPORTTYPEID,
        DESCRIPTION,
        ORDERINDEX,
        UPDATEDUSER,
        UPDATEDDATE,
        LOGTYPE,
        USERHOSTADDRESS,
        CERTIFICATESTRING,
        LOGINLOGID
    ) VALUES (
        V_WORKSSUPPORTGROUPID,
        V_WORKSSUPPORTGROUPNAME,
        V_WORKSSUPPORTPROJECTID,
        1,
        V_DESCRIPTION,
        V_WORKSSUPPORTGROUPID,
        V_UPDATEDUSER,
        SYSDATE,
        2,
        V_USERHOSTADDRESS,
        V_CERTIFICATESTRING,
        V_LOGINLOGID
    );

END;