CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTREPORT_V2_GETGROUP
/*
	CREATED BY	:	NGUYEN VAN HUAN
	      DATE  :	11/09/2017
	DESCRIPTION	:	N?P DANH SÁCH NHÓM CÔNG VI?C C?N H? TR? THEO PROJECTID CHO BAO CAO
*/
(   
    V_PROJECTID IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTPROJECTID%TYPE,
    V_OUT OUT SYS_REFCURSOR
)
  AS
  BEGIN
    OPEN V_OUT FOR
      SELECT WS.WORKSSUPPORTGROUPID,
             WS.WORKSSUPPORTGROUPNAME                              
        FROM EO_WORKSSUPPORTGROUP WS
       WHERE      WS.WORKSSUPPORTPROJECTID = V_PROJECTID 
             AND  WS.ISDELETED = 0;
  END;
/