CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORT_WORK_V2_Load
/*
	CREATED BY	:	NGUYEN THI KIM NGAN
	DATE		:11.07.2017
	DESCRIPTION	:	THEM CONG VIEC LIEN QUAN VAO CONG VIEC CAN HO TRO 
*/
(
  V_WORKSID EO_WORKSSUPPORT_WORKS.WORKSID%TYPE,
  V_NOTE IN EO_WORKSSUPPORT_WORKS.NOTE%TYPE DEFAULT NULL,
  V_OUT OUT SYS_REFCURSOR
)
AS
BEGIN
   OPEN V_OUT FOR 
  SELECT 
     EW.WORKSID
    ,EW.WORKSNAME
    ,EW.STARTDATE
    ,EW.ENDDATE
    ,EW.CURRENTPROGRESS
    FROM EO_WORKSSUPPORT_WORKS WORKS
    LEFT JOIN EO_WORKS EW ON WORKS.WORKSID = EW.WORKSID AND EW.ISDELETED =0
  WHERE 
    EW.ISDELETED = 0
    AND WORKS.WORKSID = V_WORKSID 
    ;
END;
/