CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORT_COMMENT_V2_SEL
/*
	CREATED BY	:	LUONG TRUNG NHÂN 
	DATE		:	19/06/2017
	DESCRIPTION	:	N?P THÔNG TIN  
*/ (
    V_WORKSSUPPORTID   IN EO_WORKSSUPPORT_COMMENT.WORKSSUPPORTID%TYPE,
    V_OUT              OUT SYS_REFCURSOR
)
    AS
BEGIN
    OPEN V_OUT FOR
        SELECT
            EO_WORKSSUPPORT_COMMENT.COMMENTID,
            EO_WORKSSUPPORT_COMMENT.WORKSSUPPORTID,
            EO_WORKSSUPPORT_COMMENT.COMMENTDATE,
            EO_WORKSSUPPORT_COMMENT.COMMENTCONTENT,
            EO_WORKSSUPPORT_COMMENT.COMMENTUSER,
            SYS_USER.FULLNAME,
            SYS_POSITION.POSITIONNAME,
            SYS_DEPARTMENT.DEPARTMENTNAME,
            SYS_USER.DEFAULTPICTUREURL
        FROM
            EO_WORKSSUPPORT_COMMENT
            JOIN SYS_USER ON LOWER(EO_WORKSSUPPORT_COMMENT.CREATEDUSER) = LOWER(SYS_USER.USERNAME)
            JOIN SYS_DEPARTMENT ON SYS_USER.DEPARTMENTID = SYS_DEPARTMENT.DEPARTMENTID
            JOIN SYS_POSITION ON SYS_USER.POSITIONID = SYS_POSITION.POSITIONID
        WHERE
            V_WORKSSUPPORTID = WORKSSUPPORTID
        AND
            EO_WORKSSUPPORT_COMMENT.ISDELETED = 0
        ORDER BY
            EO_WORKSSUPPORT_COMMENT.CREATEDDATE DESC;

END;
/