create or replace PROCEDURE WORKSSUPPORT_V2_PERWORK
/*
	CREATED BY	:	TRUONG HOANG NHI
	DATE		:	01/08/2017
	DESCRIPTION	:	N?P QUYEN NHÓM CÔNG VI?C C?N H? TR? THEO VAI TRO THANH VIEN DU AN
*/
(       
    V_USERNAME IN EO_WORKSSUPPORTGROUP_MEMBER.MEMBERUSERNAME%TYPE,
    V_WORKSSUPPORTID IN EO_WORKSSUPPORT.WORKSSUPPORTID%TYPE,
    V_OUT OUT SYS_REFCURSOR
)
 AS  
  BEGIN
     OPEN V_OUT FOR
      SELECT  
            MEMBERROLE.ISCANADDWORKSSUPPORT,
            MEMBERROLE.ISCANEDITWORKSSUPPORT,
            MEMBERROLE.ISCANDELETEWORKSSUPPORT
        FROM 
            EO_WORKSSUPPORTTYPE_MEMBERROLE MEMBERROLE
        INNER JOIN 
            EO_WORKSSUPPORTGROUP_MEMBER MEMBERS
        ON 
            MEMBERROLE.WORKSSUPPORTMEMBERROLEID = MEMBERS.WORKSSUPPORTMEMBERROLEID 
        AND 
            MEMBERS.MEMBERUSERNAME = V_USERNAME
        AND 
            MEMBERS.WORKSSUPPORTGROUPID = (
                SELECT
                    WORKSSUPPORTGROUPID
                FROM
                    EO_WORKSSUPPORT
                WHERE
                    WORKSSUPPORTID = V_WORKSSUPPORTID
            )
        INNER JOIN
            EO_WORKSSUPPORTPROJECT PROJECTS
        ON
            PROJECTS.WORKSSUPPORTTYPEID = MEMBERROLE.WORKSSUPPORTTYPEID
        INNER JOIN 
            EO_WORKSSUPPORTGROUP EO_WORKSSUPPORTGROUP
        ON 
            PROJECTS.WORKSSUPPORTPROJECTID = EO_WORKSSUPPORTGROUP.WORKSSUPPORTPROJECTID
        AND 
            EO_WORKSSUPPORTGROUP.WORKSSUPPORTGROUPID = 
            (
                SELECT
                    WORKSSUPPORTGROUPID
                FROM
                    EO_WORKSSUPPORT
                WHERE
                    WORKSSUPPORTID = V_WORKSSUPPORTID
            )
        GROUP BY 
            MEMBERROLE.ISCANADDWORKSSUPPORT,
            MEMBERROLE.ISCANEDITWORKSSUPPORT,
            MEMBERROLE.ISCANDELETEWORKSSUPPORT;
  END;