CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTTYPE_V2_DEL
/*
	CREATED BY	:	HOÀNG NHU PHONG 
	DATE		:	02/03/2013
	DESCRIPTION	:	XÓA THÔNG TIN LO?I CÔNG VI?C C?N H? TR? 
*/
(
	V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE.WORKSSUPPORTTYPEID%TYPE,
	V_DELETEDUSER IN EO_WORKSSUPPORTTYPE.DELETEDUSER%TYPE,
  V_CERTIFICATESTRING IN EO_WORKSSUPPORTTYPE_LOG.CERTIFICATESTRING%TYPE,
	V_USERHOSTADDRESS IN EO_WORKSSUPPORTTYPE_LOG.USERHOSTADDRESS%TYPE,
	V_LOGINLOGID IN EO_WORKSSUPPORTTYPE_LOG.LOGINLOGID%TYPE
)
AS
 V_ORDERINDEXDEL NUMBER;
BEGIN
   --1. LAY ODERINDEX CU DUOC DOI CAP NHAT THANH MOI
  SELECT EW.ORDERINDEX INTO V_ORDERINDEXDEL FROM EO_WORKSSUPPORTTYPE EW
    WHERE WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID;

  --2. XOA DU LIEU
	UPDATE EO_WORKSSUPPORTTYPE
	SET
		ISDELETED = 1,
		DELETEDDATE = SYSDATE,
		DELETEDUSER = V_DELETEDUSER
	WHERE
		WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID;

  --3. CAP NHAT LAI TAT CA CAC GIA TR? ORDERINDEX CÓ GIÁ TR? L?N HON ORDERINDEX B? XÓA
	UPDATE EO_WORKSSUPPORTTYPE
	SET
		ORDERINDEX = ORDERINDEX-1
	WHERE
		ORDERINDEX > V_ORDERINDEXDEL AND ISDELETED = 0 ;
  INSERT  INTO EO_WORKSSUPPORTTYPE_LOG
	(
		WORKSSUPPORTTYPEID,
		WORKSSUPPORTTYPENAME,
		ICONURL,
		ADDFUNCTIONID,
		VIEWALLFUNCTIONID,
		EDITFUNCTIONID,
		EDITALLFUNCTIONID,
		DELETEFUNCTIONID,
		DELETEALLFUNCTIONID,
		PROCESSFUNCTIONID,
		COMMENTFUNCTIONID,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		UPDATEDUSER,
		UPDATEDDATE,
		LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID

	)
  SELECT WORKSSUPPORTTYPEID,
		WORKSSUPPORTTYPENAME,
		ICONURL,
		ADDFUNCTIONID,
		VIEWALLFUNCTIONID,
		EDITFUNCTIONID,
		EDITALLFUNCTIONID,
		DELETEFUNCTIONID,
		DELETEALLFUNCTIONID,
		PROCESSFUNCTIONID,
		COMMENTFUNCTIONID,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		V_DELETEDUSER,
		UPDATEDDATE,
		3,
		V_USERHOSTADDRESS,
		V_CERTIFICATESTRING,
		V_LOGINLOGID
    FROM EO_WORKSSUPPORTTYPE
    WHERE WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID;
  
  --4. XÓA D? ÁN CÔNG VI?C C?N H? TR?
	UPDATE EO_WORKSSUPPORTPROJECT
 	SET
		ISDELETED = 1,
		DELETEDDATE = SYSDATE,
		DELETEDUSER = V_DELETEDUSER
	WHERE
    EXISTS (SELECT EW.WORKSSUPPORTTYPEID 
              FROM EO_WORKSSUPPORTTYPE EW
             WHERE      EW.WORKSSUPPORTTYPEID = EO_WORKSSUPPORTPROJECT.WORKSSUPPORTTYPEID
                   AND  EW.WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID);
  INSERT
	INTO EO_WORKSSUPPORTPROJECT_LOG
	(
		WORKSSUPPORTPROJECTID,
		WORKSSUPPORTPROJECTNAME,
		WORKSSUPPORTTYPEID,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		UPDATEDUSER,
		UPDATEDDATE,
		LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID

	)
  SELECT  WORKSSUPPORTPROJECTID
    		, WORKSSUPPORTPROJECTNAME
    		, WORKSSUPPORTTYPEID
    		, DESCRIPTION
    		, ORDERINDEX
    		, ISACTIVE
    		, ISSYSTEM 
    		, V_DELETEDUSER
    		, UPDATEDDATE
        , 3
    		, V_USERHOSTADDRESS
    		, V_CERTIFICATESTRING
    		, V_LOGINLOGID
    FROM    EO_WORKSSUPPORTPROJECT PROJECT
   WHERE  EXISTS (SELECT EW.WORKSSUPPORTTYPEID 
                    FROM EO_WORKSSUPPORTTYPE EW
                   WHERE      EW.WORKSSUPPORTTYPEID = PROJECT.WORKSSUPPORTTYPEID
                         AND  EW.WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID);  
                                    
END;
/