CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTTYPE_V2_ADD
/*
	Created by	:	Hoàng Nhu Phong 
	Date		:	02/03/2013
	Description	:	Thêm thông tin Lo?i công vi?c c?n h? tr? 
*/
(
    V_OUT OUT NUMBER,
	--v_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE.WORKSSUPPORTTYPEID%TYPE,
	v_WORKSSUPPORTTYPENAME IN EO_WORKSSUPPORTTYPE.WORKSSUPPORTTYPENAME%TYPE,
	v_ICONURL IN EO_WORKSSUPPORTTYPE.ICONURL%TYPE,
	v_ADDFUNCTIONID IN EO_WORKSSUPPORTTYPE.ADDFUNCTIONID%TYPE,
	v_VIEWALLFUNCTIONID IN EO_WORKSSUPPORTTYPE.VIEWALLFUNCTIONID%TYPE, 
	v_EDITFUNCTIONID IN EO_WORKSSUPPORTTYPE.EDITFUNCTIONID%TYPE,
	v_EDITALLFUNCTIONID IN EO_WORKSSUPPORTTYPE.EDITALLFUNCTIONID%TYPE,
	v_DELETEFUNCTIONID IN EO_WORKSSUPPORTTYPE.DELETEFUNCTIONID%TYPE,
	v_DELETEALLFUNCTIONID IN EO_WORKSSUPPORTTYPE.DELETEALLFUNCTIONID%TYPE,
	v_PROCESSFUNCTIONID IN EO_WORKSSUPPORTTYPE.PROCESSFUNCTIONID%TYPE,
	v_COMMENTFUNCTIONID IN EO_WORKSSUPPORTTYPE.COMMENTFUNCTIONID%TYPE,
	v_DESCRIPTION IN EO_WORKSSUPPORTTYPE.DESCRIPTION%TYPE,	
	v_ISACTIVE IN EO_WORKSSUPPORTTYPE.ISACTIVE%TYPE,
	v_ISSYSTEM IN EO_WORKSSUPPORTTYPE.ISSYSTEM%TYPE,
	v_CREATEDUSER IN EO_WORKSSUPPORTTYPE.CREATEDUSER%TYPE,
	v_CERTIFICATESTRING IN EO_WORKSSUPPORTTYPE_LOG.CERTIFICATESTRING%TYPE,
	v_USERHOSTADDRESS IN EO_WORKSSUPPORTTYPE_LOG.USERHOSTADDRESS%TYPE,
	v_LOGINLOGID IN EO_WORKSSUPPORTTYPE_LOG.LOGINLOGID%TYPE
)
AS
t_count number;
T_ORDERINDEX NUMBER := 0 ;
BEGIN
-- begin 
--    select max(ORDERINDEX) into t_count from EO_WORKSSUPPORTTYPE;
--    exception when others then t_count:=0;
--  end; 
  SELECT NVL(max(ORDERINDEX),0)+1 INTO T_ORDERINDEX 
    FROM 
         EO_WORKSSUPPORTTYPE
    WHERE ISDELETED = 0;
	INSERT
	INTO EO_WORKSSUPPORTTYPE
	(
	--	WORKSSUPPORTTYPEID,
		WORKSSUPPORTTYPENAME,
		ICONURL,
		ADDFUNCTIONID,
		VIEWALLFUNCTIONID,
		EDITFUNCTIONID,
		EDITALLFUNCTIONID,
		DELETEFUNCTIONID,
		DELETEALLFUNCTIONID,
		PROCESSFUNCTIONID,
		COMMENTFUNCTIONID,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		CREATEDUSER,
		CREATEDDATE
	)
	VALUES
	(
	--	v_WORKSSUPPORTTYPEID,
		v_WORKSSUPPORTTYPENAME,
		v_ICONURL,
		v_ADDFUNCTIONID,
		v_VIEWALLFUNCTIONID,
		v_EDITFUNCTIONID,
		v_EDITALLFUNCTIONID,
		v_DELETEFUNCTIONID,
		v_DELETEALLFUNCTIONID,
		v_PROCESSFUNCTIONID,
		v_COMMENTFUNCTIONID,
		v_DESCRIPTION,
		T_ORDERINDEX,
		v_ISACTIVE,
		v_ISSYSTEM,
		v_CREATEDUSER,
		SYSDATE
	)RETURNING WORKSSUPPORTTYPEID INTO V_OUT;
	INSERT
	INTO EO_WORKSSUPPORTTYPE_LOG
	(
	--	WORKSSUPPORTTYPEID,
		WORKSSUPPORTTYPENAME,
		ICONURL,
		ADDFUNCTIONID,
		VIEWALLFUNCTIONID,
		EDITFUNCTIONID,
		EDITALLFUNCTIONID,
		DELETEFUNCTIONID,
		DELETEALLFUNCTIONID,
		PROCESSFUNCTIONID,
		COMMENTFUNCTIONID,
		DESCRIPTION,
		ORDERINDEX,
		ISACTIVE,
		ISSYSTEM,
		UPDATEDUSER,
		UPDATEDDATE,
		LOGTYPE,
		USERHOSTADDRESS,
		CERTIFICATESTRING,
		LOGINLOGID

	)
	VALUES
	(
	--	v_WORKSSUPPORTTYPEID,
		v_WORKSSUPPORTTYPENAME,
		v_ICONURL,
		v_ADDFUNCTIONID,
		v_VIEWALLFUNCTIONID,
		v_EDITFUNCTIONID,
		v_EDITALLFUNCTIONID,
		v_DELETEFUNCTIONID,
		v_DELETEALLFUNCTIONID,
		v_PROCESSFUNCTIONID,
		v_COMMENTFUNCTIONID,
		v_DESCRIPTION,
		T_ORDERINDEX,
		v_ISACTIVE,
		v_ISSYSTEM,
		v_CREATEDUSER,
		SYSDATE,
		1,
		v_USERHOSTADDRESS,
		v_CERTIFICATESTRING,
		v_LOGINLOGID
	);
END;
/