CREATE OR REPLACE PROCEDURE ERP.WORKSSUPORTPROJECT_V2_ISACTIVE
(
  V_OUT OUT SYS_REFCURSOR,
  V_USERNAME IN ERP.EO_WORKSSUPPORTPROJECT_MEMBER.MEMBERUSERNAME%TYPE
)
AS
BEGIN
  OPEN V_OUT FOR
  SELECT 
    PROJECT.WORKSSUPPORTPROJECTID,
    PROJECT.WORKSSUPPORTPROJECTNAME,
    PROJECT.WORKSSUPPORTTYPEID,
    PROJECT.ISACTIVE,
    PROJECT.ISSYSTEM,
    ICONURL,
    (SELECT COUNT(1) 
      FROM EO_WORKSSUPPORTGROUP EW 
        WHERE EW.WORKSSUPPORTPROJECTID = PROJECT.WORKSSUPPORTPROJECTID
          AND EW.ISDELETED =0)AS NUMBEROFWORKGROUP,
    (SELECT COUNT(1)
      FROM EO_WORKSSUPPORTPROJECT_MEMBER EWM
      WHERE EWM.WORKSSUPPORTPROJECTID = PROJECT.WORKSSUPPORTPROJECTID
        AND EWM.ISDELETED =0) AS NUMBEROFMEMBER
  FROM
    ERP.EO_WORKSSUPPORTPROJECT PROJECT   
   LEFT JOIN EO_WORKSSUPPORTPROJECT_MEMBER PROJECT_MEMBER 
    ON  PROJECT_MEMBER.MEMBERUSERNAME = V_USERNAME AND project_member.workssupportprojectid = project.workssupportprojectid
  WHERE
    PROJECT.ISACTIVE = 1 AND 
    PROJECT.ISDELETED = 0   
  ORDER BY
    PROJECT.ISACTIVE DESC;  
END;
/