create or replace PROCEDURE     WS_CMT_ATTACHMENT_V2_ADD
/*
	Created by	:	Hoàng Vãn Minh 
	Date		:	8/8/2016
	Description	:	Thêm file ðính kèm cho b?nh lu?n công vi?c c?n h? tr?  
*/
(
  	V_COMMENTID IN EO_WORKSSUPPORT_CMT_ATTACHMENT.COMMENTID%TYPE,
  	V_COMMENTDATE IN EO_WORKSSUPPORT_CMT_ATTACHMENT.COMMENTDATE%TYPE,
  	V_FILEPATH IN EO_WORKSSUPPORT_CMT_ATTACHMENT.FILEPATH%TYPE,
  	V_FILENAME IN EO_WORKSSUPPORT_CMT_ATTACHMENT.FILENAME%TYPE,
  	V_FILEID IN EO_WORKSSUPPORT_CMT_ATTACHMENT.FILEID%TYPE,
  	V_CREATEDUSER IN EO_WORKSSUPPORT_CMT_ATTACHMENT.CREATEDUSER%TYPE
)
AS
BEGIN

	INSERT
	INTO EO_WORKSSUPPORT_CMT_ATTACHMENT
	(
		COMMENTID,
		COMMENTDATE,
		FILEPATH,
		FILENAME,
		FILEID,
		CREATEDUSER,
		CREATEDDATE
	)
	VALUES
	(
		V_COMMENTID,
		V_COMMENTDATE,
		V_FILEPATH,
		V_FILENAME,
		V_FILEID,
		V_CREATEDUSER,
		SYSDATE
	);

END;
