CREATE OR REPLACE PROCEDURE ERP.WS_REPORT_V2_WorkGroup_STATE
/*
	CREATED BY	:	NGUYEN VAN HUAN
	      DATE  :	11/09/2017
	DESCRIPTION	:	TH?NG KÊ CÔNG VI?C THEO TÌNH TR?NG 
*/
( 
   V_OUT OUT SYS_REFCURSOR,
   V_WORKSSUPPORTPROJECTID IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTPROJECTID%TYPE,
   V_WORKSSUPPORTGROUPID IN EO_WORKSSUPPORTGROUP.WORKSSUPPORTGROUPID%TYPE,
   V_FROMDATE IN EO_WORKSSUPPORT.CREATEDDATE%TYPE,
   V_TODATE IN EO_WORKSSUPPORT.CREATEDDATE%TYPE,
   V_Type IN number
  )
AS 
BEGIN
  IF (V_Type = 1) THEN
     
     OPEN V_OUT FOR
      SELECT  E_GROUP.WORKSSUPPORTGROUPID
              ,e_group.workssupportgroupname
              ,count(1) AS NumberOfWork
        FROM  EO_WORKSSUPPORTGROUP E_GROUP
   LEFT join  eo_workssupport e_work
          on  E_GROUP.workssupportgroupid = e_work.workssupportgroupid
              AND e_work.isdeleted = 0
              AND (V_WORKSSUPPORTGROUPID IS NULL OR e_work.WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID)              
       WHERE  E_GROUP.WORKSSUPPORTGROUPID = E_WORK.WORKSSUPPORTGROUPID
              AND E_GROUP.WORKSSUPPORTPROJECTID = V_WORKSSUPPORTPROJECTID
              AND E_GROUP.ISDELETED =0
              AND (V_WORKSSUPPORTGROUPID IS NULL OR E_GROUP.WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID)
              AND TRUNC(E_WORK.COMPLETEDDATE) < TRUNC(E_WORK.EXPECTEDCOMPLETEDDATE)
              AND (V_FROMDATE IS NULL OR TRUNC(V_FROMDATE) <= TRUNC(E_WORK.CREATEDDATE))
              AND (V_TODATE IS NULL OR TRUNC(V_TODATE) >= TRUNC(E_WORK.CREATEDDATE)) 
      GROUP BY E_GROUP.WORKSSUPPORTGROUPID, e_group.workssupportgroupname;  
     
 
  END IF;
            
        
END;
/