CREATE OR REPLACE PROCEDURE ERP.WSGROUP_MEMBER_V2_UPD
/*
	CREATED BY	:NGUYEN THI KIM NGAN
	DATE		:	09/06/2017
	DESCRIPTION	:	C?P NH?T THÔNG TIN THANH VIEN THAM GIA NHOM CONG VIEC
*/
(
	V_WORKSSUPPORTGROUPID IN EO_WORKSSUPPORTGROUP_MEMBER.WORKSSUPPORTGROUPID%TYPE,
	V_MEMBERUSERNAME IN EO_WORKSSUPPORTGROUP_MEMBER.MEMBERUSERNAME%TYPE,
  V_UPDATEDUSER IN EO_WORKSSUPPORTGROUP_MEMBER.UPDATEDUSER%TYPE,
  V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORTGROUP_MEMBER.WORKSSUPPORTMEMBERROLEID%TYPE,
  V_ISAUTOADDMEMBER IN EO_WORKSSUPPORTGROUP_MEMBER.ISAUTOADDMEMBERTOWORKSSUPPORT%TYPE
) 
AS

BEGIN
	UPDATE EO_WORKSSUPPORTGROUP_MEMBER
	SET
        ISAUTOADDMEMBERTOWORKSSUPPORT = V_ISAUTOADDMEMBER,
  		  WORKSSUPPORTMEMBERROLEID = V_WORKSSUPPORTMEMBERROLEID,
  		  UPDATEDUSER	= V_UPDATEDUSER,
  		  updateddate = sysdate
	WHERE
		    WORKSSUPPORTGROUPID = V_WORKSSUPPORTGROUPID
    AND MEMBERUSERNAME= V_MEMBERUSERNAME
    and (ISAUTOADDMEMBERTOWORKSSUPPORT <> V_ISAUTOADDMEMBER 
    OR   workssupportmemberroleid <> v_workssupportmemberroleid);

END;
/