CREATE OR REPLACE PROCEDURE ERP.EO_WORKSSUPPORTTYPE_P_SEL
/*
	CREATED BY	:	LUONG TRUNG NHÂN 
	DATE		:	02/06/2017
	DESCRIPTION	:	N?P THÔNG TIN B?NG LIÊN K?T LO?I CÔNG VI?C VÀ Ð? UU TIÊN CÔNG VI?C
*/
(	
	V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE_PRIORITY.WORKSSUPPORTTYPEID%TYPE,	
	V_OUT OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN V_OUT FOR
	SELECT
		WORKSSUPPORTTYPEID,
		WORKSSUPPORTPRIORITYID
	FROM 
    EO_WORKSSUPPORTTYPE_PRIORITY
	WHERE
		WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID;
END;
/