create or replace PROCEDURE  EO_WORKSSUPPORT_SOLUTIONATM_ID
/*
	CREATED BY	:	LÝÕNG TRUNG NHÂN
	DATE		:	19/07/2017
	DESCRIPTION	:	N?P THÔNG TIN DANH SÁCH FILE DÍNH KÈM C?A CÔNG VI?C C?N H? TR? 
*/
(	
	V_FILEID IN EO_WORKSSUPPORT_SOLUTIONATM.FILEID%TYPE,	
	V_OUT OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN V_OUT FOR
	SELECT
        ATTACHMENTID,
		WORKSSUPPORTID,
		FILEPATH,
		FILENAME,
        FILEID
	FROM 
        EO_WORKSSUPPORT_SOLUTIONATM
	WHERE
		FILEID = V_FILEID
  AND ISDELETED = 0
;
END;