create or replace PROCEDURE EO_WORKSSUPPORTTYPE_WFNX_P_SEL
/*
	CREATED BY	:	LÝÕNG TRUNG NHÂN 
	DATE		:	02/06/2017
	DESCRIPTION	:	N?P THÔNG TIN B?NG CH?A CÁC BÝ?C X? L? K? TI?P
*/ (
    V_WORKSSUPPORTSTEPID   IN EO_WORKSSUPPORTTYPE_WFNXPERMIS.WORKSSUPPORTSTEPID%TYPE,
    V_WORKSSUPPORTTYPEID   IN EO_WORKSSUPPORTTYPE_WFNXPERMIS.WORKSSUPPORTTYPEID%TYPE,
    V_OUT                  OUT SYS_REFCURSOR
)
    AS
BEGIN
    OPEN V_OUT FOR
        SELECT
            WORKSSUPPORTSTEPID,
            (
                SELECT
                    WORKSSUPPORTSTEPNAME
                FROM
                    EO_WORKSSUPPORTTYPE_WORKFLOW
                WHERE
                    EO_WORKSSUPPORTTYPE_WORKFLOW.WORKSSUPPORTSTEPID = V_WORKSSUPPORTSTEPID
            ) AS WORKSSUPPORTSTEPNAME,
            NEXTWORKSSUPPORTSTEPID,
            WORKSSUPPORTMEMBERROLEID,
            WORKSSUPPORTTYPEID
        FROM
            EO_WORKSSUPPORTTYPE_WFNXPERMIS
        WHERE
            WORKSSUPPORTSTEPID = V_WORKSSUPPORTSTEPID
        AND
            WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID;

END;