CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTPRIORITY_V2_SElHR
/*
	Created by	:	Nguyen thi kim ngan 
	Date		:	29.05.2014
	Description	:	N?p thông tin do uu tien công vi?c c?n h? tr? 
*/
(	
	V_WORKSSUPPORTPRIORITYID IN EO_WORKSSUPPORTPRIORITY.WORKSSUPPORTPRIORITYID%type,	
	v_Out OUT SYS_REFCURSOR
) 
AS
BEGIN
    OPEN v_Out FOR
	SELECT
		*
	FROM 
    EO_WORKSSUPPORTPRIORITY
	WHERE
		WORKSSUPPORTPRIORITYID = V_WORKSSUPPORTPRIORITYID
;
END;
/