create or replace PROCEDURE EO_WORKSSUPPORTTYPE_WFNX_SEL
/*
	CREATED BY	:	LÝÕNG TRUNG NHÂN 
	DATE		:	02/06/2017
	DESCRIPTION	:	N?P THÔNG TIN B?NG CH?A CÁC BÝ?C X? L? K? TI?P
*/ (
    V_WORKSSUPPORTTYPEID   IN EO_WORKSSUPPORTTYPE_WF_NX.WORKSSUPPORTTYPEID%TYPE,
    V_WORKSSUPPORTSTEPID   IN EO_WORKSSUPPORTTYPE_WF_NX.WORKSSUPPORTSTEPID%TYPE,
    V_OUT                  OUT SYS_REFCURSOR
)
    AS
BEGIN
    OPEN V_OUT FOR
        SELECT
            NX.WORKSSUPPORTTYPEID,
            NX.NEXTWORKSSUPPORTSTEPID,            
            NX.WORKSSUPPORTSTEPID,            
            NX.CHOOSEFUNCTIONID,
            WF.WORKSSUPPORTSTEPNAME
        FROM
            EO_WORKSSUPPORTTYPE_WF_NX NX
        JOIN
            EO_WORKSSUPPORTTYPE_WORKFLOW WF
        ON 
            NX.NEXTWORKSSUPPORTSTEPID = WF.WORKSSUPPORTSTEPID
        WHERE
            NX.WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID
        AND
            NX.WORKSSUPPORTSTEPID = V_WORKSSUPPORTSTEPID;

END;