create or replace PROCEDURE     EO_WORKSSUPPORTTYPE_WF_P_ADD
/*
	Created by	:	Hoàng Nhý Phong 
	Date		:	02/03/2013
	Description	:	Thêm thông tin Lo?i công vi?c c?n h? tr? 
*/
(
	V_WORKSSUPPORTSTEPID IN EO_WORKSSUPPORTTYPE_WF_PERMIS.WORKSSUPPORTSTEPID%TYPE,
	V_WORKSSUPPORTMEMBERROLEID IN EO_WORKSSUPPORTTYPE_WF_PERMIS.WORKSSUPPORTMEMBERROLEID%TYPE,
    V_ISCANPROCESSWORKFLOW IN EO_WORKSSUPPORTTYPE_WF_PERMIS.ISCANPROCESSWORKFLOW%TYPE,
    V_CREATEDUSER IN EO_WORKSSUPPORTTYPE_WF_PERMIS.CREATEDUSER%TYPE
)
AS
--t_count number;
BEGIN
	INSERT
	INTO EO_WORKSSUPPORTTYPE_WF_PERMIS
	(
        WORKSSUPPORTSTEPID,
        WORKSSUPPORTMEMBERROLEID,    
        ISCANPROCESSWORKFLOW,
        CREATEDUSER,
        CREATEDDATE
	)
	VALUES
	(
        V_WORKSSUPPORTSTEPID,
        V_WORKSSUPPORTMEMBERROLEID,
        V_ISCANPROCESSWORKFLOW,
        V_CREATEDUSER,
        SYSDATE
	);
END;
