create or replace PROCEDURE     EO_WORKSSUPPORTTYPE_WFNX_DEL
/*
	CREATED BY	:	LÝÕNG TRUNG NHÂN 
	DATE		:	02/06/2017
	DESCRIPTION	:	XÓA THÔNG TIN B?NG CH?A CÁC BÝ?C X? L? K? TI?P
*/
(
	V_WORKSSUPPORTSTEPID IN EO_WORKSSUPPORTTYPE_WF_NX.WORKSSUPPORTSTEPID%TYPE
)
AS
BEGIN
	DELETE EO_WORKSSUPPORTTYPE_WF_NX
	WHERE
		WORKSSUPPORTSTEPID = WORKSSUPPORTSTEPID;
END;
