CREATE OR REPLACE PROCEDURE ERP.WSMEMBERROLE_V2_GETALL
  /*
	CREATED BY	:	NGUY?N TH? KIM NGÂN
	DATE		:	22/07/2017
	DESCRIPTION	: NAP VAI TRO CUA THANH VIEN TRONG DU AN 
*/
(
  V_OUT OUT SYS_REFCURSOR,
  V_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE.WORKSSUPPORTTYPEID%TYPE
)
AS
BEGIN
  OPEN V_OUT FOR
   SELECT
    TYPEROLE.WORKSSUPPORTMEMBERROLEID,
    MEMBERROLE.WORKSSUPPORTMEMBERROLENAME
    FROM EO_WORKSSUPPORTTYPE_MEMBERROLE TYPEROLE
    LEFT JOIN EO_WORKSSUPPORTMEMBERROLE MEMBERROLE 
      ON MEMBERROLE.WORKSSUPPORTMEMBERROLEID = TYPEROLE.WORKSSUPPORTMEMBERROLEID 
        AND MEMBERROLE.ISDELETED =0 
    WHERE
      TYPEROLE.WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID
      AND MEMBERROLE.ISDELETED = 0
    order by  MEMBERROLE.WORKSSUPPORTMEMBERROLENAME ASC;
--and TYPEROLE.ISDEFAULTROLE =1;
  
END;
/