CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTGROUP_V2_GETROLE
/*
	CREATED BY	:	NGUYEN VAN HUAN
	DATE		:	01/08/2017
	DESCRIPTION	:	N?P QUYEN NHÓM CÔNG VI?C C?N H? TR? THEO VAI TRO THANH VIEN DU AN
*/
(   
    V_PROJECTID IN EO_WORKSSUPPORTPROJECT_MEMBER.WORKSSUPPORTPROJECTID%TYPE,
    V_USERNAME IN EO_WORKSSUPPORTPROJECT_MEMBER.MEMBERUSERNAME%TYPE,
    V_WORKTYPEID IN EO_WORKSSUPPORTTYPE_MEMBERROLE.WORKSSUPPORTTYPEID%TYPE,
    V_OUT OUT SYS_REFCURSOR
)
 AS  
  BEGIN
     OPEN V_OUT FOR
       SELECT  
        EWM.ISCANADDWORKSSUPPORTGROUP,
        EWM.ISCANADDWORKSSUPPORT,
        EWM.ISCANEDITWORKSSUPPORTGROUP,
        EWM.ISCANEDITWORKSSUPPORT,
        EWM.ISCANDELETEWORKSSUPPORTGROUP,
        EWM.ISCANDELETEWORKSSUPPORT
        FROM EO_WORKSSUPPORTTYPE_MEMBERROLE EWM, EO_WORKSSUPPORTPROJECT_MEMBER EW 
        where  EW.WORKSSUPPORTPROJECTID = V_PROJECTID AND EW.MEMBERUSERNAME = V_USERNAME AND
            EW.ISDELETED = 0 AND EWM.WORKSSUPPORTTYPEID = V_WORKTYPEID AND
            EW.WORKSSUPPORTMEMBERROLEID = EWM.WORKSSUPPORTMEMBERROLEID;      
  END;
/