create or replace PROCEDURE WORKSSUPPORTTYPE_V2_UPD
/*
	Created by	:	Nguyen Thi Kim Ngan
	Date		:	21/06/2017
	Description	:	C?p nh?t thông tin Tr?ng thái công vi?c c?n h? tr? 
*/
(
	v_WORKSSUPPORTTYPEID IN EO_WORKSSUPPORTTYPE.WorksSupportTypeID%TYPE,
	v_WORKSSUPPORTTYPENAME IN EO_WORKSSUPPORTTYPE.WORKSSUPPORTTYPENAME%TYPE,
	v_ICONURL IN EO_WORKSSUPPORTTYPE.ICONURL%TYPE,
	v_DESCRIPTION IN EO_WORKSSUPPORTTYPE.DESCRIPTION%TYPE,
	v_ORDERINDEX IN EO_WORKSSUPPORTTYPE.ORDERINDEX%TYPE,
	v_ISACTIVE IN EO_WORKSSUPPORTTYPE.ISACTIVE%TYPE,
	v_ISSYSTEM IN EO_WORKSSUPPORTTYPE.ISSYSTEM%TYPE,
	v_UPDATEDUSER IN EO_WORKSSUPPORTTYPE.UPDATEDUSER%TYPE DEFAULT NULL,
	v_CERTIFICATESTRING IN EO_WORKSSUPPORTTYPE_LOG.CERTIFICATESTRING%TYPE,
	v_USERHOSTADDRESS IN EO_WORKSSUPPORTTYPE_LOG.USERHOSTADDRESS%TYPE,
	v_LOGINLOGID IN EO_WORKSSUPPORTTYPE_LOG.LOGINLOGID%TYPE
) 
AS
BEGIN

UPDATE EO_WORKSSUPPORTTYPE
  	SET
  		WORKSSUPPORTTYPENAME	= V_WORKSSUPPORTTYPENAME,
  		ICONURL	= v_ICONURL,
  		DESCRIPTION	= V_DESCRIPTION,
  		ORDERINDEX	= V_ORDERINDEX,
  		ISACTIVE	= V_ISACTIVE,
  		ISSYSTEM	= V_ISSYSTEM,
  		UPDATEDUSER	= V_UPDATEDUSER,
  		UPDATEDDATE	= sysdate
  	WHERE
  		WORKSSUPPORTTYPEID = V_WORKSSUPPORTTYPEID;
--	INSERT
--	INTO EO_WORKSSUPPORTTYPE_LOG
--	(
--		WORKSSUPPORTTYPEID,
--		WORKSSUPPORTTYPENAME,
--		ICONURL,
--		DESCRIPTION,
--		ORDERINDEX,
--		ISACTIVE,
--		ISSYSTEM,
--		UPDATEDUSER,
--		UPDATEDDATE,
--		LOGTYPE,
--		USERHOSTADDRESS,
--		CERTIFICATESTRING,
--		LOGINLOGID
--	)
--	VALUES
--	(
--		V_WORKSSUPPORTTYPEID,
--		V_WORKSSUPPORTTYPENAME,
--		v_ICONURL,
--        v_DESCRIPTION,
--        v_ORDERINDEX,
--		V_ISACTIVE,
--		V_ISSYSTEM,
--		v_UPDATEDUSER,
--		SYSDATE,
--		2,
--		v_USERHOSTADDRESS,
--		v_CERTIFICATESTRING,
--		v_LOGINLOGID
--	);
END;