CREATE OR REPLACE PROCEDURE ERP.WORKSSUPPORTMEMBERROLE_V2_GETS
  /*
	Created by	:	NGUYEN THI KIM NGAN
	Date		:	30.05.2017
	Description	:	N?p danh sách vai tro cua công vi?c c?n h? tr? 
*/
(
  V_OUT OUT SYS_REFCURSOR
)
AS
BEGIN
  OPEN V_OUT FOR
  SELECT
    EO_WORKSSUPPORTMEMBERROLE.WORKSSUPPORTMEMBERROLEID,
    EO_WORKSSUPPORTMEMBERROLE.WORKSSUPPORTMEMBERROLENAME,
    EO_WORKSSUPPORTMEMBERROLE.DESCRIPTION,
    EO_WORKSSUPPORTMEMBERROLE.ICONURL,
    EO_WORKSSUPPORTMEMBERROLE.ORDERINDEX,
    EO_WORKSSUPPORTMEMBERROLE.ISACTIVE,
    EO_WORKSSUPPORTMEMBERROLE.ISSYSTEM
  FROM
    EO_WORKSSUPPORTMEMBERROLE
  WHERE
    --EO_WORKSSUPPORTMEMBERROLE.ISACTIVE = 1 AND
     EO_WORKSSUPPORTMEMBERROLE.ISDELETED = 0
  ORDER BY
    EO_WORKSSUPPORTMEMBERROLE.ORDERINDEX
  ;
END;
/